package br.com.lexoffice.icpbridge;

import com.sun.net.httpserver.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.security.cert.X509Certificate;import java.util.*;import javax.security.auth.callback.*;import javax.swing.*;

public final class BridgeMain {
 static final String DLL=System.getenv().getOrDefault("LEXOFFICE_PKCS11_DLL","C:\\Windows\\System32\\aetpkss1.dll");
 static volatile Provider provider; static volatile KeyStore ks;
 public static void main(String[] a)throws Exception{System.setProperty("java.awt.headless","false");HttpServer s=HttpServer.create(new InetSocketAddress(InetAddress.getLoopbackAddress(),17681),0);s.createContext("/health",x->json(x,200,"{\"ok\":true,\"service\":\"LEXOFFICE ICP-Brasil Bridge\",\"pkcs11\":\""+esc(DLL)+"\"}"));s.createContext("/certificates",BridgeMain::certificates);s.createContext("/sign/pades",BridgeMain::sign);s.setExecutor(java.util.concurrent.Executors.newCachedThreadPool());s.start();System.out.println("LEXOFFICE ICP-Brasil Bridge: http://127.0.0.1:17681");}
 static boolean origin(HttpExchange x){String o=x.getRequestHeaders().getFirst("Origin");return o==null||o.equals("https://lexoffice-ashy.vercel.app")||o.startsWith("http://localhost:")||o.startsWith("http://127.0.0.1:");}
 static void cors(HttpExchange x){String o=x.getRequestHeaders().getFirst("Origin");if(o!=null&&origin(x)){x.getResponseHeaders().set("Access-Control-Allow-Origin",o);x.getResponseHeaders().set("Vary","Origin");}x.getResponseHeaders().set("Access-Control-Allow-Methods","GET,POST,OPTIONS");x.getResponseHeaders().set("Access-Control-Allow-Headers","Content-Type,X-Lexoffice-Bridge");x.getResponseHeaders().set("Access-Control-Allow-Private-Network","true");}
 static synchronized KeyStore store()throws Exception{if(ks!=null)return ks;Provider base=Security.getProvider("SunPKCS11");if(base==null)throw new GeneralSecurityException("SunPKCS11 indisponível");String cfg="name=LexofficeA3\nlibrary="+DLL.replace("\\","/")+"\n";File f=File.createTempFile("lexoffice-p11-",".cfg");java.nio.file.Files.writeString(f.toPath(),cfg);f.deleteOnExit();provider=base.configure(f.getAbsolutePath());Security.addProvider(provider);ks=KeyStore.getInstance("PKCS11",provider);ks.load(null,null);return ks;}
 static void certificates(HttpExchange x)throws IOException{cors(x);if("OPTIONS".equals(x.getRequestMethod())){x.sendResponseHeaders(204,-1);return;}if(!origin(x)){json(x,403,"{\"error\":\"origin blocked\"}");return;}try{KeyStore k=store();List<String> out=new ArrayList<>();Enumeration<String> en=k.aliases();while(en.hasMoreElements()){String al=en.nextElement();java.security.cert.Certificate c=k.getCertificate(al);if(c instanceof X509Certificate z){out.add("{\"subject\":\""+esc(z.getSubjectX500Principal().getName())+"\",\"issuer\":\""+esc(z.getIssuerX500Principal().getName())+"\",\"fingerprint\":\""+hex(MessageDigest.getInstance("SHA-256").digest(z.getEncoded()))+"\",\"alias\":\""+esc(al)+"\"}");}}json(x,200,"{\"certificates\":["+String.join(",",out)+"]}");}catch(Exception e){json(x,500,"{\"error\":\""+esc(e.getMessage())+"\"}");}}
 static void sign(HttpExchange x)throws IOException{cors(x);if("OPTIONS".equals(x.getRequestMethod())){x.sendResponseHeaders(204,-1);return;}if(!origin(x)){json(x,403,"{\"error\":\"origin blocked\"}");return;}json(x,501,"{\"error\":\"Módulo PAdES aguardando ativação criptográfica; nenhuma assinatura falsa foi produzida.\"}");}
 static void json(HttpExchange x,int code,String b)throws IOException{cors(x);byte[] d=b.getBytes(StandardCharsets.UTF_8);x.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");x.sendResponseHeaders(code,d.length);try(OutputStream o=x.getResponseBody()){o.write(d);}}
 static String esc(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\n"," ");}static String hex(byte[] b){StringBuilder s=new StringBuilder();for(byte v:b)s.append(String.format("%02X",v));return s.toString();}
}
