package br.com.lexoffice.icpbridge;

import com.sun.net.httpserver.*;
import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.security.cert.Certificate;import java.security.cert.X509Certificate;import java.util.*;import javax.swing.*;
import org.apache.pdfbox.Loader;import org.apache.pdfbox.pdmodel.*;import org.apache.pdfbox.pdmodel.font.*;import org.apache.pdfbox.pdmodel.interactive.digitalsignature.*;
import org.bouncycastle.cert.jcajce.JcaCertStore;import org.bouncycastle.cms.*;import org.bouncycastle.cms.jcajce.JcaSignerInfoGeneratorBuilder;import org.bouncycastle.operator.ContentSigner;import org.bouncycastle.operator.jcajce.*;

public final class BridgeMain {
 static final String DLL=System.getenv().getOrDefault("LEXOFFICE_PKCS11_DLL","C:\\Windows\\System32\\aetpkss1.dll");
 static volatile Provider provider; static volatile KeyStore publicStore;
 public static void main(String[] a)throws Exception{System.setProperty("java.awt.headless","false");Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());HttpServer s=HttpServer.create(new InetSocketAddress(InetAddress.getLoopbackAddress(),17681),0);s.createContext("/health",x->json(x,200,"{\"ok\":true,\"service\":\"LEXOFFICE ICP-Brasil Bridge\",\"version\":\"1.1.0\",\"pkcs11\":\""+esc(DLL)+"\"}"));s.createContext("/certificates",BridgeMain::certificates);s.createContext("/sign/pades",BridgeMain::sign);s.setExecutor(java.util.concurrent.Executors.newCachedThreadPool());s.start();System.out.println("LEXOFFICE ICP-Brasil Bridge ativo em http://127.0.0.1:17681");}
 static boolean origin(HttpExchange x){String o=x.getRequestHeaders().getFirst("Origin");return o==null||o.equals("https://lexoffice-ashy.vercel.app")||o.startsWith("http://localhost:")||o.startsWith("http://127.0.0.1:");}
 static void cors(HttpExchange x){String o=x.getRequestHeaders().getFirst("Origin");if(o!=null&&origin(x)){x.getResponseHeaders().set("Access-Control-Allow-Origin",o);x.getResponseHeaders().set("Vary","Origin");}x.getResponseHeaders().set("Access-Control-Allow-Methods","GET,POST,OPTIONS");x.getResponseHeaders().set("Access-Control-Allow-Headers","Content-Type,X-Lexoffice-Bridge");x.getResponseHeaders().set("Access-Control-Allow-Private-Network","true");}
 static synchronized Provider p11()throws Exception{if(provider!=null)return provider;Provider base=Security.getProvider("SunPKCS11");if(base==null)throw new GeneralSecurityException("SunPKCS11 indisponível");String cfg="name=LexofficeA3\nlibrary="+DLL.replace("\\","/")+"\n";File f=File.createTempFile("lexoffice-p11-",".cfg");java.nio.file.Files.writeString(f.toPath(),cfg);f.deleteOnExit();provider=base.configure(f.getAbsolutePath());Security.addProvider(provider);return provider;}
 static synchronized KeyStore store(char[] pin)throws Exception{KeyStore k=KeyStore.getInstance("PKCS11",p11());k.load(null,pin);return k;}
 static void certificates(HttpExchange x)throws IOException{cors(x);if("OPTIONS".equals(x.getRequestMethod())){x.sendResponseHeaders(204,-1);return;}if(!origin(x)){json(x,403,"{\"error\":\"origin blocked\"}");return;}try{if(publicStore==null)publicStore=store(null);List<String> out=new ArrayList<>();Enumeration<String> en=publicStore.aliases();while(en.hasMoreElements()){String al=en.nextElement();Certificate c=publicStore.getCertificate(al);if(c instanceof X509Certificate z){out.add("{\"subject\":\""+esc(z.getSubjectX500Principal().getName())+"\",\"issuer\":\""+esc(z.getIssuerX500Principal().getName())+"\",\"fingerprint\":\""+hex(MessageDigest.getInstance("SHA-256").digest(z.getEncoded()))+"\",\"notBefore\":\""+z.getNotBefore().toInstant()+"\",\"notAfter\":\""+z.getNotAfter().toInstant()+"\"}");}}json(x,200,"{\"certificates\":["+String.join(",",out)+"]}");}catch(Exception e){json(x,500,"{\"error\":\""+esc(msg(e))+"\"}");}}
 static void sign(HttpExchange x)throws IOException{cors(x);if("OPTIONS".equals(x.getRequestMethod())){x.sendResponseHeaders(204,-1);return;}if(!origin(x)){json(x,403,"{\"error\":\"origin blocked\"}");return;}try{Parts p=Parts.parse(x);if(p.file==null||p.file.length<5)throw new IllegalArgumentException("PDF não recebido.");if(!new String(p.file,0,Math.min(5,p.file.length),StandardCharsets.ISO_8859_1).startsWith("%PDF"))throw new IllegalArgumentException("Arquivo recebido não é PDF.");char[] pin=askPin();if(pin==null)throw new IllegalStateException("Assinatura cancelada no computador.");try{KeyStore k=store(pin);String alias=findAlias(k,p.fingerprint);if(alias==null)throw new GeneralSecurityException("Certificado selecionado não encontrado no token.");PrivateKey key=(PrivateKey)k.getKey(alias,pin);Certificate[] chain=k.getCertificateChain(alias);if(key==null||chain==null||chain.length==0)throw new GeneralSecurityException("Chave privada/cadeia não disponível no token.");X509Certificate cert=(X509Certificate)chain[0];cert.checkValidity();byte[] out=signPdf(p.file,key,chain,cert,p.visibleSeal);cors(x);x.getResponseHeaders().set("Content-Type","application/pdf");x.getResponseHeaders().set("X-Lexoffice-Signer",esc(cert.getSubjectX500Principal().getName()));x.sendResponseHeaders(200,out.length);try(OutputStream os=x.getResponseBody()){os.write(out);}}finally{Arrays.fill(pin,'\0');}}catch(Exception e){json(x,500,"{\"error\":\""+esc(msg(e))+"\"}");}}
 static byte[] signPdf(byte[] input,PrivateKey key,Certificate[] chain,X509Certificate cert,boolean seal)throws Exception{try(PDDocument doc=Loader.loadPDF(input);ByteArrayOutputStream out=new ByteArrayOutputStream()){if(seal&&doc.getNumberOfPages()>0)addSeal(doc,cert);PDSignature sig=new PDSignature();sig.setFilter(PDSignature.FILTER_ADOBE_PPKLITE);sig.setSubFilter(PDSignature.SUBFILTER_ETSI_CADES_DETACHED);sig.setName(cn(cert));sig.setReason("Assinatura digital ICP-Brasil");sig.setLocation("Brasil");sig.setSignDate(Calendar.getInstance());SignatureOptions opts=new SignatureOptions();opts.setPreferredSignatureSize(SignatureOptions.DEFAULT_SIGNATURE_SIZE*3);doc.addSignature(sig,content->cms(content,key,chain,cert),opts);doc.saveIncremental(out);opts.close();return out.toByteArray();}}
 static byte[] cms(InputStream content,PrivateKey key,Certificate[] chain,X509Certificate cert)throws IOException{try{CMSSignedDataGenerator gen=new CMSSignedDataGenerator();String alg=key.getAlgorithm().equalsIgnoreCase("EC")?"SHA256withECDSA":"SHA256withRSA";ContentSigner signer=new JcaContentSignerBuilder(alg).setProvider(p11()).build(key);gen.addSignerInfoGenerator(new JcaSignerInfoGeneratorBuilder(new JcaDigestCalculatorProviderBuilder().setProvider("BC").build()).build(signer,cert));gen.addCertificates(new JcaCertStore(Arrays.asList(chain)));CMSTypedData data=new CMSTypedData(){public org.bouncycastle.asn1.ASN1ObjectIdentifier getContentType(){return CMSObjectIdentifiers.data;}public Object getContent(){return content;}public void write(OutputStream o)throws IOException,CMSException{content.transferTo(o);}};return gen.generate(data,false).getEncoded();}catch(Exception e){throw new IOException("Falha criptográfica no token: "+msg(e),e);}}
 static void addSeal(PDDocument doc,X509Certificate cert)throws IOException{PDPage page=doc.getPage(doc.getNumberOfPages()-1);try(PDPageContentStream cs=new PDPageContentStream(doc,page,PDPageContentStream.AppendMode.APPEND,true,true)){float x=42,y=42;cs.setLineWidth(0.8f);cs.addRect(x,y,300,54);cs.stroke();PDType1Font font=new PDType1Font(Standard14Fonts.FontName.HELVETICA);PDType1Font bold=new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);cs.beginText();cs.setFont(bold,9);cs.newLineAtOffset(x+8,y+38);cs.showText(safe("ASSINADO DIGITALMENTE — ICP-BRASIL"));cs.setFont(font,8);cs.newLineAtOffset(0,-13);cs.showText(safe(cn(cert)));cs.newLineAtOffset(0,-11);cs.showText(safe("Emissor: "+shortIssuer(cert)+" | "+new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new Date())));cs.endText();}}
 static char[] askPin()throws Exception{final JPasswordField field=new JPasswordField(18);Object[] m={"Informe o PIN do seu token A3.","O PIN permanece somente neste computador.",field};final int[] r=new int[1];SwingUtilities.invokeAndWait(()->{r[0]=JOptionPane.showConfirmDialog(null,m,"LEXOFFICE — Assinatura ICP-Brasil",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);});return r[0]==JOptionPane.OK_OPTION?field.getPassword():null;}
 static String findAlias(KeyStore k,String fp)throws Exception{Enumeration<String> en=k.aliases();while(en.hasMoreElements()){String a=en.nextElement();Certificate c=k.getCertificate(a);if(c instanceof X509Certificate z){String h=hex(MessageDigest.getInstance("SHA-256").digest(z.getEncoded()));if(fp==null||fp.isBlank()||h.equalsIgnoreCase(fp))return a;}}return null;}
 static String cn(X509Certificate c){String s=c.getSubjectX500Principal().getName();for(String p:s.split(","))if(p.trim().startsWith("CN="))return p.trim().substring(3);return s;}static String shortIssuer(X509Certificate c){String s=c.getIssuerX500Principal().getName();for(String p:s.split(","))if(p.trim().startsWith("CN="))return p.trim().substring(3);return s;}
 static void json(HttpExchange x,int code,String b)throws IOException{cors(x);byte[] d=b.getBytes(StandardCharsets.UTF_8);x.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");x.sendResponseHeaders(code,d.length);try(OutputStream o=x.getResponseBody()){o.write(d);}}
 static String msg(Throwable e){Throwable t=e;while(t.getCause()!=null)t=t.getCause();return t.getMessage()!=null?t.getMessage():e.getClass().getSimpleName();}static String safe(String s){return s==null?"":s.replace("—","-").replace("•","-").replaceAll("[^\\x20-\\x7EÀ-ÿ]"," ");}static String esc(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\n"," ").replace("\r"," ");}static String hex(byte[] b){StringBuilder s=new StringBuilder();for(byte v:b)s.append(String.format("%02X",v));return s.toString();}
 static final class Parts{byte[] file;String fingerprint;boolean visibleSeal=true;static Parts parse(HttpExchange x)throws IOException{String ct=x.getRequestHeaders().getFirst("Content-Type");if(ct==null||!ct.contains("boundary="))throw new IOException("multipart/form-data inválido");String boundary=ct.substring(ct.indexOf("boundary=")+9).replace("\"","").trim();byte[] raw=x.getRequestBody().readAllBytes();String text=new String(raw,StandardCharsets.ISO_8859_1);String marker="--"+boundary;Parts out=new Parts();int pos=0;while((pos=text.indexOf(marker,pos))>=0){int hs=text.indexOf("\r\n\r\n",pos);if(hs<0)break;int dataStart=hs+4,end=text.indexOf("\r\n"+marker,dataStart);if(end<0)break;String h=text.substring(pos,hs);String name=attr(h,"name");byte[] data=Arrays.copyOfRange(raw,dataStart,end);if("file".equals(name))out.file=data;else{String v=new String(data,StandardCharsets.UTF_8).trim();if("certificateFingerprint".equals(name))out.fingerprint=v;if("visibleSeal".equals(name))out.visibleSeal=Boolean.parseBoolean(v);}pos=end+2;}return out;}static String attr(String h,String n){String q=n+"=\"";int a=h.indexOf(q);if(a<0)return null;int b=h.indexOf('"',a+q.length());return b<0?null:h.substring(a+q.length(),b);}}
}
