import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
function admin(){const url=Deno.env.get("SUPABASE_URL")!;let key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";try{key=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default||key}catch{}return createClient(url,key,{auth:{persistSession:false}})}
function userClient(req:Request){const url=Deno.env.get("SUPABASE_URL")!;let key=Deno.env.get("SUPABASE_ANON_KEY")||"";try{key=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}").default||key}catch{}return createClient(url,key,{global:{headers:{Authorization:req.headers.get("Authorization")||""}},auth:{persistSession:false}})}
function b64url(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return new Response(JSON.stringify({error:"Método inválido."}),{status:405,headers:cors});try{const client=userClient(req);const jwt=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(!jwt)return new Response(JSON.stringify({error:"Sessão inválida."}),{status:401,headers:cors});const {data:{user},error:userError}=await client.auth.getUser(jwt);if(userError||!user)return new Response(JSON.stringify({error:"Sessão inválida."}),{status:401,headers:cors});const db=admin();const {data:profile,error:profileError}=await db.from("profiles").select("org_id").eq("id",user.id).maybeSingle();if(profileError||!profile?.org_id)return new Response(JSON.stringify({error:"Usuário sem escritório vinculado."}),{status:403,headers:cors});const raw=b64url(crypto.getRandomValues(new Uint8Array(32)));const expiresAt=new Date(Date.now()+7*24*60*60*1000).toISOString();const {error}=await db.from("client_intake_links").insert({org_id:profile.org_id,owner_user_id:user.id,created_by:user.id,token_hash:await sha256(raw),expires_at:expiresAt});if(error)throw error;return new Response(JSON.stringify({ok:true,token:raw,expires_at:expiresAt}),{headers:cors})}catch(e){console.error("client-intake-link-create",e);return new Response(JSON.stringify({error:"Não foi possível gerar o link agora."}),{status:500,headers:cors})}});
