import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "jsr:@supabase/supabase-js@2.57.4";
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
const digits=(v:any)=>String(v??'').replace(/\D/g,'');
const admin=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
async function secret(a:any,key:string){try{const{data}=await a.from('system_runtime_secrets').select('secret').eq('key',key).maybeSingle();return String(data?.secret||'').trim()}catch{return''}}
function phoneOf(b:any){return digits(b?.phone||b?.sender?.phone||b?.from||b?.chatId||b?.participantPhone||b?.senderPhone)}
function textOf(b:any){return String(b?.text?.message||b?.text?.description||b?.message?.text||b?.message?.body||b?.body||b?.caption||'').trim()}
function choiceOf(b:any){return String(b?.buttonsResponseMessage?.buttonId||b?.buttonResponse?.buttonId||b?.listResponseMessage?.selectedRowId||b?.listResponse?.selectedRowId||b?.selectedButtonId||b?.selectedRowId||'').trim()}
async function office(a:any){const{data,error}=await a.from('integration_connections').select('org_id,owner_user_id').eq('provider','whatsapp').eq('status','connected').contains('settings',{provider:'zapi'}).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(error||!data)throw new Error('Conexão Z-API ativa não encontrada');return data}
async function ensureConversation(a:any,b:any,phone:string){const off=await office(a);let{data:ct}=await a.from('whatsapp_contacts').select('id,org_id,client_id,lead_id,owner_user_id').eq('org_id',off.org_id).eq('phone',phone).limit(1).maybeSingle();if(!ct){const name=String(b?.senderName||b?.chatName||b?.sender?.name||b?.pushName||'Contato WhatsApp').trim();const ins=await a.from('whatsapp_contacts').insert({org_id:off.org_id,owner_user_id:off.owner_user_id,phone,name,profile_name:name,whatsapp_id:phone}).select('id,org_id,client_id,lead_id,owner_user_id').single();if(ins.error)throw ins.error;ct=ins.data}let{data:cv}=await a.from('whatsapp_conversations').select('id,org_id,bot_ativo,conversation_owner,last_human_outbound_at').eq('org_id',off.org_id).eq('contact_id',ct.id).neq('status','closed').order('updated_at',{ascending:false}).limit(1).maybeSingle();if(!cv){const{data:conn}=await a.from('whatsapp_connections').select('id').eq('org_id',off.org_id).eq('is_active',true).limit(1).maybeSingle();const ins=await a.from('whatsapp_conversations').insert({org_id:off.org_id,owner_user_id:off.owner_user_id,connection_id:conn?.id||null,contact_id:ct.id,client_id:ct.client_id||null,lead_id:ct.lead_id||null,status:'open',bot_ativo:true,conversation_owner:'HELENA',last_message_at:new Date().toISOString()}).select('id,org_id,bot_ativo,conversation_owner,last_human_outbound_at').single();if(ins.error)throw ins.error;cv=ins.data}return{ct,cv,off}}
Deno.serve(async(req)=>{if(req.method!=='POST')return json({ok:false},405);try{const a=admin(),key=(await secret(a,'zapi_webhook_key')).trim(),url=new URL(req.url);if(key&&url.searchParams.get('key')!==key)return json({ok:false,error:'unauthorized'},401);const b=await req.json().catch(()=>({}));if(b?.fromMe===true||b?.from_me===true||b?.isGroup===true||b?.isNewsletter===true||b?.isStatusReply===true)return json({ok:true,ignored:true});const phone=phoneOf(b);if(!phone)return json({ok:true,ignored:true,reason:'phone_not_found'});const{cv}=await ensureConversation(a,b,phone);const selected=choiceOf(b),text=textOf(b);const{data:st}=await a.from('whatsapp_chatbot_flow_state').select('current_node').eq('conversation_id',cv.id).maybeSingle();const node=String(st?.current_node||'start'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const invoke=async(payload:any)=>{const r=await fetch(`${Deno.env.get('SUPABASE_URL')}/functions/v1/whatsapp-chatbot-flow`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${service}`},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw new Error(d?.error||`chatbot ${r.status}`);return d};if(selected){const result=await invoke({org_id:cv.org_id,conversation_id:cv.id,phone,node,choice:selected});if(result?.node)await a.from('whatsapp_chatbot_flow_state').upsert({conversation_id:cv.id,org_id:cv.org_id,current_node:result.node,updated_at:new Date().toISOString()});if(result?.handoff){await a.from('whatsapp_chatbot_flow_state').upsert({conversation_id:cv.id,org_id:cv.org_id,current_node:result.next_node||'after_ai',updated_at:new Date().toISOString()});if(result.agent_key==='human'){await a.from('whatsapp_conversations').update({bot_ativo:false,conversation_owner:'HUMAN',owner_agent_key:null,owner_changed_at:new Date().toISOString()}).eq('id',cv.id)}else{await a.from('whatsapp_conversations').update({bot_ativo:true,conversation_owner:'HELENA',owner_agent_key:result.agent_key,owner_changed_at:new Date().toISOString()}).eq('id',cv.id);try{await a.from('ai_orchestrator_events').insert({org_id:cv.org_id,conversation_id:cv.id,event_type:'chatbot_menu_handoff',agent_key:result.agent_key,decision:'selected',metadata:{selected:result.selected,next_node:result.next_node,phone}})}catch{}}}return json({ok:true,event:'chatbot_choice',result})}const hello=/^(oi|olá|ola|bom dia|boa tarde|boa noite|menu|início|inicio)$/i.test(text);if(!st||hello){const result=await invoke({org_id:cv.org_id,conversation_id:cv.id,phone,node:'start'});await a.from('whatsapp_chatbot_flow_state').upsert({conversation_id:cv.id,org_id:cv.org_id,current_node:'start',updated_at:new Date().toISOString()});return json({ok:true,event:'chatbot_menu',result})}return json({ok:true,event:'free_text',conversation_id:cv.id,owner:cv.conversation_owner})}catch(e){console.error('zapi-received-webhook',e);return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
