import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const J=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json; charset=utf-8"}});
const digits=(v:string)=>String(v||'').replace(/\D/g,'');
const safe=(v:string)=>String(v||'').replace(/[%(),]/g,' ').replace(/[^0-9A-Za-zÀ-ÿ@._+\- /]/g,'').trim();
type Input='cpf'|'cnpj'|'phone'|'plate'|'cnj'|'name'|'unknown';
type Def={slug:string;title:string;provider_mode:string;input_kind:string};

function detect(q:string):Input{const raw=q.trim(),d=digits(raw),plate=raw.replace(/[^A-Za-z0-9]/g,'');if(d.length===20)return'cnj';if(d.length===14)return'cnpj';if(d.length===11&&/^[0-9]+$/.test(d))return'cpf';if(d.length>=10&&d.length<=13)return'phone';if(/^[A-Za-z]{3}[0-9][A-Za-z0-9][0-9]{2}$/.test(plate))return'plate';if(/[A-Za-zÀ-ÿ]{2,}/.test(raw))return'name';return'unknown'}
function accepts(kind:string,input:Input){const m:Record<string,Input[]>={phone:['phone'],cpf:['cpf'],cnpj:['cnpj'],cpf_cnpj:['cpf','cnpj'],plate:['plate'],name_or_cpf:['name','cpf'],name_or_document:['name','cpf','cnpj'],document_or_name:['name','cpf','cnpj']};return(m[kind]||['cpf','cnpj','phone','plate','cnj','name','unknown']).includes(input)}

async function phoneLookup(q:string){let d=digits(q);if(d.startsWith('55')&&d.length>=12)d=d.slice(2);const ddd=d.slice(0,2);if(ddd.length!==2)throw Object.assign(new Error('Informe um telefone brasileiro com DDD.'),{status:400});const r=await fetch(`https://brasilapi.com.br/api/ddd/v1/${ddd}`);const x=await r.json().catch(()=>null);if(!r.ok)throw Object.assign(new Error(x?.message||'DDD não localizado na fonte pública.'),{status:r.status===404?404:502});return{status:'completed',source:'BrasilAPI / consulta pública de DDD',result:{telefone_informado:q,ddd,uf:x?.state||null,cidades:Array.isArray(x?.cities)?x.cities:[],aviso:'Consulta pública por DDD. Não identifica titular, CPF, endereço individual nem operadora da linha.'}}}

async function cnpjLookup(q:string,title:string){const cnpj=digits(q);if(cnpj.length!==14)throw Object.assign(new Error('Informe um CNPJ com 14 dígitos.'),{status:400});const r=await fetch(`https://brasilapi.com.br/api/cnpj/v1/${cnpj}`);const d=await r.json().catch(()=>null);if(!r.ok)throw Object.assign(new Error(d?.message||'CNPJ não encontrado na fonte pública.'),{status:r.status===404?404:502});const base={cnpj:d.cnpj,razao_social:d.razao_social,nome_fantasia:d.nome_fantasia,situacao:d.descricao_situacao_cadastral,data_situacao:d.data_situacao_cadastral,cnae_principal:d.cnae_fiscal_descricao,endereco:{logradouro:d.logradouro,numero:d.numero,bairro:d.bairro,municipio:d.municipio,uf:d.uf,cep:d.cep},telefones:[d.ddd_telefone_1,d.ddd_telefone_2].filter(Boolean),email:d.email,capital_social:d.capital_social,qsa:d.qsa||[],cnaes_secundarios:d.cnaes_secundarios||[]};if(title==='Grupo econômico')return{status:'completed',source:'BrasilAPI / dados públicos da Receita Federal',result:{empresa:base,vinculos_societarios:d.qsa||[],aviso:'Vínculos societários isoladamente não comprovam grupo econômico.'}};if(title==='Participações societárias')return{status:'completed',source:'BrasilAPI / dados públicos da Receita Federal',result:{empresa:{cnpj:base.cnpj,razao_social:base.razao_social,nome_fantasia:base.nome_fantasia},qsa:d.qsa||[]}};if(title==='Situação cadastral')return{status:'completed',source:'BrasilAPI / dados públicos da Receita Federal',result:{cnpj:base.cnpj,razao_social:base.razao_social,nome_fantasia:base.nome_fantasia,situacao:base.situacao,data_situacao:base.data_situacao,endereco:base.endereco}};return{status:'completed',source:'BrasilAPI / dados públicos da Receita Federal',result:base}}

async function processLookup(db:any,org:string,q:string){const input=detect(q),d=digits(q),term=safe(q),rows:any[]=[],seen=new Set<string>();const add=(a:any[]|null)=>{for(const x of a||[])if(!seen.has(x.id)){seen.add(x.id);rows.push(x)}};const fields='id,cnj_number,internal_number,subject,class_name,status,court,vara,comarca,opposing_party,source,last_synced_at,clients(name,cpf_cnpj)';if(['cpf','cnpj','name'].includes(input)){let cq=db.from('clients').select('id').eq('org_id',org).limit(50);cq=input==='name'?cq.ilike('name',`%${term}%`):cq.ilike('cpf_cnpj',`%${d}%`);const c=await cq;if(c.error)throw c.error;const ids=(c.data||[]).map((x:any)=>x.id);if(ids.length){const p=await db.from('processes').select(fields).eq('org_id',org).in('client_id',ids).limit(50);if(p.error)throw p.error;add(p.data)}}if(term){const pt=input==='cnj'?d:term;const p=await db.from('processes').select(fields).eq('org_id',org).or(`cnj_number.ilike.%${pt}%,internal_number.ilike.%${pt}%,subject.ilike.%${term}%,opposing_party.ilike.%${term}%`).limit(50);if(p.error)throw p.error;add(p.data)}return{status:'completed',source:'LEXOFFICE / sincronizações judiciais DataJud e bases internas',result:{matches:rows,count:rows.length,input_type:input,observacao:'Processos sincronizados pelo DataJud público ficam disponíveis nesta base quando vinculados ao escritório.'}}}

async function internalLookup(db:any,org:string,def:Def,q:string){if(def.slug==='processes')return processLookup(db,org,q);const d=digits(q),term=safe(q);let x=db.from('clients').select('id,name,cpf_cnpj,rg,birth_date,profession,address,phone,whatsapp,email,status').eq('org_id',org).limit(50);x=d.length>=6?x.ilike('cpf_cnpj',`%${d}%`):x.ilike('name',`%${term}%`);const r=await x;if(r.error)throw r.error;const a=r.data||[];if(def.slug==='professional-data')return{status:'completed',source:'Cadastro interno autorizado do LEXOFFICE',result:{matches:a.map((v:any)=>({id:v.id,name:v.name,cpf_cnpj:v.cpf_cnpj,profession:v.profession,status:v.status})),count:a.length}};if(def.slug==='person-location')return{status:'completed',source:'Cadastro interno autorizado do LEXOFFICE',result:{matches:a.map((v:any)=>({id:v.id,name:v.name,cpf_cnpj:v.cpf_cnpj,address:v.address,phone:v.phone,whatsapp:v.whatsapp,email:v.email})),count:a.length}};return{status:'completed',source:'Cadastro interno autorizado do LEXOFFICE',result:{matches:a,count:a.length}}}

async function runOne(db:any,org:string,def:Def,q:string){const input=detect(q);if(!accepts(def.input_kind,input))return{status:'not_applicable',source:'Formato incompatível com esta categoria',result:{message:`O dado informado foi identificado como ${input} e não se aplica a esta consulta.`,input_type:input}};if(def.provider_mode==='public_ddd'||def.slug==='phone-data')return phoneLookup(q);if(def.provider_mode==='public_cnpj')return cnpjLookup(q,def.title);if(def.provider_mode==='internal')return internalLookup(db,org,def,q);return{status:'provider_required',source:'Provedor oficial/autorizado necessário',result:{message:`A consulta “${def.title}” depende de fonte oficial ou provedor autorizado ainda não disponível gratuitamente para automação.`,input_type:input}}}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return J({error:'method_not_allowed'},405);try{const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const auth=req.headers.get('Authorization')||'';const uc=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user}}=await uc.auth.getUser();if(!user)return J({error:'Sessão inválida.'},401);const db=createClient(url,service,{auth:{persistSession:false}});const pr=await db.from('profiles').select('org_id').eq('id',user.id).maybeSingle();if(pr.error)throw pr.error;if(!pr.data?.org_id)return J({error:'Organização não encontrada.'},403);const org=pr.data.org_id,body=await req.json().catch(()=>({})),action=String(body.action||'single');const cat=await db.from('investigation_catalog').select('slug,title,description,category,input_kind,provider_mode,novelty,sort_order').eq('enabled',true).order('sort_order');if(cat.error)throw cat.error;if(action==='catalog')return J({ok:true,catalog:cat.data||[]});const q=String(body.query||'').trim();if(!q)return J({error:'Informe o dado que deseja consultar.'},400);const defs=(cat.data||[]) as Def[],input_type=detect(q);
if(action==='batch'){const reqs=Array.isArray(body.slugs)&&body.slugs.length?body.slugs.map(String):defs.map(x=>x.slug),sel=defs.filter(x=>reqs.includes(x.slug));if(!sel.length)return J({error:'Nenhuma categoria válida selecionada.'},400);const b=await db.from('investigation_batches').insert({org_id:org,user_id:user.id,query_text:q,status:'processing',total_items:sel.length}).select('id').single();if(b.error)throw b.error;const out:any[]=[];let completed=0,failed=0,provider_required=0,not_applicable=0;for(const def of sel){try{const r=await runOne(db,org,def,q);await db.from('investigation_searches').insert({org_id:org,user_id:user.id,search_type:def.title,search_slug:def.slug,query_text:q,status:r.status,source:r.source,result:r.result,batch_id:b.data.id});await db.from('investigation_batch_items').insert({batch_id:b.data.id,org_id:org,search_type:def.title,search_slug:def.slug,status:r.status,source:r.source,result:r.result});out.push({slug:def.slug,title:def.title,...r});if(r.status==='completed')completed++;else if(r.status==='provider_required')provider_required++;else not_applicable++}catch(e:any){failed++;const msg=e instanceof Error?e.message:String(e);await db.from('investigation_batch_items').insert({batch_id:b.data.id,org_id:org,search_type:def.title,search_slug:def.slug,status:'failed',source:'Erro',result:{},error_message:msg});out.push({slug:def.slug,title:def.title,status:'failed',source:'Erro',error:msg})}}const status=failed?'partial':'completed';await db.from('investigation_batches').update({status,completed_items:completed+provider_required+not_applicable,completed_at:new Date().toISOString()}).eq('id',b.data.id);return J({ok:true,batch_id:b.data.id,status,input_type,summary:{completed,provider_required,not_applicable,failed},results:out,checked_at:new Date().toISOString()})}
const slug=String(body.slug||''),def=defs.find(x=>x.slug===slug);if(!def)return J({error:'Categoria de investigação inválida.'},400);try{const r=await runOne(db,org,def,q);const s=await db.from('investigation_searches').insert({org_id:org,user_id:user.id,search_type:def.title,search_slug:def.slug,query_text:q,status:r.status,source:r.source,result:r.result}).select('id').single();if(s.error)throw s.error;return J({ok:true,search_id:s.data.id,slug:def.slug,title:def.title,input_type,...r,checked_at:new Date().toISOString()})}catch(e:any){return J({error:e instanceof Error?e.message:String(e)},Number(e?.status)||500)}}catch(e){console.error(e);return J({error:e instanceof Error?e.message:String(e)},500)}});
