import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const nowMs=()=>Date.now();
const J=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const digits=(v:string)=>String(v||'').replace(/\D/g,'');
const safe=(v:string)=>String(v||'').replace(/[%(),]/g,' ').replace(/[^0-9A-Za-zÀ-ÿ@._+\- /]/g,'').trim();
type Input='cpf'|'cnpj'|'phone'|'plate'|'cnj'|'name'|'unknown';
type Def={slug:string;title:string;description?:string;category?:string;provider_mode:string;input_kind:string;novelty?:boolean;sort_order?:number};

function detect(q:string):Input{const raw=q.trim(),d=digits(raw),plate=raw.replace(/[^A-Za-z0-9]/g,'');if(d.length===20)return'cnj';if(d.length===14)return'cnpj';if(d.length===11&&/^[0-9]+$/.test(d))return'cpf';if(d.length>=10&&d.length<=13)return'phone';if(/^[A-Za-z]{3}[0-9][A-Za-z0-9][0-9]{2}$/.test(plate))return'plate';if(/[A-Za-zÀ-ÿ]{2,}/.test(raw))return'name';return'unknown'}
function detectFor(def:Def,q:string):Input{const d=digits(q);if(def.slug==='phone-data'&&d.length>=10&&d.length<=13)return'phone';return detect(q)}
function accepts(kind:string,input:Input){const m:Record<string,Input[]>={phone:['phone'],cpf:['cpf'],cnpj:['cnpj'],cpf_cnpj:['cpf','cnpj'],plate:['plate'],name_or_cpf:['name','cpf'],name_or_document:['name','cpf','cnpj'],document_or_name:['name','cpf','cnpj'],freeform:['cpf','cnpj','phone','plate','cnj','name','unknown']};return(m[kind]||['cpf','cnpj','phone','plate','cnj','name','unknown']).includes(input)}
const UTILITY_INPUT:Record<string,Input[]>={'phone-data':['phone'],'cep-address':['unknown'],'bank-data':['unknown','name'],'pix-participants':['unknown','name'],'ncm-data':['unknown','name'],'registrobr-domain':['name'],'cvm-broker':['cnpj'],'vehicle-renavam':['unknown'],'property-certificate':['unknown'],'property-encumbrances':['unknown']};
function applies(def:Def,input:Input){const forced=UTILITY_INPUT[def.slug];if(forced)return forced.includes(input);if(def.slug==='processes'&&input==='cnj')return true;return accepts(def.input_kind,input)}

async function apiJson(url:string,init:RequestInit={}){const r=await fetch(url,init);const x=await r.json().catch(()=>null);if(!r.ok)throw Object.assign(new Error(x?.message||x?.error||'Falha na consulta pública.'),{status:r.status===404?404:502});return x}

const TJ_BY_CODE:Record<string,string>={'01':'tjac','02':'tjal','03':'tjap','04':'tjam','05':'tjba','06':'tjce','07':'tjdft','08':'tjes','09':'tjgo','10':'tjma','11':'tjmt','12':'tjms','13':'tjmg','14':'tjpa','15':'tjpb','16':'tjpr','17':'tjpe','18':'tjpi','19':'tjrj','20':'tjrn','21':'tjrs','22':'tjro','23':'tjrr','24':'tjsc','25':'tjse','26':'tjsp','27':'tjto'};
function datajudAlias(cnj:string){const d=digits(cnj);if(d.length!==20)return null;const ramo=d[13],trib=d.slice(14,16);if(ramo==='8')return TJ_BY_CODE[trib]||null;if(ramo==='4')return 'trf'+String(Number(trib));if(ramo==='5')return 'trt'+String(Number(trib));if(ramo==='6')return trib==='00'?'tse':null;return null}
async function datajudLookup(q:string){const cnj=digits(q);if(cnj.length!==20)throw Object.assign(new Error('Para a API Pública do DataJud, informe o número CNJ completo com 20 dígitos.'),{status:400});const alias=datajudAlias(cnj);if(!alias)return{status:'provider_required',source:'CNJ / DataJud',result:{message:'O número foi reconhecido, mas o ramo/tribunal ainda não está mapeado neste conector.'}};const key='cDZHYzlZa0JadVREZDJCendQbXY6SkJlTzNjLV9TRENyQk1RdnFKZGRQdw==';const x=await apiJson('https://api-publica.datajud.cnj.jus.br/api_publica_'+alias+'/_search',{method:'POST',headers:{'Authorization':'APIKey '+key,'Content-Type':'application/json'},body:JSON.stringify({query:{match:{numeroProcesso:cnj}},size:20})});const hits=x?.hits?.hits||[];return{status:'completed',source:'CNJ / API Pública DataJud',result:{numero_processo:cnj,tribunal_alias:alias,total:x?.hits?.total?.value??hits.length,processos:hits.map((h:any)=>h?._source||h).slice(0,20),aviso:'Fonte oficial pública do CNJ. Processos sigilosos e dados protegidos não são expostos pela API pública.'}}}

async function sanctionsLookup(q:string){const input=detect(q),doc=digits(q),name=safe(q),key=String(Deno.env.get('PORTAL_TRANSPARENCIA_API_KEY')||'');if(!key)return{status:'provider_required',source:'CGU / Portal da Transparência',result:{message:'Conector oficial gratuito preparado. Falta cadastrar a chave gratuita da API do Portal da Transparência no cofre do Supabase.'}};const base='https://api.portaldatransparencia.gov.br/api-de-dados',headers={'Accept':'application/json','chave-api-dados':key};const get=async(path:string,param:string)=>{const value=['cpf','cnpj'].includes(input)?doc:name;try{return await apiJson(base+'/'+path+'?pagina=1&'+param+'='+encodeURIComponent(value),{headers})}catch(e:any){return{_error:e?.message||String(e)}}};const jobs:any[]=[['CEIS','ceis',['cpf','cnpj'].includes(input)?'codigoSancionado':'nomeSancionado'],['CNEP','cnep',['cpf','cnpj'].includes(input)?'codigoSancionado':'nomeSancionado']];if(input==='cnpj')jobs.push(['CEPIM','cepim','cnpjSancionado'],['Acordos de Leniência','acordos-leniencia','cnpjSancionado']);if(input==='cpf')jobs.push(['CEAF','ceaf','cpfSancionado']);const rows=await Promise.all(jobs.map(async([label,path,param])=>({cadastro:label,dados:await get(path,param)})));return{status:'completed',source:'CGU / API do Portal da Transparência',result:{consulta:q,cadastros:rows,total_registros:rows.reduce((n:any,r:any)=>n+(Array.isArray(r.dados)?r.dados.length:0),0),aviso:'Consulta oficial aos cadastros federais de sanções. Ausência de retorno não equivale a certidão negativa.'}}}

async function phoneLookup(q:string){let d=digits(q);if(d.startsWith('55')&&d.length>=12)d=d.slice(2);if(d.length<10||d.length>11)throw Object.assign(new Error('Informe um telefone brasileiro com DDD.'),{status:400});const ddd=d.slice(0,2),x=await apiJson(`https://brasilapi.com.br/api/ddd/v1/${ddd}`);return{status:'completed',source:'BrasilAPI / DDD',result:{telefone_informado:q,ddd,uf:x?.state||null,cidades:Array.isArray(x?.cities)?x.cities:[],aviso:'Consulta pública por DDD. Não identifica titular, CPF, endereço individual nem operadora da linha.'}}}
async function cnpjLookup(q:string,title:string){const cnpj=digits(q);if(cnpj.length!==14)throw Object.assign(new Error('Informe um CNPJ com 14 dígitos.'),{status:400});const d=await apiJson(`https://brasilapi.com.br/api/cnpj/v1/${cnpj}`);const base={cnpj:d.cnpj,razao_social:d.razao_social,nome_fantasia:d.nome_fantasia,situacao:d.descricao_situacao_cadastral,data_situacao:d.data_situacao_cadastral,motivo_situacao:d.descricao_motivo_situacao_cadastral||d.codigo_motivo_situacao_cadastral||null,data_abertura:d.data_inicio_atividade,matriz_filial:d.descricao_identificador_matriz_filial||d.identificador_matriz_filial,natureza_juridica:d.descricao_natureza_juridica||d.codigo_natureza_juridica,porte:d.porte,mei:d.opcao_pelo_mei,simples_nacional:d.opcao_pelo_simples,cnae_principal_codigo:d.cnae_fiscal,cnae_principal:d.cnae_fiscal_descricao,endereco:{logradouro:d.logradouro,numero:d.numero,complemento:d.complemento,bairro:d.bairro,municipio:d.municipio,uf:d.uf,cep:d.cep},telefones:[d.ddd_telefone_1,d.ddd_telefone_2].filter(Boolean),email:d.email,capital_social:d.capital_social,qsa:d.qsa||[],cnaes_secundarios:d.cnaes_secundarios||[]};if(title==='Grupo econômico')return{status:'completed',source:'BrasilAPI / Receita Federal',result:{empresa:base,vinculos_societarios:d.qsa||[],aviso:'Vínculos societários isoladamente não comprovam grupo econômico.'}};if(title==='Participações societárias')return{status:'completed',source:'BrasilAPI / Receita Federal',result:{empresa:{cnpj:base.cnpj,razao_social:base.razao_social,nome_fantasia:base.nome_fantasia},qsa:d.qsa||[]}};if(title==='Situação cadastral')return{status:'completed',source:'BrasilAPI / Receita Federal',result:base};return{status:'completed',source:'BrasilAPI / Receita Federal',result:base}}
async function cepLookup(q:string){const cep=digits(q);if(cep.length!==8)throw Object.assign(new Error('Informe um CEP com 8 dígitos.'),{status:400});const x=await apiJson(`https://brasilapi.com.br/api/cep/v2/${cep}`);return{status:'completed',source:'BrasilAPI / CEP',result:{cep:x?.cep||cep,estado:x?.state||null,cidade:x?.city||null,bairro:x?.neighborhood||null,logradouro:x?.street||null,servico:x?.service||null,localizacao:x?.location||null,aviso:'Consulta pública de CEP. Não identifica moradores, proprietários ou titulares do endereço.'}}}
async function bankLookup(q:string){const raw=q.trim(),all=await apiJson('https://brasilapi.com.br/api/banks/v1'),arr=Array.isArray(all)?all:[],low=raw.toLowerCase(),d=digits(raw),matches=arr.filter((b:any)=>String(b?.code??'')===d||String(b?.ispb??'')===d||String(b?.name??'').toLowerCase().includes(low)||String(b?.fullName??'').toLowerCase().includes(low)).slice(0,50);return{status:'completed',source:'BrasilAPI / Banco Central',result:{matches,count:matches.length,aviso:'Identifica instituições bancárias públicas. Não identifica titular de conta ou dados bancários individuais.'}}}
async function pixLookup(q:string){const raw=q.trim().toLowerCase(),d=digits(q),all=await apiJson('https://brasilapi.com.br/api/pix/v1/participants'),arr=Array.isArray(all)?all:[],matches=arr.filter((x:any)=>String(x?.ispb??'')===d||String(x?.nome??'').toLowerCase().includes(raw)||String(x?.nome_reduzido??'').toLowerCase().includes(raw)).slice(0,50);return{status:'completed',source:'BrasilAPI / PIX - Banco Central',result:{matches,count:matches.length,aviso:'Consulta instituições participantes do PIX. Não identifica titulares, chaves PIX ou contas individuais.'}}}
async function cvmLookup(q:string){const cnpj=digits(q);if(cnpj.length!==14)throw Object.assign(new Error('Informe o CNPJ da corretora com 14 dígitos.'),{status:400});return{status:'completed',source:'BrasilAPI / CVM',result:await apiJson(`https://brasilapi.com.br/api/cvm/corretoras/v1/${cnpj}`)}}
async function ncmLookup(q:string){const raw=q.trim(),compact=raw.replace(/[^0-9]/g,''),url=compact.length>=6?`https://brasilapi.com.br/api/ncm/v1/${compact}`:`https://brasilapi.com.br/api/ncm/v1?search=${encodeURIComponent(raw)}`,x=await apiJson(url);return{status:'completed',source:'BrasilAPI / NCM',result:{matches:Array.isArray(x)?x:[x],count:Array.isArray(x)?x.length:1}}}
async function registroBrLookup(q:string){let domain=q.trim().toLowerCase().replace(/^https?:\/\//,'').split('/')[0].replace(/^www\./,'');if(!domain.includes('.'))domain=`${domain}.com.br`;const x=await apiJson(`https://brasilapi.com.br/api/registrobr/v1/${encodeURIComponent(domain)}`);return{status:'completed',source:'BrasilAPI / Registro.br',result:{dominio:domain,...x,aviso:'Dados de domínio não comprovam identidade civil da pessoa responsável.'}}}

async function processLookup(db:any,org:string,q:string){const input=detect(q),d=digits(q),term=safe(q),rows:any[]=[],seen=new Set<string>();const add=(a:any[]|null)=>{for(const x of a||[])if(!seen.has(x.id)){seen.add(x.id);rows.push(x)}};const fields='id,cnj_number,internal_number,subject,class_name,status,court,vara,comarca,opposing_party,source,last_synced_at,clients(name,cpf_cnpj)';if(['cpf','cnpj','name'].includes(input)){let cq=db.from('clients').select('id').eq('org_id',org).limit(50);cq=input==='name'?cq.ilike('name',`%${term}%`):cq.ilike('cpf_cnpj',`%${d}%`);const c=await cq;if(c.error)throw c.error;const ids=(c.data||[]).map((x:any)=>x.id);if(ids.length){const p=await db.from('processes').select(fields).eq('org_id',org).in('client_id',ids).limit(50);if(p.error)throw p.error;add(p.data)}}if(term){const pt=input==='cnj'?d:term,p=await db.from('processes').select(fields).eq('org_id',org).or(`cnj_number.ilike.%${pt}%,internal_number.ilike.%${pt}%,subject.ilike.%${term}%,opposing_party.ilike.%${term}%`).limit(50);if(p.error)throw p.error;add(p.data)}return{status:'completed',source:'LEXOFFICE / processos sincronizados',result:{matches:rows,count:rows.length,input_type:input,observacao:'Resultado da base processual do escritório. Para pesquisa externa por documento, o motor DataJud é tentado primeiro.'}}}
async function internalLookup(db:any,org:string,def:Def,q:string){if(def.slug==='processes')return processLookup(db,org,q);const d=digits(q),term=safe(q);let x=db.from('clients').select('id,name,cpf_cnpj,rg,birth_date,profession,address,phone,whatsapp,email,status').eq('org_id',org).limit(50);x=d.length>=6?x.ilike('cpf_cnpj',`%${d}%`):x.ilike('name',`%${term}%`);const r=await x;if(r.error)throw r.error;const a=r.data||[];if(def.slug==='professional-data')return{status:'completed',source:'Cadastro interno do LEXOFFICE',result:{matches:a.map((v:any)=>({id:v.id,name:v.name,cpf_cnpj:v.cpf_cnpj,profession:v.profession,status:v.status})),count:a.length,aviso:'Esta parte do resultado vem apenas do cadastro interno.'}};if(def.slug==='person-location')return{status:'completed',source:'Cadastro interno do LEXOFFICE',result:{matches:a.map((v:any)=>({id:v.id,name:v.name,cpf_cnpj:v.cpf_cnpj,address:v.address,phone:v.phone,whatsapp:v.whatsapp,email:v.email})),count:a.length,aviso:'Esta parte do resultado vem apenas do cadastro interno.'}};return{status:'completed',source:'Cadastro interno do LEXOFFICE',result:{matches:a,count:a.length}}}

async function runOne(db:any,org:string,def:Def,q:string){const input=detectFor(def,q);if(def.slug==='processes'&&input==='cnj')return datajudLookup(q);if(!applies(def,input))return{status:'not_applicable',source:'Validação de entrada',result:{message:`O dado informado foi identificado como ${input} e não se aplica a esta consulta.`,input_type:input}};
 if(def.slug==='public-sanctions')return sanctionsLookup(q);
 if(def.provider_mode==='public_ddd'||def.slug==='phone-data')return phoneLookup(q);
 if(def.provider_mode==='public_cnpj')return cnpjLookup(q,def.title);
 if(def.provider_mode==='public_cep')return cepLookup(q);
 if(def.provider_mode==='public_bank')return bankLookup(q);
 if(def.provider_mode==='public_pix')return pixLookup(q);
 if(def.provider_mode==='public_cvm')return cvmLookup(q);
 if(def.provider_mode==='public_ncm')return ncmLookup(q);
 if(def.provider_mode==='public_registrobr')return registroBrLookup(q);
 if(def.slug==='employment-links')return{status:'provider_required',source:'MTE / PDET · Microdados RAIS e CAGED',result:{message:'Os microdados públicos do MTE são não identificados e podem alimentar análises estatísticas internas. Consulta individualizada de vínculo por CPF exige base identificada e autorização legal específica.',pagina_oficial:'Microdados RAIS e CAGED - Ministério do Trabalho e Emprego',input_type:input}};
 if(def.slug==='cpf-light')return{status:'provider_required',source:'Conecta gov.br / Receita Federal',result:{message:'A API CPF Light exige credencial e autorização do Conecta gov.br. O LEXOFFICE mantém este conector preparado para ativação quando houver acesso válido.',input_type:input}};
 if(def.slug==='municipal-property')return{status:'provider_required',source:'Portais municipais / conectores locais',result:{message:'A disponibilidade de consulta de IPTU e patrimônio varia por município. O LEXOFFICE deve usar apenas conectores públicos/oficiais permitidos para cada prefeitura.',input_type:input}};
 if(def.provider_mode==='internal')return internalLookup(db,org,def,q);
 return{status:'provider_required',source:'Provedor oficial/autorizado necessário',result:{message:`A consulta “${def.title}” ainda não possui uma fonte externa autorizada configurada no motor.`,input_type:input}}}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return J({error:'method_not_allowed'},405);try{
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,auth=req.headers.get('Authorization')||'';const uc=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user}}=await uc.auth.getUser();if(!user)return J({error:'Sessão inválida.'},401);const db=createClient(url,service,{auth:{persistSession:false}}),pr=await db.from('profiles').select('org_id').eq('id',user.id).maybeSingle();if(pr.error)throw pr.error;if(!pr.data?.org_id)return J({error:'Organização não encontrada.'},403);const org=pr.data.org_id,body=await req.json().catch(()=>({})),action=String(body.action||'single'),cat=await db.from('investigation_catalog').select('slug,title,description,category,input_kind,provider_mode,novelty,sort_order').eq('enabled',true).order('sort_order');if(cat.error)throw cat.error;if(action==='catalog')return J({ok:true,catalog:cat.data||[]});const q=String(body.query||'').trim();if(!q)return J({error:'Informe o dado que deseja consultar.'},400);const defs=(cat.data||[]) as Def[];
 if(action==='batch'){const batchStarted=nowMs(),input=detect(q);const reqs=Array.isArray(body.slugs)&&body.slugs.length?body.slugs.map(String):defs.map(x=>x.slug),requested=defs.filter(x=>reqs.includes(x.slug)),sel=requested.filter(x=>applies(x,input));if(!sel.length)return J({error:`Nenhuma fonte aplicável ao dado identificado como ${input}.`},400);const b=await db.from('investigation_batches').insert({org_id:org,user_id:user.id,query_text:q,status:'processing',total_items:sel.length}).select('id').single();if(b.error)throw b.error;const out:any[]=[];let completed=0,failed=0,provider_required=0,not_applicable=0;for(const def of sel){const itemStarted=nowMs();try{const r=await runOne(db,org,def,q);const duration_ms=nowMs()-itemStarted;await db.from('investigation_searches').insert({org_id:org,user_id:user.id,search_type:def.title,search_slug:def.slug,query_text:q,status:r.status,source:r.source,result:r.result,batch_id:b.data.id,duration_ms});await db.from('investigation_batch_items').insert({batch_id:b.data.id,org_id:org,search_type:def.title,search_slug:def.slug,status:r.status,source:r.source,result:r.result,duration_ms});out.push({slug:def.slug,title:def.title,...r,duration_ms});if(r.status==='completed')completed++;else if(r.status==='provider_required')provider_required++;else not_applicable++}catch(e:any){failed++;const msg=e instanceof Error?e.message:String(e);await db.from('investigation_batch_items').insert({batch_id:b.data.id,org_id:org,search_type:def.title,search_slug:def.slug,status:'failed',source:'Erro',result:{},error_message:msg,duration_ms:nowMs()-itemStarted});out.push({slug:def.slug,title:def.title,status:'failed',source:'Erro',error:msg,duration_ms:nowMs()-itemStarted})}}const status=failed?'partial':'completed';await db.from('investigation_batches').update({status,completed_items:completed+provider_required+not_applicable,completed_at:new Date().toISOString(),duration_ms:nowMs()-batchStarted}).eq('id',b.data.id);return J({ok:true,batch_id:b.data.id,status,input_type:input,duration_ms:nowMs()-batchStarted,summary:{applicable:sel.length,completed,provider_required,not_applicable,failed,excluded:requested.length-sel.length},results:out,checked_at:new Date().toISOString()})}
 const slug=String(body.slug||''),def=defs.find(x=>x.slug===slug);if(!def)return J({error:'Categoria de investigação inválida.'},400);const started=nowMs();const r=await runOne(db,org,def,q);const duration_ms=nowMs()-started;const ins=await db.from('investigation_searches').insert({org_id:org,user_id:user.id,search_type:def.title,search_slug:def.slug,query_text:q,status:r.status,source:r.source,result:r.result,duration_ms}).select('id').single();return J({ok:true,slug:def.slug,title:def.title,...r,duration_ms,search_id:ins.data?.id||null,checked_at:new Date().toISOString()});
 }catch(e:any){console.error('investigation-search',e);return J({error:e instanceof Error?e.message:String(e)},e?.status||500)}});
