import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const J=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}});
const clean=(v:any)=>String(v??'').trim();
const digits=(v:any)=>clean(v).replace(/\D/g,'');
const ALLOWED='https://api.escavador.com/api/v2/advogado/processos';
function safeNext(v:any){if(!v)return null;try{const u=new URL(String(v));if(u.origin!=='https://api.escavador.com'||u.pathname!=='/api/v2/advogado/processos')return null;return u.toString()}catch{return null}}
function firstSource(it:any){return Array.isArray(it?.fontes)&&it.fontes.length?it.fontes[0]:null}
function courtFromCnj(cnj:string){if(cnj.length!==20)return null;const j=cnj.slice(13,14),tr=cnj.slice(14,16),n=Number(tr);const st:Record<string,string>={'01':'AC','02':'AL','03':'AP','04':'AM','05':'BA','06':'CE','07':'DFT','08':'ES','09':'GO','10':'MA','11':'MT','12':'MS','13':'MG','14':'PA','15':'PB','16':'PR','17':'PE','18':'PI','19':'RJ','20':'RN','21':'RS','22':'RO','23':'RR','24':'SC','25':'SE','26':'SP','27':'TO'};if(j==='8'&&st[tr])return `TJ${st[tr]}`;if(j==='4'&&n>=1&&n<=6)return `TRF${n}`;if(j==='5')return tr==='00'?'TST':n>=1&&n<=24?`TRT${n}`:null;if(j==='6')return tr==='00'?'TSE':st[tr]?`TRE${st[tr]}`:null;if(j==='7'&&tr==='00')return'STM';if(j==='9'&&['13','21','26'].includes(tr))return tr==='13'?'TJMMG':tr==='21'?'TJMRS':'TJMSP';if(j==='1')return'STF';if(j==='3')return'STJ';return null}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return J({error:'Método não permitido.'},405);try{const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,auth=req.headers.get('Authorization')||'',uc=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user}}=await uc.auth.getUser();if(!user)return J({error:'Sessão inválida. Faça login novamente.'},401);const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const [{data:profile},{data:pa},{data:sec}]=await Promise.all([db.from('profiles').select('org_id').eq('id',user.id).maybeSingle(),db.from('platform_admins').select('user_id').eq('user_id',user.id).eq('status','active').maybeSingle(),db.from('system_runtime_secrets').select('secret').eq('key','escavador_pat').maybeSingle()]);if(!profile?.org_id)return J({error:'Organização não encontrada.'},403);const orgId=profile.org_id,body=await req.json().catch(()=>({})),action=clean(body.action||'status');const token=clean(sec?.secret);
if(action==='status')return J({ok:true,configured:Boolean(token),can_configure:Boolean(pa)});
if(action==='configure'){if(!pa)return J({error:'Somente o administrador da plataforma pode configurar o provedor Escavador.'},403);const pat=clean(body.token);if(pat.length<20)return J({error:'PAT do Escavador inválido ou muito curto.'},400);const {error}=await db.from('system_runtime_secrets').upsert({key:'escavador_pat',secret:pat,updated_at:new Date().toISOString()},{onConflict:'key'});if(error)throw error;return J({ok:true,configured:true,message:'Escavador configurado no cofre da plataforma.'})}
if(action!=='discover')return J({error:'Ação inválida.'},400);if(!token)return J({error:'Integração Escavador ainda não configurada.',configured:false},503);
const oab=digits(body.oab_number),uf=clean(body.oab_uf).toUpperCase();if(!oab||uf.length!==2)return J({error:'Informe número da OAB e UF.'},400);let next=safeNext(body.continue_url);if(!next){const u=new URL(ALLOWED);u.searchParams.set('oab_estado',uf);u.searchParams.set('oab_numero',oab);u.searchParams.set('oab_tipo','ADVOGADO');u.searchParams.set('limit','100');if(clean(body.status))u.searchParams.set('status',clean(body.status).toUpperCase());next=u.toString()}
const {data:existingRows}=await db.from('processes').select('id,cnj_number').eq('org_id',orgId).eq('owner_user_id',user.id).not('cnj_number','is',null).limit(10000);const existing=new Map((existingRows||[]).map((r:any)=>[digits(r.cnj_number),r.id]));let pages=0,found=0,imported=0,duplicates=0,invalid=0,lastNext:string|null=next,advogado:any=null;while(lastNext&&pages<5){const r=await fetch(lastNext,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json'}}),raw=await r.text();if(!r.ok)return J({error:`Escavador HTTP ${r.status}: ${raw.slice(0,240)}`},502);const data=JSON.parse(raw);pages++;advogado=advogado||data?.advogado_encontrado||null;const items=Array.isArray(data?.items)?data.items:[];found+=items.length;for(const it of items){const rawCnj=clean(it?.numero_cnj),cnj=digits(rawCnj);if(cnj.length!==20){invalid++;continue}if(existing.has(cnj)){duplicates++;continue}const src=firstSource(it),capa=src?.capa||{},tc=clean(it?.unidade_origem?.tribunal_sigla||src?.sigla||courtFromCnj(cnj)).toUpperCase()||courtFromCnj(cnj);const ins=await db.from('processes').insert({org_id:orgId,owner_user_id:user.id,responsible_id:user.id,cnj_number:rawCnj||cnj,opposing_party:clean(it?.titulo_polo_passivo)||null,court:clean(it?.unidade_origem?.nome||capa?.orgao_julgador)||null,comarca:clean(it?.unidade_origem?.cidade)||null,area:clean(capa?.area)||null,subject:clean(capa?.assunto)||null,class_name:clean(capa?.classe)||null,tribunal_code:tc,tribunal_name:tc,judicial_system:clean(src?.sistema)||'DataJud',status:'active',priority:'normal',source:'escavador:oab',sync_status:'not_synced',external_process_id:it?.id?String(it.id):null}).select('id').single();if(ins.error)invalid++;else{existing.set(cnj,ins.data.id);imported++}}lastNext=safeNext(data?.links?.next)}
const {data:mon}=await db.from('djen_monitors').select('id').eq('org_id',orgId).eq('owner_user_id',user.id).eq('oab_number',oab).eq('oab_uf',uf).maybeSingle();if(!mon)await db.from('djen_monitors').insert({org_id:orgId,owner_user_id:user.id,oab_number:oab,oab_uf:uf,enabled:true});else await db.from('djen_monitors').update({enabled:true,updated_at:new Date().toISOString()}).eq('id',mon.id);
try{await fetch(`${url}/functions/v1/tribunal-sync`,{method:'POST',headers:{Authorization:auth,'Content-Type':'application/json'},body:'{}'})}catch{}
return J({ok:true,advogado,pages,found,imported,duplicates,invalid,partial:Boolean(lastNext),continue_url:lastNext,message:`Descoberta concluída: ${imported} novo(s), ${duplicates} já existente(s), ${invalid} ignorado(s).`})}catch(e){console.error(e);return J({error:e instanceof Error?e.message:String(e)},500)}});