import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.57.4";

const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
const digits=(v:any)=>String(v??'').replace(/\D/g,'');
function admin(){return createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}})}
function cfg(){const base=(Deno.env.get('WAHA_API_URL')||'http://209.50.245.8:3000').replace(/\/$/,'');const key=(Deno.env.get('WAHA_API_KEY')||'').trim();const session=(Deno.env.get('WAHA_SESSION')||'lexoffice').trim();if(!key)throw new Error('WAHA_API_KEY ausente');return{base,key,session}}
async function waha(path:string,init:RequestInit={}){const c=cfg();const r=await fetch(c.base+path,{...init,headers:{'X-Api-Key':c.key,'Accept':'application/json',...(init.body?{'Content-Type':'application/json'}:{}),...(init.headers||{})}});const raw=await r.text();let d:any={};try{d=raw?JSON.parse(raw):{}}catch{d={raw}}if(!r.ok)throw new Error(d?.message||d?.error||raw||`WAHA ${r.status}`);return d}
async function resolveChatId(target:string){const c=cfg();if(target.includes('@'))return target;const p=digits(target);if(!p)throw new Error('Destino inválido');try{const q=await waha(`/api/contacts/check-exists?phone=${encodeURIComponent(p)}&session=${encodeURIComponent(c.session)}`,{method:'GET'});if(q?.numberExists&&q?.chatId)return String(q.chatId);if(q?.numberExists===false)throw new Error('Número não encontrado no WhatsApp')}catch(e){if(e instanceof Error&&e.message==='Número não encontrado no WhatsApp')throw e}return `${p}@c.us`}
function sanitize(text:string){return text.replace(/^\s*(suporte|support)\s*:\s*/i,'').trim()}
function unsafe(text:string){return /(bot_ativo|human_takeover|ai_enabled|resume_at|system prompt|prompt interno|racioc[ií]nio interno|verifica[cç][aã]o de estado|transbordo humano|registro de poss[ií]vel)/i.test(text)}
async function blockedByHuman(a:any,orgId:string,conversationId:string|null,target:string){let cv:any=null;if(conversationId){const q=await a.from('whatsapp_conversations').select('id,bot_ativo,conversation_owner,human_takeover_at').eq('org_id',orgId).eq('id',conversationId).maybeSingle();cv=q.data}else{const p=digits(target.split('@')[0]);if(p){const {data:ct}=await a.from('whatsapp_contacts').select('id').eq('org_id',orgId).eq('phone',p).limit(1).maybeSingle();if(ct){const q=await a.from('whatsapp_conversations').select('id,bot_ativo,conversation_owner,human_takeover_at').eq('org_id',orgId).eq('contact_id',ct.id).neq('status','closed').order('updated_at',{ascending:false}).limit(1).maybeSingle();cv=q.data}}}if(cv&&(cv.bot_ativo===false||cv.conversation_owner==='HUMAN'||cv.human_takeover_at))return true;const p=digits(target.split('@')[0]);if(p){const {data:ctl}=await a.from('ai_conversation_controls').select('ai_enabled,human_takeover').eq('org_id',orgId).eq('contact_key',p).maybeSingle();if(ctl&&(ctl.ai_enabled===false||ctl.human_takeover===true))return true}return false}
async function log(a:any,row:any){try{await a.from('whatsapp_outbound_gate_log').insert(row)}catch{}}

Deno.serve(async(req)=>{if(req.method!=='POST')return json({ok:false,error:'Método inválido'},405);try{const service=(Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'').trim(),auth=(req.headers.get('authorization')||'').trim();if(!service||auth!==`Bearer ${service}`)return json({ok:false,error:'Não autorizado'},401);const b=await req.json().catch(()=>({}));const orgId=String(b.org_id||'').trim(),conversationId=b.conversation_id?String(b.conversation_id):null,target=String(b.chat_id||b.phone||b.to||'').trim(),agentKey=String(b.agent_key||'system').trim(),key=String(b.idempotency_key||'').trim()||null;const message=sanitize(String(b.message||'').trim());if(!orgId||!target||!message)return json({ok:false,error:'org_id, destino e mensagem são obrigatórios'},400);const a=admin();if(key){const {data:existing}=await a.from('whatsapp_outbound_gate_log').select('id,allowed,reason').eq('org_id',orgId).eq('idempotency_key',key).maybeSingle();if(existing)return json({ok:true,duplicate:true,allowed:existing.allowed,reason:existing.reason})}if(unsafe(message)){await log(a,{org_id:orgId,conversation_id:conversationId,agent_key:agentKey,allowed:false,reason:'unsafe_internal_content',body_preview:message.slice(0,240),idempotency_key:key});return json({ok:true,allowed:false,reason:'unsafe_internal_content'})}if(await blockedByHuman(a,orgId,conversationId,target)){await log(a,{org_id:orgId,conversation_id:conversationId,agent_key:agentKey,allowed:false,reason:'human_takeover',body_preview:message.slice(0,240),idempotency_key:key});return json({ok:true,allowed:false,reason:'human_takeover'})}const chatId=await resolveChatId(target),c=cfg();const provider=await waha('/api/sendText',{method:'POST',body:JSON.stringify({session:c.session,chatId,text:message})});await log(a,{org_id:orgId,conversation_id:conversationId,agent_key:agentKey,allowed:true,reason:'sent',body_preview:message.slice(0,240),idempotency_key:key});return json({ok:true,allowed:true,chat_id:chatId,provider_response:provider})}catch(e){console.error('whatsapp-outbound-gate',e);return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
