import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.57.4";
import {formatWhatsAppAgentReply,previewForLog} from '../_shared/whatsapp-reply-format.mjs';

const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
const digits=(v:any)=>String(v??'').replace(/\D/g,'');
const AGENT_KEYS=new Set(['client_service_triage','client_process_updates','client_schedule_relationship','sales','billing']);
function admin(){return createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}})}
function cfg(){const base=(Deno.env.get('WAHA_API_URL')||'http://209.50.245.8:3000').replace(/\/$/,'');const key=(Deno.env.get('WAHA_API_KEY')||'').trim();const session=(Deno.env.get('WAHA_SESSION')||'lexoffice').trim();if(!key)throw new Error('WAHA_API_KEY ausente');return{base,key,session}}
async function waha(path:string,init:RequestInit={}){const c=cfg();const r=await fetch(c.base+path,{...init,headers:{'X-Api-Key':c.key,'Accept':'application/json',...(init.body?{'Content-Type':'application/json'}:{}),...(init.headers||{})}});const raw=await r.text();let d:any={};try{d=raw?JSON.parse(raw):{}}catch{d={raw}}if(!r.ok)throw new Error(d?.message||d?.error||raw||`WAHA ${r.status}`);return d}
async function resolveChatId(target:string){const c=cfg();if(target.includes('@'))return target;const p=digits(target);if(!p)throw new Error('Destino inválido');let q:any;try{q=await waha(`/api/contacts/check-exists?phone=${encodeURIComponent(p)}&session=${encodeURIComponent(c.session)}`,{method:'GET'})}catch(e){console.error('whatsapp-contact-validation',e);throw new Error('Não foi possível validar o destinatário no WhatsApp. O envio foi bloqueado por segurança.')}if(q?.numberExists&&q?.chatId)return String(q.chatId);if(q?.numberExists===false)throw new Error('Número não encontrado no WhatsApp.');throw new Error('O provedor não confirmou o identificador do destinatário. O envio foi bloqueado por segurança.')}
function sanitize(text:string){return text.replace(/^\s*(suporte|support)\s*:\s*/i,'').replace(/\r\n?/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
function unsafe(text:string){return /(bot_ativo|human_takeover|ai_enabled|resume_at|system prompt|prompt interno|racioc[ií]nio interno|verifica[cç][aã]o de estado|transbordo humano|registro de poss[ií]vel)/i.test(text)}
async function conversationState(a:any,orgId:string,conversationId:string|null,target:string){let cv:any=null;if(conversationId){const q=await a.from('whatsapp_conversations').select('id,bot_ativo,conversation_owner,human_takeover_at').eq('org_id',orgId).eq('id',conversationId).maybeSingle();cv=q.data}else{const p=digits(target.split('@')[0]);if(p){const {data:ct}=await a.from('whatsapp_contacts').select('id').eq('org_id',orgId).eq('phone',p).limit(1).maybeSingle();if(ct){const q=await a.from('whatsapp_conversations').select('id,bot_ativo,conversation_owner,human_takeover_at').eq('org_id',orgId).eq('contact_id',ct.id).neq('status','closed').order('updated_at',{ascending:false}).limit(1).maybeSingle();cv=q.data}}}const p=digits(target.split('@')[0]);let ctl:any=null;if(p){const q=await a.from('ai_conversation_controls').select('ai_enabled,human_takeover').eq('org_id',orgId).eq('contact_key',p).maybeSingle();ctl=q.data}return{cv,ctl,bot_ativo:cv?.bot_ativo??null,human_takeover:Boolean(cv?.conversation_owner==='HUMAN'||cv?.human_takeover_at||ctl?.human_takeover===true||ctl?.ai_enabled===false)}}
async function blockedByHuman(a:any,orgId:string,conversationId:string|null,target:string){const state=await conversationState(a,orgId,conversationId,target);return{blocked:state.human_takeover||state.bot_ativo===false,state}}
async function log(a:any,row:any){try{await a.from('whatsapp_outbound_gate_log').insert(row)}catch{}}
async function trace(a:any,orgId:string,conversationId:string|null,agentKey:string,decision:string,metadata:any){if(!conversationId)return;try{await a.from('ai_orchestrator_events').insert({org_id:orgId,conversation_id:conversationId,event_type:'whatsapp_reply_pipeline',agent_key:agentKey,decision,reason:metadata?.reason||null,metadata})}catch(e){console.error('whatsapp-reply-trace',e)}}

Deno.serve(async(req)=>{if(req.method!=='POST')return json({ok:false,error:'Método inválido'},405);try{const service=(Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'').trim(),auth=(req.headers.get('authorization')||'').trim();if(!service||auth!==`Bearer ${service}`)return json({ok:false,error:'Não autorizado'},401);const b=await req.json().catch(()=>({}));const orgId=String(b.org_id||'').trim(),conversationId=b.conversation_id?String(b.conversation_id):null,target=String(b.chat_id||b.phone||b.to||'').trim(),agentKey=String(b.agent_key||'system').trim(),key=String(b.idempotency_key||'').trim()||null;const rawMessage=String(b.message||'').trim();if(!orgId||!target||!rawMessage)return json({ok:false,error:'org_id, destino e mensagem são obrigatórios'},400);const a=admin();if(key){const {data:existing}=await a.from('whatsapp_outbound_gate_log').select('id,allowed,reason').eq('org_id',orgId).eq('idempotency_key',key).maybeSingle();if(existing)return json({ok:true,duplicate:true,allowed:existing.allowed,reason:existing.reason})}
const automated=AGENT_KEYS.has(agentKey)||b.format_agent_reply===true;const formatted=automated?formatWhatsAppAgentReply(rawMessage):{rawAgentOutput:rawMessage,parsedReply:sanitize(rawMessage),formattedReply:sanitize(rawMessage)};const message=formatted.formattedReply;if(!message)return json({ok:false,error:'Mensagem vazia após formatação'},400);if(unsafe(formatted.parsedReply)){await log(a,{org_id:orgId,conversation_id:conversationId,agent_key:agentKey,allowed:false,reason:'unsafe_internal_content',body_preview:previewForLog(formatted.parsedReply,240),idempotency_key:key});await trace(a,orgId,conversationId,agentKey,'blocked',{reason:'unsafe_internal_content',raw_agent_output:previewForLog(formatted.rawAgentOutput),parsed_reply:previewForLog(formatted.parsedReply),formatted_reply:previewForLog(message),final_whatsapp_payload:null,agent_id:agentKey,conversation_id:conversationId,human_takeover:null,bot_ativo:null});return json({ok:true,allowed:false,reason:'unsafe_internal_content'})}
const hb=await blockedByHuman(a,orgId,conversationId,target);if(hb.blocked){await log(a,{org_id:orgId,conversation_id:conversationId,agent_key:agentKey,allowed:false,reason:'human_takeover',body_preview:previewForLog(message,240),idempotency_key:key});await trace(a,orgId,conversationId,agentKey,'blocked',{reason:'human_takeover',raw_agent_output:previewForLog(formatted.rawAgentOutput),parsed_reply:previewForLog(formatted.parsedReply),formatted_reply:previewForLog(message),final_whatsapp_payload:null,agent_id:agentKey,conversation_id:conversationId,human_takeover:true,bot_ativo:hb.state.bot_ativo});return json({ok:true,allowed:false,reason:'human_takeover'})}
const chatId=await resolveChatId(target),c=cfg();await trace(a,orgId,conversationId,agentKey,'ready_to_send',{raw_agent_output:previewForLog(formatted.rawAgentOutput),parsed_reply:previewForLog(formatted.parsedReply),formatted_reply:previewForLog(message),final_whatsapp_payload:previewForLog(message),agent_id:agentKey,conversation_id:conversationId,human_takeover:false,bot_ativo:hb.state.bot_ativo});const provider=await waha('/api/sendText',{method:'POST',body:JSON.stringify({session:c.session,chatId,text:message})});await log(a,{org_id:orgId,conversation_id:conversationId,agent_key:agentKey,allowed:true,reason:'sent',body_preview:previewForLog(message,240),idempotency_key:key});return json({ok:true,allowed:true,chat_id:chatId,provider_response:provider,parsed_reply:formatted.parsedReply,formatted_reply:message})}catch(e){console.error('whatsapp-outbound-gate',e);return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
