import { useEffect,useState } from 'react';
import { CalendarDays,RefreshCw,Link2,Clock,MapPin } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './integrations.css';

type EventRow={id:string;title:string;description?:string|null;starts_at:string;ends_at?:string|null;location?:string|null;status?:string|null;event_type?:string|null};
export default function Agenda(){const [events,setEvents]=useState<EventRow[]>([]),[connection,setConnection]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
async function load(){if(!supabase)return;setLoading(true);const [{data:e,error:ee},{data:c}]=await Promise.all([supabase.from('calendar_events').select('id,title,description,starts_at,ends_at,location,status,event_type').gte('starts_at',new Date(Date.now()-86400000).toISOString()).order('starts_at',{ascending:true}).limit(100),supabase.from('integration_connections').select('id,provider,status,last_sync_at,last_error').eq('provider','google_calendar').maybeSingle()]);if(ee)setNotice(ee.message);else setEvents((e||[]) as EventRow[]);setConnection(c);setLoading(false)}
useEffect(()=>{load()},[]);
async function connect(){if(!supabase)return;setBusy(true);setNotice('');const {data,error}=await supabase.functions.invoke('google-calendar-oauth-start',{body:{}});setBusy(false);if(error){setNotice(error.message);return}if((data as any)?.error){setNotice((data as any).error);return}if((data as any)?.url)window.location.href=(data as any).url;else setNotice('O Google não retornou a URL de autorização.')}
async function sync(){if(!supabase)return;setBusy(true);setNotice('');const {data,error}=await supabase.functions.invoke('google-calendar-sync',{body:{}});if(error)setNotice(error.message);else if((data as any)?.error)setNotice((data as any).error);else{const d:any=data;setNotice(`Sincronização concluída: ${d.pushed_to_google||0} enviados, ${d.updated_on_google||0} atualizados e ${d.imported_from_google||0} importados.`);await load()}setBusy(false)}
return <><div className="page-title"><h1>Agenda</h1><p>Compromissos do escritório e sincronização com Google Agenda</p></div><div className="integration-head"><div><span className="integration-pill"><CalendarDays size={14}/> GOOGLE AGENDA</span><h2>Agenda jurídica integrada</h2><p>Audiências, compromissos e eventos do LEXOFFICE em uma agenda sincronizada.</p></div><div className="signature-actions"><button className="integration-action" onClick={connect} disabled={busy}><Link2 size={16}/>{connection?.status==='connected'?'Reconectar Google':'Conectar Google'}</button><button className="integration-action" onClick={sync} disabled={busy||connection?.status!=='connected'}><RefreshCw size={16}/>Sincronizar</button></div></div>{connection&&<div className="integration-notice">Google Agenda: <b>{connection.status||'não conectado'}</b>{connection.last_sync_at?` • última sincronização ${new Date(connection.last_sync_at).toLocaleString('pt-BR')}`:''}{connection.last_error?` • ${connection.last_error}`:''}</div>}{notice&&<div className="integration-notice">{notice}</div>}<div className="integration-panel">{loading?<p>Carregando agenda...</p>:events.length===0?<div className="integration-empty"><CalendarDays size={30}/><h3>Nenhum compromisso futuro</h3><p>Eventos do LEXOFFICE e do Google aparecerão aqui após a sincronização.</p></div>:<div className="signature-list">{events.map(e=><div className="signature-row" key={e.id}><div><strong>{e.title}</strong><small><Clock size={12}/> {new Date(e.starts_at).toLocaleString('pt-BR')}{e.location?<> • <MapPin size={12}/> {e.location}</>:null}</small></div><span className="status-dot">{e.status||e.event_type||'agendado'}</span></div>)}</div>}</div></>}
