import { useEffect,useMemo,useState } from 'react';
import { Calculator,Play,ShieldCheck,Printer,Save,UserRound,Scale } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './integrations.css';

type Field={key:string;label:string;type?:'number'|'date'|'select';options?:{value:string;label:string}[]};
type Client={id:string;name:string};
type Process={id:string;client_id?:string|null;cnj_number?:string|null;internal_number?:string|null;subject?:string|null};
const opt=(...items:string[])=>items.map(v=>({value:v,label:v}));
const calculators=['Atualização monetária e juros','Revisional Bancária','Financiamento e empréstimos','Superendividamento','RMC / RCC INSS','Revisão PASEP','Benefícios Previdenciários','Contribuições acima do teto do INSS','Aluguel e reajuste locatício','Dosimetria da Pena','Progressão de Regime','Detração Penal','Liquidação Trabalhista','Horas Extras','Verbas Rescisórias','FGTS','Pensão Alimentícia','Divórcio e Partilha','Inventário e Quinhões','Danos Materiais','Custas e Honorários','Prazo Processual'];
const fields:Record<string,Field[]>={
'Atualização monetária e juros':[{key:'principal',label:'Principal',type:'number'},{key:'correctionPercent',label:'Correção (%)',type:'number'},{key:'penalty',label:'Multa (%)',type:'number'},{key:'rate',label:'Juros ao mês (%)',type:'number'},{key:'startDate',label:'Data inicial',type:'date'},{key:'endDate',label:'Data final',type:'date'}],
'Revisional Bancária':[{key:'contractValue',label:'Valor contratado',type:'number'},{key:'releasedValue',label:'Valor efetivamente liberado',type:'number'},{key:'installments',label:'Quantidade de parcelas',type:'number'},{key:'installmentValue',label:'Valor da parcela',type:'number'},{key:'paidInstallments',label:'Parcelas pagas',type:'number'},{key:'contractRate',label:'Taxa contratada (% a.m.)',type:'number'},{key:'referenceRate',label:'Taxa de referência (% a.m.)',type:'number'}],
'Financiamento e empréstimos':[{key:'principal',label:'Valor principal',type:'number'},{key:'entryAmount',label:'Entrada',type:'number'},{key:'installmentCount',label:'Nº de parcelas',type:'number'},{key:'rate',label:'Taxa mensal (%)',type:'number'},{key:'system',label:'Sistema',type:'select',options:[{value:'price',label:'Price'},{value:'sac',label:'SAC'},{value:'simple',label:'Sem juros'}]}],
'Superendividamento':[{key:'income',label:'Renda líquida',type:'number'},{key:'essentialExpenses',label:'Despesas essenciais',type:'number'},{key:'monthlyDebt',label:'Dívidas mensais',type:'number'},{key:'totalDebt',label:'Dívida total',type:'number'},{key:'minimumExistence',label:'Mínimo existencial',type:'number'}],
'RMC / RCC INSS':[{key:'amountReceived',label:'Valor recebido',type:'number'},{key:'monthlyDiscount',label:'Desconto mensal',type:'number'},{key:'monthsDiscounted',label:'Meses descontados',type:'number'},{key:'totalPaid',label:'Total descontado (opcional)',type:'number'}],
'Revisão PASEP':[{key:'initialBalance',label:'Saldo inicial',type:'number'},{key:'withdrawals',label:'Saques realizados',type:'number'},{key:'finalBalance',label:'Saldo final informado',type:'number'},{key:'correctionPercent',label:'Correção acumulada informada (%)',type:'number'}],
'Benefícios Previdenciários':[{key:'retirementMode',label:'Modalidade',type:'select',options:[{value:'programada',label:'Programada'},{value:'pontos',label:'Regra de pontos'},{value:'idade_progressiva',label:'Idade progressiva'},{value:'pedagio_50',label:'Pedágio 50%'},{value:'pedagio_100',label:'Pedágio 100%'},{value:'professor_pontos',label:'Professor - pontos'},{value:'professor_idade',label:'Professor - idade'},{value:'professor_pedagio_100',label:'Professor - pedágio 100%'},{value:'rural',label:'Rural'},{value:'pcd_idade',label:'PCD por idade'},{value:'pcd_tempo',label:'PCD por tempo'},{value:'especial_nova',label:'Especial - regra nova'},{value:'especial_transicao',label:'Especial - transição'},{value:'incapacidade',label:'Incapacidade permanente'}]},{key:'sex',label:'Sexo',type:'select',options:[{value:'female',label:'Feminino'},{value:'male',label:'Masculino'}]},{key:'birthDate',label:'Data de nascimento',type:'date'},{key:'der',label:'DER / data da análise',type:'date'},{key:'contributionYears',label:'Tempo total de contribuição (anos)',type:'number'},{key:'contributionAtReform',label:'Tempo em 13/11/2019 (anos)',type:'number'},{key:'carencyMonths',label:'Carência (meses)',type:'number'},{key:'averageSalary',label:'Média salarial',type:'number'},{key:'teacherYears',label:'Tempo de magistério (anos)',type:'number'},{key:'ruralMonths',label:'Atividade rural (meses)',type:'number'},{key:'pcdYears',label:'Tempo como PCD (anos)',type:'number'},{key:'disabilityDegree',label:'Grau de deficiência',type:'select',options:opt('leve','moderada','grave')},{key:'specialYears',label:'Tempo especial (anos)',type:'number'},{key:'specialExposure',label:'Meta especial (15/20/25 anos)',type:'number'}],
'Contribuições acima do teto do INSS':[{key:'totalContributions',label:'Total recolhido',type:'number'},{key:'ceilingContributions',label:'Total limitado ao teto',type:'number'}],
'Aluguel e reajuste locatício':[{key:'rent',label:'Aluguel atual',type:'number'},{key:'indexPercentage',label:'Índice de reajuste (%)',type:'number'},{key:'months',label:'Meses',type:'number'}],
'Dosimetria da Pena':[{key:'minimumPenaltyMonths',label:'Pena mínima (meses)',type:'number'},{key:'maximumPenaltyMonths',label:'Pena máxima (meses)',type:'number'},{key:'unfavorableCount',label:'Circunstâncias desfavoráveis',type:'number'},{key:'phase1PercentEach',label:'Acréscimo por circunstância (%)',type:'number'},{key:'aggravatingPercent',label:'Agravantes (%)',type:'number'},{key:'mitigatingPercent',label:'Atenuantes (%)',type:'number'},{key:'increasePercent',label:'Causa de aumento (%)',type:'number'},{key:'decreasePercent',label:'Causa de diminuição (%)',type:'number'},{key:'detractionDays',label:'Detração (dias)',type:'number'},{key:'fineDays',label:'Dias-multa',type:'number'},{key:'fineDayValue',label:'Valor do dia-multa',type:'number'}],
'Progressão de Regime':[{key:'sentenceMonths',label:'Pena (meses)',type:'number'},{key:'fraction',label:'Fração exigida (%)',type:'number'},{key:'detraction',label:'Detração (dias)',type:'number'},{key:'remission',label:'Remição (dias)',type:'number'},{key:'servedDays',label:'Dias já cumpridos',type:'number'}],
'Detração Penal':[{key:'custodyStart',label:'Início da custódia',type:'date'},{key:'custodyEnd',label:'Fim da custódia',type:'date'},{key:'otherDays',label:'Outros dias',type:'number'},{key:'sentenceMonths',label:'Pena (meses)',type:'number'}],
'Liquidação Trabalhista':[{key:'salary',label:'Salário-base',type:'number'},{key:'monthlyHours',label:'Divisor mensal',type:'number'},{key:'overtime',label:'Horas extras',type:'number'},{key:'overtimeAdditional',label:'Adicional de hora extra (%)',type:'number'},{key:'additional',label:'Outras parcelas',type:'number'},{key:'deductions',label:'Deduções',type:'number'}],
'Horas Extras':[{key:'salary',label:'Salário',type:'number'},{key:'monthlyHours',label:'Divisor mensal',type:'number'},{key:'extraHours',label:'Horas extras/mês',type:'number'},{key:'additionalPercentage',label:'Adicional (%)',type:'number'},{key:'periodMonths',label:'Meses do período',type:'number'}],
'Verbas Rescisórias':[{key:'salary',label:'Salário',type:'number'},{key:'daysWorked',label:'Dias trabalhados no mês',type:'number'},{key:'thirteenthMonths',label:'Avos de 13º',type:'number'},{key:'vacationMonths',label:'Avos de férias',type:'number'},{key:'overdueVacations',label:'Férias vencidas',type:'number'},{key:'noticeDays',label:'Dias de aviso',type:'number'}],
'FGTS':[{key:'remuneration',label:'Remuneração mensal',type:'number'},{key:'months',label:'Meses',type:'number'},{key:'fgtsRate',label:'Alíquota FGTS (%)',type:'number'},{key:'deposited',label:'Valor depositado',type:'number'},{key:'expected',label:'FGTS esperado (opcional)',type:'number'}],
'Pensão Alimentícia':[{key:'income',label:'Renda',type:'number'},{key:'percentage',label:'Percentual (%)',type:'number'},{key:'fixedAmount',label:'Valor fixo (se houver)',type:'number'},{key:'dependents',label:'Número de alimentandos',type:'number'}],
'Divórcio e Partilha':[{key:'assets',label:'Bens',type:'number'},{key:'debts',label:'Dívidas',type:'number'},{key:'shareA',label:'Parte A (%)',type:'number'},{key:'shareB',label:'Parte B (%)',type:'number'}],
'Inventário e Quinhões':[{key:'estate',label:'Patrimônio',type:'number'},{key:'debts',label:'Dívidas',type:'number'},{key:'spouseShare',label:'Meação (%)',type:'number'},{key:'heirs',label:'Número de herdeiros',type:'number'}],
'Danos Materiais':[{key:'directLoss',label:'Dano emergente',type:'number'},{key:'lostProfits',label:'Lucros cessantes',type:'number'},{key:'otherLosses',label:'Outros prejuízos',type:'number'},{key:'correctionPercent',label:'Correção (%)',type:'number'},{key:'interestPercent',label:'Juros (%)',type:'number'}],
'Custas e Honorários':[{key:'claimValue',label:'Valor da causa',type:'number'},{key:'feesPercentage',label:'Honorários (%)',type:'number'},{key:'fixedFees',label:'Honorários fixos',type:'number'},{key:'courtCosts',label:'Custas',type:'number'},{key:'otherCosts',label:'Outras despesas',type:'number'}],
'Prazo Processual':[{key:'startDate',label:'Data inicial',type:'date'},{key:'days',label:'Quantidade de dias',type:'number'},{key:'countType',label:'Contagem',type:'select',options:[{value:'business',label:'Dias úteis'},{value:'calendar',label:'Dias corridos'}]}]
};
function text(v:any){return typeof v==='string'?v:JSON.stringify(v,null,2)}
function esc(v:any){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]||m))}
export default function Calculators(){
 const [calculator,setCalculator]=useState(calculators[0]),[data,setData]=useState<Record<string,any>>({}),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[clients,setClients]=useState<Client[]>([]),[processes,setProcesses]=useState<Process[]>([]),[clientId,setClientId]=useState(''),[processId,setProcessId]=useState(''),[orgId,setOrgId]=useState(''),[userId,setUserId]=useState(''),[brand,setBrand]=useState<any>({}),[logoUrl,setLogoUrl]=useState('');
 const current=useMemo(()=>fields[calculator]||[],[calculator]);const availableProcesses=useMemo(()=>clientId?processes.filter(p=>p.client_id===clientId):processes,[processes,clientId]);const client=clients.find(c=>c.id===clientId);const process=processes.find(p=>p.id===processId);
 useEffect(()=>{(async()=>{if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;setUserId(user.id);const {data:p}=await supabase.from('profiles').select('org_id,name,email,phone,oab_number,oab_uf').eq('id',user.id).maybeSingle();if(!p?.org_id)return;setOrgId(p.org_id);const [{data:c},{data:pr},{data:o},{data:s}]=await Promise.all([supabase.from('clients').select('id,name').order('name').limit(1000),supabase.from('processes').select('id,client_id,cnj_number,internal_number,subject').order('updated_at',{ascending:false}).limit(1000),supabase.from('organizations').select('name').eq('id',p.org_id).maybeSingle(),supabase.from('organization_settings').select('*').eq('org_id',p.org_id).maybeSingle()]);setClients((c||[]) as Client[]);setProcesses((pr||[]) as Process[]);const b={organization_name:s?.organization_name||o?.name||'',trade_name:s?.trade_name||'',email:s?.email||p.email||'',phone:s?.phone||p.phone||'',whatsapp:s?.whatsapp||'',website:s?.website||'',primary_color:s?.primary_color||'#8f1c3b',secondary_color:s?.secondary_color||'#5b1022',professional_name:p.name||'',oab_number:p.oab_number||'',oab_uf:p.oab_uf||'',logo_storage_path:s?.logo_storage_path||''};setBrand(b);if(b.logo_storage_path){const {data:u}=await supabase.storage.from('lexoffice-documents').createSignedUrl(b.logo_storage_path,3600);setLogoUrl(u?.signedUrl||'')}})()},[]);
 useEffect(()=>{if(clientId&&processId&&!availableProcesses.some(p=>p.id===processId))setProcessId('')},[clientId,processId,availableProcesses]);
 async function run(){if(!supabase)return;setBusy(true);setNotice('');try{const payload={...data};for(const f of current){if(f.type==='select'&&payload[f.key]===undefined)payload[f.key]=f.options?.[0]?.value??''}const {data:response,error}=await supabase.functions.invoke('legal-calculators',{body:{calculator,data:payload}});if(error)throw error;if((response as any)?.ok===false)throw new Error((response as any)?.error||'Falha no cálculo.');setResult(response)}catch(e:any){setNotice(e?.message||'Falha no cálculo.')}finally{setBusy(false)}}
 async function selfTest(){if(!supabase)return;setBusy(true);setNotice('');const {data:response,error}=await supabase.functions.invoke('legal-calculators',{body:{self_test:true,calculator:'__self_test__'}});setBusy(false);setNotice(error?error.message:(response as any)?.summary||'Teste concluído.')}
 function printReport(){if(!result)return;const w=window.open('','_blank','noopener,noreferrer');if(!w){setNotice('O navegador bloqueou a abertura do relatório. Permita pop-ups para imprimir.');return}const params=current.map(f=>`<tr><td>${esc(f.label)}</td><td>${esc(data[f.key]??f.options?.[0]?.label??'—')}</td></tr>`).join('');const resultText=esc(text(result.result));const contact=[brand.phone,brand.whatsapp,brand.email,brand.website].filter(Boolean).map(esc).join(' • ');const proc=process?(process.cnj_number||process.internal_number||process.subject||'Processo vinculado'):'';w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(calculator)}</title><style>@page{size:A4;margin:15mm}body{font-family:Arial,sans-serif;color:#1d2430;margin:0}.head{display:flex;align-items:center;gap:18px;border-bottom:3px solid ${esc(brand.primary_color)};padding-bottom:14px}.logo{width:82px;height:70px;object-fit:contain}.mark{width:70px;height:70px;display:grid;place-items:center;border-radius:14px;background:${esc(brand.primary_color)};color:white;font:bold 25px Georgia}.office h1{font:700 20px Georgia;margin:0}.office p{margin:5px 0 0;font-size:11px;color:#616a77}.title{margin:28px 0 18px}.title h2{font:700 24px Georgia;margin:0}.title p{font-size:12px;color:#69717d}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;background:#f5f6f8;padding:12px;border-radius:8px;font-size:12px}table{width:100%;border-collapse:collapse;margin-top:20px;font-size:12px}td{border-bottom:1px solid #e2e5e9;padding:9px}td:first-child{font-weight:700;width:42%}.result{margin-top:24px;border-left:4px solid ${esc(brand.primary_color)};padding:14px 16px;background:#fafafa;white-space:pre-wrap;line-height:1.55;font-size:13px}.foot{position:fixed;bottom:0;left:0;right:0;border-top:1px solid #ddd;padding-top:8px;font-size:10px;text-align:center;color:#6b7280}</style></head><body><div class="head">${logoUrl?`<img class="logo" src="${esc(logoUrl)}">`:`<div class="mark">SF</div>`}<div class="office"><h1>${esc(brand.trade_name||brand.organization_name||'Escritório de Advocacia')}</h1><p>${esc(brand.professional_name)}${brand.oab_number?` • OAB/${esc(brand.oab_uf||'')} ${esc(brand.oab_number)}`:''}</p></div></div><div class="title"><h2>Relatório de cálculo — ${esc(calculator)}</h2><p>Gerado em ${esc(new Date().toLocaleString('pt-BR'))}</p></div><div class="meta"><div><b>Cliente:</b> ${esc(client?.name||'Não vinculado')}</div><div><b>Processo:</b> ${esc(proc||'Não vinculado')}</div></div><table><tbody>${params}</tbody></table><div class="result"><b>RESULTADO</b><br><br>${resultText}</div><div class="foot">${contact||esc(brand.organization_name||'LEXOFFICE')} • Relatório gerado pelo LEXOFFICE</div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close()}
 async function saveReport(){if(!supabase||!orgId||!result)return;setBusy(true);setNotice('');const {error}=await supabase.from('generated_documents').insert({org_id:orgId,client_id:clientId||null,process_id:processId||null,template_id:null,title:`Relatório de cálculo - ${calculator}${client?` - ${client.name}`:''}`,mime_type:'application/x-lexoffice-calculation-report',variables:{document_type:'calculator_report',calculator,inputs:data,result:result.result,warnings:result.warnings||[],generated_at:new Date().toISOString(),branding_snapshot:brand},status:'approved',created_by:userId||null});setBusy(false);setNotice(error?'Não foi possível salvar o relatório: '+error.message:'Relatório timbrado salvo na biblioteca de documentos.')}
 return <><div className="page-title"><h1>Calculadoras Jurídicas</h1><p>Cálculos conectados ao motor jurídico do LEXOFFICE.</p></div><div className="integration-head"><div><span className="integration-pill"><Calculator size={14}/> MOTOR DE CÁLCULO</span><h2>Selecione a calculadora</h2><p>Todas as calculadoras agora possuem formulário próprio; confira juridicamente os parâmetros aplicáveis ao caso.</p></div><button className="integration-action" onClick={selfTest} disabled={busy}><ShieldCheck size={16}/>Testar motor</button></div>{notice&&<div className="integration-notice">{notice}</div>}<div className="integration-panel"><div className="integration-form"><label>Calculadora<select value={calculator} onChange={e=>{setCalculator(e.target.value);setData({});setResult(null);setNotice('')}}>{calculators.map(c=><option key={c}>{c}</option>)}</select></label><label><UserRound size={14}/> Cliente (opcional)<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Sem cliente vinculado</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><Scale size={14}/> Processo (opcional)<select value={processId} onChange={e=>setProcessId(e.target.value)}><option value="">Sem processo vinculado</option>{availableProcesses.map(p=><option key={p.id} value={p.id}>{p.cnj_number||p.internal_number||p.subject||'Processo'}</option>)}</select></label>{current.map(f=><label key={f.key}>{f.label}{f.type==='select'?<select value={data[f.key]??f.options?.[0]?.value??''} onChange={e=>setData({...data,[f.key]:e.target.value})}>{f.options?.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select>:<input type={f.type||'text'} step={f.type==='number'?'any':undefined} value={data[f.key]??''} onChange={e=>setData({...data,[f.key]:f.type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value})}/>}</label>)}<button className="integration-action" onClick={run} disabled={busy}><Play size={16}/>{busy?'Calculando...':'Calcular'}</button></div></div>{result&&<div className="integration-panel"><h3>Resultado</h3><pre style={{whiteSpace:'pre-wrap',fontFamily:'inherit',lineHeight:1.7}}>{text(result.result)}</pre>{Array.isArray(result.warnings)&&result.warnings.map((w:string,i:number)=><div className="integration-notice" key={i}>{w}</div>)}<div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:18}}><button className="integration-action" onClick={printReport}><Printer size={15}/>Gerar relatório timbrado / PDF</button><button className="secondary" onClick={saveReport} disabled={busy}><Save size={15}/>{busy?'Salvando...':'Salvar nos Documentos'}</button></div></div>}</>
}
