import { useMemo,useState } from 'react';
import { Calculator,Play,ShieldCheck } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './integrations.css';

type Field={key:string;label:string;type?:'number'|'date'|'select';options?:{value:string;label:string}[]};
const calculators=['Atualização monetária e juros','Revisional Bancária','Financiamento e empréstimos','Superendividamento','RMC / RCC INSS','Revisão PASEP','Benefícios Previdenciários','Contribuições acima do teto do INSS','Aluguel e reajuste locatício','Dosimetria da Pena','Progressão de Regime','Detração Penal','Liquidação Trabalhista','Horas Extras','Verbas Rescisórias','FGTS','Pensão Alimentícia','Divórcio e Partilha','Inventário e Quinhões','Danos Materiais','Custas e Honorários','Prazo Processual'];
const fields:Record<string,Field[]>={
'Atualização monetária e juros':[{key:'principal',label:'Principal',type:'number'},{key:'correctionPercent',label:'Correção (%)',type:'number'},{key:'penalty',label:'Multa (%)',type:'number'},{key:'rate',label:'Juros ao mês (%)',type:'number'},{key:'startDate',label:'Data inicial',type:'date'},{key:'endDate',label:'Data final',type:'date'}],
'Financiamento e empréstimos':[{key:'principal',label:'Valor principal',type:'number'},{key:'entryAmount',label:'Entrada',type:'number'},{key:'installmentCount',label:'Nº de parcelas',type:'number'},{key:'rate',label:'Taxa mensal (%)',type:'number'},{key:'system',label:'Sistema',type:'select',options:[{value:'price',label:'Price'},{value:'sac',label:'SAC'},{value:'simple',label:'Sem juros'}]}],
'Superendividamento':[{key:'income',label:'Renda líquida',type:'number'},{key:'essentialExpenses',label:'Despesas essenciais',type:'number'},{key:'monthlyDebt',label:'Dívidas mensais',type:'number'},{key:'totalDebt',label:'Dívida total',type:'number'},{key:'minimumExistence',label:'Mínimo existencial',type:'number'}],
'Aluguel e reajuste locatício':[{key:'rent',label:'Aluguel atual',type:'number'},{key:'indexPercentage',label:'Índice de reajuste (%)',type:'number'},{key:'months',label:'Meses',type:'number'}],
'Horas Extras':[{key:'salary',label:'Salário',type:'number'},{key:'monthlyHours',label:'Divisor mensal',type:'number'},{key:'extraHours',label:'Horas extras/mês',type:'number'},{key:'additionalPercentage',label:'Adicional (%)',type:'number'},{key:'periodMonths',label:'Meses do período',type:'number'}],
'Verbas Rescisórias':[{key:'salary',label:'Salário',type:'number'},{key:'daysWorked',label:'Dias trabalhados no mês',type:'number'},{key:'thirteenthMonths',label:'Avos de 13º',type:'number'},{key:'vacationMonths',label:'Avos de férias',type:'number'},{key:'overdueVacations',label:'Férias vencidas',type:'number'},{key:'noticeDays',label:'Dias de aviso',type:'number'}],
'FGTS':[{key:'remuneration',label:'Remuneração mensal',type:'number'},{key:'months',label:'Meses',type:'number'},{key:'fgtsRate',label:'Alíquota FGTS (%)',type:'number'},{key:'deposited',label:'Valor depositado',type:'number'}],
'Pensão Alimentícia':[{key:'income',label:'Renda',type:'number'},{key:'percentage',label:'Percentual (%)',type:'number'},{key:'fixedAmount',label:'Valor fixo (se houver)',type:'number'},{key:'dependents',label:'Número de alimentandos',type:'number'}],
'Divórcio e Partilha':[{key:'assets',label:'Bens',type:'number'},{key:'debts',label:'Dívidas',type:'number'},{key:'shareA',label:'Parte A (%)',type:'number'},{key:'shareB',label:'Parte B (%)',type:'number'}],
'Inventário e Quinhões':[{key:'estate',label:'Patrimônio',type:'number'},{key:'debts',label:'Dívidas',type:'number'},{key:'spouseShare',label:'Meação (%)',type:'number'},{key:'heirs',label:'Número de herdeiros',type:'number'}],
'Danos Materiais':[{key:'directLoss',label:'Dano emergente',type:'number'},{key:'lostProfits',label:'Lucros cessantes',type:'number'},{key:'otherLosses',label:'Outros prejuízos',type:'number'},{key:'correctionPercent',label:'Correção (%)',type:'number'},{key:'interestPercent',label:'Juros (%)',type:'number'}],
'Custas e Honorários':[{key:'claimValue',label:'Valor da causa',type:'number'},{key:'feesPercentage',label:'Honorários (%)',type:'number'},{key:'fixedFees',label:'Honorários fixos',type:'number'},{key:'courtCosts',label:'Custas',type:'number'},{key:'otherCosts',label:'Outras despesas',type:'number'}],
'Prazo Processual':[{key:'startDate',label:'Data inicial',type:'date'},{key:'days',label:'Quantidade de dias',type:'number'},{key:'countType',label:'Contagem',type:'select',options:[{value:'business',label:'Dias úteis'},{value:'calendar',label:'Dias corridos'}]}],
'Progressão de Regime':[{key:'sentenceMonths',label:'Pena (meses)',type:'number'},{key:'fraction',label:'Fração exigida (%)',type:'number'},{key:'detraction',label:'Detração (dias)',type:'number'},{key:'remission',label:'Remição (dias)',type:'number'},{key:'servedDays',label:'Dias já cumpridos',type:'number'}],
'Detração Penal':[{key:'custodyStart',label:'Início da custódia',type:'date'},{key:'custodyEnd',label:'Fim da custódia',type:'date'},{key:'otherDays',label:'Outros dias',type:'number'},{key:'sentenceMonths',label:'Pena (meses)',type:'number'}]
};
export default function Calculators(){const [calculator,setCalculator]=useState(calculators[0]),[data,setData]=useState<Record<string,any>>({}),[raw,setRaw]=useState('{}'),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const current=useMemo(()=>fields[calculator]||[],[calculator]);
function changeCalculator(v:string){setCalculator(v);setData({});setRaw('{}');setResult(null);setNotice('')}
async function run(){if(!supabase)return;setBusy(true);setNotice('');try{let payload=data;if(!current.length){try{payload=JSON.parse(raw||'{}')}catch{throw new Error('Os parâmetros JSON estão inválidos.')}}const {data:response,error}=await supabase.functions.invoke('legal-calculators',{body:{calculator,data:payload}});if(error)throw error;if((response as any)?.ok===false)throw new Error((response as any)?.error||'Falha no cálculo.');setResult(response)}catch(e:any){setNotice(e?.message||'Falha no cálculo.')}finally{setBusy(false)}}
async function selfTest(){if(!supabase)return;setBusy(true);setNotice('');const {data:response,error}=await supabase.functions.invoke('legal-calculators',{body:{self_test:true,calculator:'__self_test__'}});setBusy(false);if(error)setNotice(error.message);else setNotice((response as any)?.summary||'Teste concluído.')}
return <><div className="page-title"><h1>Calculadoras Jurídicas</h1><p>Cálculos conectados ao motor jurídico do LEXOFFICE.</p></div><div className="integration-head"><div><span className="integration-pill"><Calculator size={14}/> MOTOR DE CÁLCULO</span><h2>Selecione a calculadora</h2><p>Os resultados são matemáticos e devem ser conferidos pelo profissional responsável.</p></div><button className="integration-action" onClick={selfTest} disabled={busy}><ShieldCheck size={16}/>Testar motor</button></div>{notice&&<div className="integration-notice">{notice}</div>}<div className="integration-panel"><div className="integration-form"><label>Calculadora<select value={calculator} onChange={e=>changeCalculator(e.target.value)}>{calculators.map(c=><option key={c}>{c}</option>)}</select></label>{current.length?current.map(f=><label key={f.key}>{f.label}{f.type==='select'?<select value={data[f.key]??f.options?.[0]?.value??''} onChange={e=>setData({...data,[f.key]:e.target.value})}>{f.options?.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select>:<input type={f.type||'text'} step={f.type==='number'?'any':undefined} value={data[f.key]??''} onChange={e=>setData({...data,[f.key]:f.type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value})}/>}</label>):<label>Parâmetros avançados (JSON)<textarea rows={10} value={raw} onChange={e=>setRaw(e.target.value)} placeholder='{"campo": 0}'/></label>}<button className="integration-action" onClick={run} disabled={busy}><Play size={16}/>{busy?'Calculando...':'Calcular'}</button></div></div>{result&&<div className="integration-panel"><h3>Resultado</h3><pre style={{whiteSpace:'pre-wrap',fontFamily:'inherit',lineHeight:1.7}}>{result.result}</pre>{Array.isArray(result.warnings)&&result.warnings.map((w:string,i:number)=><div className="integration-notice" key={i}>{w}</div>)}</div>}</>}
