import { ArrowLeft, Check, CreditCard, FileText, LockKeyhole, QrCode, ShieldCheck } from 'lucide-react';
import { useMemo, useState } from 'react';

type PlanKey='essencial'|'profissional'|'avancado'|'enterprise';
const plans:Record<PlanKey,{name:string;price:number;description:string}>={
  essencial:{name:'Essencial',price:149,description:'1 usuário · até 100 processos'},
  profissional:{name:'Profissional',price:299,description:'até 3 usuários · até 500 processos'},
  avancado:{name:'Avançado',price:499,description:'até 10 usuários · processos ilimitados'},
  enterprise:{name:'Enterprise',price:0,description:'Plano personalizado'}
};

export default function Checkout(){
  const params=new URLSearchParams(window.location.search);
  const selected=((params.get('plano')||'profissional') in plans?(params.get('plano')||'profissional'):'profissional') as PlanKey;
  const plan=plans[selected];
  const [method,setMethod]=useState('PIX');
  const price=useMemo(()=>plan.price.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),[plan.price]);
  return <div className="checkout-page"><style>{`
.checkout-page{min-height:100vh;background:radial-gradient(circle at 50% 0%,rgba(178,24,32,.10),transparent 30%),#0b1017;color:#f5f7fa;font-family:Inter,Segoe UI,Arial,sans-serif;padding:0 20px 60px}.checkout-shell{max-width:1160px;margin:auto}.checkout-top{height:76px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(255,255,255,.08)}.brand{font-weight:900;letter-spacing:.05em;font-size:20px}.brand span{color:#e02b32}.back{display:flex;align-items:center;gap:7px;color:#aeb7c3;text-decoration:none;font-size:13px}.title{text-align:center;padding:54px 0 34px}.title h1{font-size:clamp(34px,5vw,54px);margin:0 0 10px;letter-spacing:-.04em}.title p{margin:0;color:#9ba6b3}.grid{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(320px,.75fr);gap:18px}.panel{border:1px solid rgba(255,255,255,.10);background:linear-gradient(155deg,rgba(24,31,41,.97),rgba(14,19,27,.99));border-radius:20px;padding:26px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:14px}.field{display:grid;gap:7px}.field.full{grid-column:1/-1}.field label{font-size:12px;color:#aeb7c3;font-weight:700}.field input{width:100%;box-sizing:border-box;border-radius:11px;border:1px solid rgba(255,255,255,.11);background:#0d141d;color:#fff;padding:13px 14px;outline:none}.pay-title{margin:26px 0 12px;font-size:13px;font-weight:900}.methods{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.method{border:1px solid rgba(255,255,255,.10);background:#111923;color:#dbe1e7;border-radius:12px;padding:13px 10px;cursor:pointer;display:flex;align-items:center;justify-content:center;gap:8px;font-weight:800}.method.active{border-color:#e02b32;background:rgba(214,37,45,.12);color:#fff}.submit{margin-top:18px;width:100%;border:1px solid #e02b32;border-radius:12px;padding:15px;background:linear-gradient(145deg,#d6252d,#a51218);color:white;font-weight:900;cursor:pointer}.secure{display:flex;justify-content:center;align-items:center;gap:7px;color:#7f8a98;font-size:11px;margin-top:12px}.summary small{color:#ff6b70;font-weight:900}.summary h3{font-size:26px;margin:8px 0 5px}.summary p{color:#98a3b0;font-size:13px}.price{display:flex;justify-content:space-between;align-items:end;margin:24px 0;padding:20px 0;border-top:1px solid rgba(255,255,255,.08);border-bottom:1px solid rgba(255,255,255,.08)}.price strong{font-size:30px}.items{display:grid;gap:12px;color:#c9d0d8;font-size:13px}.items div{display:flex;gap:8px;align-items:center}.items svg{color:#61c79b}.provider{margin-top:24px;color:#8793a0;font-size:11px;line-height:1.55}@media(max-width:850px){.grid{grid-template-columns:1fr}.summary{order:-1}}@media(max-width:600px){.fields,.methods{grid-template-columns:1fr}.field.full{grid-column:auto}}
`}</style><div className="checkout-shell"><header className="checkout-top"><div className="brand">⚖ LEX<span>OFFICE</span></div><a className="back" href="/planos"><ArrowLeft size={15}/> Voltar aos planos</a></header><section className="title"><h1>Finalizar contratação</h1><p>Seu escritório está a poucos passos de uma nova inteligência.</p></section><div className="grid"><section className="panel"><h2>Dados do escritório</h2><div className="fields"><div className="field"><label>Nome completo</label><input placeholder="Responsável pela contratação"/></div><div className="field"><label>Nome do escritório</label><input placeholder="Nome profissional ou razão social"/></div><div className="field"><label>CPF ou CNPJ</label><input placeholder="CPF ou CNPJ"/></div><div className="field"><label>Telefone / WhatsApp</label><input placeholder="(31) 99999-9999"/></div><div className="field full"><label>E-mail de acesso</label><input type="email" placeholder="voce@escritorio.com.br"/></div></div><div className="pay-title">FORMA DE PAGAMENTO</div><div className="methods"><button type="button" className={`method ${method==='PIX'?'active':''}`} onClick={()=>setMethod('PIX')}><QrCode size={18}/> PIX</button><button type="button" className={`method ${method==='BOLETO'?'active':''}`} onClick={()=>setMethod('BOLETO')}><FileText size={18}/> Boleto</button><button type="button" className={`method ${method==='CARTAO'?'active':''}`} onClick={()=>setMethod('CARTAO')}><CreditCard size={18}/> Cartão</button></div><button className="submit" type="button">Ir para pagamento seguro</button><div className="secure"><LockKeyhole size={13}/> Pagamento via Asaas</div></section><aside className="panel summary"><small>SEU PLANO</small><h3>{plan.name}</h3><p>{plan.description}</p><div className="price"><span>Total mensal</span><strong>{selected==='enterprise'?'Sob consulta':price}</strong></div><div className="items"><div><Check size={15}/> Ativação após confirmação</div><div><Check size={15}/> Recursos liberados conforme o plano</div><div><Check size={15}/> Usuários e permissões do escritório</div><div><ShieldCheck size={15}/> Confirmação automática preparada</div></div><div className="provider">PIX, boleto e cartão serão processados pelo Asaas. Nenhum dado de cartão será armazenado no LexOffice.</div></aside></div></div></div>
}
