import React,{useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';
import './client-portal.css';

const SUPA='https://dcpwcuototomxoiszukt.supabase.co';
const KEY='sb_publishable_h1gal1BQha__PKo2_wxY_Q_wZfAqoEm';
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=(v:any)=>v?new Date(v).toLocaleDateString('pt-BR'):'';
type Tab='home'|'process'|'messages'|'documents'|'steps'|'finance'|'service'|'urgent';

export default function ClientPortal(){
 const[session,setSession]=useState<any>(undefined),[cpf,setCpf]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState('');
 const[tab,setTab]=useState<Tab>('home'),[ctx,setCtx]=useState<any>(),[processes,setProcesses]=useState<any[]>([]),[movements,setMovements]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([]),[docs,setDocs]=useState<any[]>([]),[steps,setSteps]=useState<any[]>([]),[finance,setFinance]=useState<any[]>([]);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session)return;(async()=>{const {data:c}=await supabase.rpc('client_app_context');const x=c?.[0];setCtx(x);const [p,m,d,s,f]=await Promise.all([supabase.rpc('client_app_processes'),x?.client_id?supabase.from('client_office_messages').select('*').eq('client_id',x.client_id).is('archived_at',null).order('sent_at',{ascending:false}):Promise.resolve({data:[]}),x?.client_id?supabase.from('client_document_requests').select('*').eq('client_id',x.client_id).order('created_at'):Promise.resolve({data:[]}),x?.client_id?supabase.from('client_case_steps').select('*').eq('client_id',x.client_id).order('position'):Promise.resolve({data:[]}),supabase.rpc('client_app_finance')]);setProcesses(p.data||[]);setMessages(m.data||[]);setDocs(d.data||[]);setSteps(s.data||[]);setFinance(f.data||[]);if(p.data?.[0]){const mm=await supabase.rpc('client_app_movements',{p_process_id:p.data[0].id});setMovements(mm.data||[])}})()},[session]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setErr('');if(cpf.trim().toUpperCase()==='SUZANNE'&&code.trim().toUpperCase()==='SF2026'){localStorage.setItem('sf-demo','1');setSession({user:{id:'demo',user_metadata:{client_app:true}}});setBusy(false);return}const digits=cpf.replace(/\D/g,'');if(digits.length!==11||!code.trim()){setBusy(false);setErr('Informe seu CPF e o código de acesso fornecido pelo escritório.');return}try{const r=await fetch(SUPA+'/functions/v1/swift-service?action=client-app-auth',{method:'POST',headers:{'Content-Type':'application/json',apikey:KEY,Authorization:'Bearer '+KEY},body:JSON.stringify({cpf:digits,access_code:code.trim()})});const d=await r.json();if(!r.ok||!d?.email||!d?.password)throw 0;const a=await supabase.auth.signInWithPassword({email:d.email,password:d.password});if(a.error)throw 0}catch{setErr('CPF ou código de acesso inválido.')}finally{setBusy(false)}}
 const baseSteps=['Contratação','Documentos','Análise do caso','Elaboração da medida','Protocolo','Distribuição','Acompanhamento','Audiências / Decisões','Encerramento'];
 const stepList=steps.length?steps:baseSteps.map((label,i)=>({id:label,label,position:i+1,status:'pending'}));
 const demo=localStorage.getItem('sf-demo')==='1'; const current=processes[0],contract=finance[0];
 const tiles=useMemo(()=>[
  ['Meu Processo','process','▤'],['Recados do Escritório','messages','✉'],['Documentos','documents','▧'],['Próximos Passos','steps','⚖'],['Financeiro','finance','▣'],['Meu Atendimento','service','♧']
 ] as const,[]);
 if(session===undefined)return <div className="cp-loading">SF</div>;
 if(!session&&localStorage.getItem('sf-demo')!=='1')return <div className="cp-login"><div className="cp-login-card"><div className="cp-seal">SF</div><h1>SUZANNE FIGUEIREDO</h1><small>ADVOCACIA E SOLUÇÕES JURÍDICAS</small><h2>Bem-vinda ao nosso escritório!</h2><p className="cp-script">Mais que direito, soluções para a sua vida.</p><form onSubmit={login}><input placeholder="Seu CPF ou login de teste" value={cpf} onChange={e=>setCpf(e.target.value)}/><input type="password" placeholder="Código de acesso" value={code} onChange={e=>setCode(e.target.value)}/>{err&&<p className="cp-error">{err}</p>}<button disabled={busy}>{busy?'Entrando...':'Começar'}</button></form></div></div>;
 const Header=({n,title}:{n:string,title:string})=><header className="cp-head"><span>{n}</span><h2>{title}</h2><i/></header>;
 const Back=()=>tab!=='home'?<button className="cp-back" onClick={()=>setTab('home')}>‹ Início</button>:null;
 return <div className="cp-shell"><main className="cp-phone"><Back/>
 {tab==='home'&&<><section className="cp-hero"><div className="cp-seal small">SF</div><h1>SUZANNE FIGUEIREDO</h1><small>ADVOCACIA E SOLUÇÕES JURÍDICAS</small><h2>Olá, {demo?'Suzanne':(ctx?.client_name?.split(' ')[0]||'Cliente')}!<br/>Bem-vinda ao seu espaço exclusivo.</h2></section><div className="cp-grid">{tiles.map(([label,t,icon])=><button key={t} onClick={()=>setTab(t as Tab)}><b>{icon}</b><span>{label}</span></button>)}</div><button className="cp-talk" onClick={()=>setTab('service')}>✥ &nbsp; Falar com o Escritório</button></>}
 {tab==='process'&&<><Header n="02" title="MEU PROCESSO"/><section className="cp-card"><h3>Meu Processo</h3><p>Acompanhe o andamento do seu caso com informações atualizadas e linguagem simples.</p>{current?<><label>Selecione o processo</label><div className="cp-select">{current.cnj_number||'Aguardando protocolo'}<br/><small>{current.area||current.subject}</small></div><p className="cp-ok">● Em andamento</p>{movements.slice(0,4).map((m:any)=><article className="cp-move" key={m.id}><b>{m.title||'Atualização processual'}</b><small>{date(m.movement_date)}</small><p>{m.client_message||m.description}</p></article>)}</>:<p>Nenhum processo liberado para exibição.</p>}</section></>}
 {tab==='messages'&&<><Header n="03" title="RECADOS DO ESCRITÓRIO"/><section className="cp-card"><h3>Recados do Escritório</h3><p>Informações importantes sobre seu atendimento.</p>{messages.length?messages.map((m:any)=><article className={'cp-notice '+String(m.category||'').toLowerCase()} key={m.id}><small>{m.category||'INFORMATIVO'}</small><b>{m.title}</b><p>{m.body}</p><time>{new Date(m.sent_at).toLocaleString('pt-BR')}</time></article>):<p>Nenhum recado novo.</p>}</section></>}
 {tab==='documents'&&<><Header n="04" title="DOCUMENTOS"/><section className="cp-card"><h3>Documentos</h3><p>Envie e acesse seus documentos de forma segura.</p><h4>Checklist do seu caso</h4>{docs.length?docs.map((d:any)=><article className="cp-doc" key={d.id}><span>▧</span><div><b>{d.title}</b><small>{d.status==='pending'?'Pendente':'Recebido'}</small></div></article>):['Documento de identificação (RG e CPF)','Comprovante de endereço','Certidão de casamento ou nascimento','Comprovantes de renda','Conversas, prints e provas relevantes','Documentos específicos'].map((x,i)=><article className="cp-doc" key={x}><span>▧</span><div><b>{x}</b><small>{i===0?'Recebido':'Pendente'}</small></div></article>)}</section></>}
 {tab==='steps'&&<><Header n="05" title="PRÓXIMOS PASSOS"/><section className="cp-card"><h3>Próximos Passos</h3><p>Entenda as principais etapas do seu caso.</p>{stepList.map((s:any,i:number)=><article className="cp-step" key={s.id}><span>{i+1}</span><div><b>{s.label}</b><small>{s.status==='completed'?'Concluído':s.status==='current'?'Etapa atual':''}</small></div></article>)}<p className="cp-note">Cada processo possui dinâmica própria. Os prazos dos atos do Poder Judiciário não são controlados pelo escritório.</p></section></>}
 {tab==='finance'&&<><Header n="06" title="FINANCEIRO"/><section className="cp-card"><h3>Financeiro</h3><p>Acompanhe seu plano de honorários de forma clara e organizada.</p>{contract?<><div className="cp-summary"><b>Valor contratado</b><strong>{money(contract.total_amount)}</strong><span>Entrada: {money(contract.down_payment_amount)}</span><span>Parcelas: {contract.installments_count}</span><span>Vencimento: {contract.due_day?'dia '+contract.due_day:'conforme contrato'}</span></div>{finance.filter((x:any)=>x.installment_id).slice(0,6).map((x:any)=><article className="cp-install" key={x.installment_id}><span>{date(x.due_date)}</span><b>{money(x.original_amount)}</b><em>{x.installment_status==='paid'?'Paga':x.installment_status}</em></article>)}</>:<p>Nenhum contrato financeiro disponível.</p>}<div className="cp-person"><b>Dra. Gláucia Gomes</b><small>Financeiro e Assessora Jurídica</small></div></section></>}
 {tab==='service'&&<><Header n="07" title="MEU ATENDIMENTO"/><section className="cp-card"><h3>Meu Atendimento</h3><p>Seus contatos e informações principais, sempre à mão.</p><div className="cp-person"><b>Dra. Suzanne Figueiredo</b><small>Responsável pela condução jurídica do seu caso</small></div><div className="cp-person"><b>Dra. Gláucia Gomes</b><small>Financeiro e Assessora Jurídica</small></div><div className="cp-person"><b>Helena</b><small>Atendimento e organização</small></div><h4>Canais oficiais do escritório</h4><p>☎ (31) 99690-5968<br/>☎ (31) 99298-4141<br/>✉ glaudicaadv15@gmail.com<br/>✉ eulampiosuzanne@gmail.com</p><button className="cp-gold" onClick={()=>setTab('urgent')}>Quando nos avisar imediatamente?</button></section></>}
 {tab==='urgent'&&<><Header n="08" title="QUANDO NOS AVISAR"/><section className="cp-card"><h3>Quando nos avisar imediatamente?</h3><p>Entre em contato o quanto antes em situações que possam impactar diretamente o seu caso.</p>{['Risco à vida ou à integridade física.','Ameaça grave relacionada ao caso.','Intimação ou documento com prazo que você acabou de receber.','Fato novo urgente que possa exigir providência jurídica.'].map(x=><div className="cp-alert" key={x}>⚠ {x}</div>)}<div className="cp-letter"><h4>Uma mensagem da Dra. Suzanne</h4><p>É uma satisfação ter você conosco. A partir de agora, seu caso passa a ser acompanhado por uma estrutura jurídica organizada, com atenção, responsabilidade e clareza em cada etapa.</p><strong>Dra. Suzanne Figueiredo</strong><small>OAB/MG</small></div></section></>}
 </main><nav className="cp-nav"><button onClick={()=>setTab('home')}>⌂<small>Início</small></button><button onClick={()=>setTab('messages')}>●<small>Notificações</small></button><button onClick={()=>{localStorage.removeItem('sf-demo');supabase.auth.signOut();setSession(null)}}>♙<small>Sair</small></button></nav></div>
}