import { useMemo,useState } from 'react';
import { Search,Filter,Star,Phone,Home,Car,Network,IdCard,Briefcase,Copyright,Scale,Landmark,Users,Building2,MapPin,DollarSign,Play } from 'lucide-react';
import './consultas.css';
type Consulta={title:string;description:string;icon:any;kind:string;field:string;placeholder:string};
const consultas:Consulta[]=[
 {title:'Dados por telefone',description:'Consulta de informações cadastrais disponíveis a partir de um número de telefone.',icon:Phone,kind:'Pessoa',field:'Telefone',placeholder:'Ex.: (31) 99999-9999'},
 {title:'Imóveis financiados',description:'Consulta de imóveis financiados e situação das operações vinculadas ao CPF/CNPJ.',icon:Home,kind:'Patrimônio',field:'CPF/CNPJ',placeholder:'Digite CPF ou CNPJ'},
 {title:'Imóveis rurais',description:'Consulta de informações de imóveis rurais em fontes oficiais disponíveis.',icon:Landmark,kind:'Patrimônio',field:'CPF/CNPJ ou matrícula',placeholder:'CPF/CNPJ ou matrícula'},
 {title:'Débitos veiculares',description:'Consulta de débitos, multas, IPVA e licenciamento quando a fonte integrada permitir.',icon:Car,kind:'Veículos',field:'Placa ou RENAVAM',placeholder:'Digite placa ou RENAVAM'},
 {title:'Dados da CNH',description:'Consulta de informações de CNH em fontes autorizadas e integradas.',icon:IdCard,kind:'Veículos',field:'CPF',placeholder:'Digite o CPF'},
 {title:'Rastreamento de veículo',description:'Central para consultas de rastreamento veicular quando houver provedor autorizado conectado.',icon:Car,kind:'Veículos',field:'Placa',placeholder:'Digite a placa'},
 {title:'Grupo econômico',description:'Relações empresariais para identificação de possível grupo econômico.',icon:Network,kind:'Empresas',field:'CPF/CNPJ',placeholder:'Digite CPF ou CNPJ'},
 {title:'Situação cadastral',description:'Situação cadastral de pessoa física ou jurídica em fontes oficiais disponíveis.',icon:IdCard,kind:'Pessoa',field:'CPF/CNPJ',placeholder:'Digite CPF ou CNPJ'},
 {title:'Dados profissionais',description:'Consulta de vínculos e dados profissionais disponíveis em fontes autorizadas.',icon:Briefcase,kind:'Pessoa',field:'CPF',placeholder:'Digite o CPF'},
 {title:'Marcas e patentes',description:'Informações e histórico de marcas e patentes relacionadas à pessoa física ou jurídica.',icon:Copyright,kind:'Empresas',field:'Nome, CPF/CNPJ ou marca',placeholder:'Digite nome, documento ou marca'},
 {title:'Processos',description:'Pesquisa de processos envolvendo pessoa física ou jurídica nas fontes judiciais integradas.',icon:Scale,kind:'Jurídico',field:'CPF/CNPJ, nome ou CNJ',placeholder:'Digite documento, nome ou número CNJ'},
 {title:'Restrição de crédito',description:'Consulta de restrições e informações de crédito por meio de provedor autorizado.',icon:DollarSign,kind:'Crédito',field:'CPF/CNPJ',placeholder:'Digite CPF ou CNPJ'},
 {title:'Relacionamentos',description:'Consulta de relações familiares e societárias disponíveis em fontes autorizadas.',icon:Users,kind:'Pessoa',field:'CPF/CNPJ',placeholder:'Digite CPF ou CNPJ'},
 {title:'Participações societárias',description:'Informações sobre sociedades relacionadas à pessoa física ou jurídica.',icon:Building2,kind:'Empresas',field:'CPF/CNPJ',placeholder:'Digite CPF ou CNPJ'},
 {title:'Dados da empresa',description:'Dados cadastrais da pessoa jurídica, CNAEs e quadro societário em fontes oficiais.',icon:Building2,kind:'Empresas',field:'CNPJ',placeholder:'Digite o CNPJ'},
 {title:'Localização de pessoa',description:'Consulta de endereços e meios de contato somente por provedores legalmente autorizados.',icon:MapPin,kind:'Pessoa',field:'CPF ou nome completo',placeholder:'Digite CPF ou nome completo'},
 {title:'Propriedade veicular',description:'Consulta de veículos vinculados à pessoa quando disponível em fonte autorizada.',icon:Car,kind:'Veículos',field:'CPF/CNPJ',placeholder:'Digite CPF ou CNPJ'},
 {title:'Dados do veículo',description:'Consulta de dados cadastrais do veículo e informações disponibilizadas pelo provedor conectado.',icon:Car,kind:'Veículos',field:'Placa, RENAVAM ou chassi',placeholder:'Digite placa, RENAVAM ou chassi'}
];
export default function Consultas(){const [q,setQ]=useState(''),[filter,setFilter]=useState('Todos'),[selected,setSelected]=useState<Consulta|null>(null),[term,setTerm]=useState(''),[notice,setNotice]=useState('');const kinds=['Todos',...Array.from(new Set(consultas.map(x=>x.kind)))];const list=useMemo(()=>consultas.filter(x=>(filter==='Todos'||x.kind===filter)&&(`${x.title} ${x.description}`.toLowerCase().includes(q.toLowerCase()))),[q,filter]);function select(x:Consulta){setSelected(x);setTerm('');setNotice('');setTimeout(()=>document.getElementById('investigation-form')?.scrollIntoView({behavior:'smooth',block:'center'}),0)}function run(){if(!selected||!term.trim()){setNotice('Preencha o campo da pesquisa.');return}setNotice('Pesquisa pronta para execução. Se a fonte exigir provedor externo, conecte o provedor autorizado em Integrações; pesquisas judiciais usam as fontes processuais já integradas ao LEXOFFICE.')}
return <div className="investigation-page"><div className="page-title"><h1>Investigações e Consultas</h1><p>Pesquisas cadastrais, patrimoniais, empresariais e processuais em uma interface clara e selecionável.</p></div><div className="integration-panel investigation-filter"><div className="integration-head"><div><span className="integration-pill"><Search size={14}/> NOVA PESQUISA</span><h2>Escolha o tipo de investigação</h2><p>Clique em um quadro abaixo. O formulário da pesquisa será aberto imediatamente.</p></div></div><div className="investigation-search"><label className="field"><span>Localizar tipo de consulta</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ex.: processos, telefone, veículo, empresa"/></label><label className="field"><span><Filter size={14}/> Categoria</span><select value={filter} onChange={e=>setFilter(e.target.value)}>{kinds.map(k=><option key={k}>{k}</option>)}</select></label></div></div><div className="investigation-grid">{list.map(x=>{const Icon=x.icon;return <button type="button" key={x.title} className={`investigation-card ${selected?.title===x.title?'selected':''}`} onClick={()=>select(x)}><div className="card-icon"><Icon size={21}/></div><div><strong>{x.title}</strong><p>{x.description}</p><small>{x.kind} · Clique para selecionar</small></div><Star size={16} className="investigation-star"/></button>})}</div>{selected&&<section id="investigation-form" className="integration-panel investigation-form"><div className="integration-head"><div><span className="integration-pill">PESQUISA SELECIONADA</span><h2>{selected.title}</h2><p>{selected.description}</p></div><button className="secondary" onClick={()=>{setSelected(null);setTerm('');setNotice('')}}>Fechar</button></div><label className="field investigation-main-field"><span>{selected.field}</span><input autoFocus value={term} onChange={e=>setTerm(e.target.value)} placeholder={selected.placeholder} onKeyDown={e=>{if(e.key==='Enter')run()}}/></label><button className="primary investigation-run" onClick={run}><Play size={16}/> Pesquisar agora</button>{notice&&<div className="integration-notice">{notice}</div>}</section>}</div>}
