import {useEffect,useState} from 'react';
import {Search,Landmark,RefreshCw,Gavel,CalendarDays,Scale,UserRound,FileSearch,Printer} from 'lucide-react';
import {supabase} from '../lib/supabase';
import './integrations.css';
const ufs=['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'];
const tribunals=[['STF','Supremo Tribunal Federal'],['STJ','Superior Tribunal de Justiça'],['TST','Tribunal Superior do Trabalho'],...[1,2,3,4,5,6].map(n=>[`TRF${n}`,`Tribunal Regional Federal da ${n}ª Região`]),...ufs.map(uf=>[`TJ${uf}`,`Tribunal de Justiça de ${uf}`]),...Array.from({length:24},(_,i)=>[`TRT${i+1}`,`Tribunal Regional do Trabalho da ${i+1}ª Região`])] as [string,string][];
const fmt=(v:any)=>{if(!v)return '—';const s=String(v);if(/^\d{14}$/.test(s))return `${s.slice(6,8)}/${s.slice(4,6)}/${s.slice(0,4)} ${s.slice(8,10)}:${s.slice(10,12)}`;const d=new Date(s);return isNaN(d.getTime())?s:d.toLocaleString('pt-BR')};
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c] as string));
export default function Consultations(){
 const[cnj,setCnj]=useState(''),[tribunal,setTribunal]=useState('TJMG'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[result,setResult]=useState<any>(null),[logo,setLogo]=useState(''),[office,setOffice]=useState<any>(null);
 useEffect(()=>{(async()=>{if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:p}=await supabase.from('profiles').select('org_id').eq('id',user.id).maybeSingle();if(!p?.org_id)return;const{data:o}=await supabase.from('organization_settings').select('organization_name,trade_name,email,phone,address,logo_storage_path').eq('org_id',p.org_id).maybeSingle();setOffice(o||null);if(o?.logo_storage_path){const{data:u}=supabase.storage.from('lexoffice-documents').getPublicUrl(o.logo_storage_path);setLogo(u.publicUrl)}})()},[]);
 async function consult(){if(!supabase)return;setBusy(true);setNotice('');setResult(null);try{const {data,error}=await supabase.functions.invoke('tribunal-connection-manager',{body:{action:'consult_process',cnj_number:cnj,tribunal_code:tribunal}});if(error)throw new Error((data as any)?.error||error.message);if((data as any)?.error)throw new Error((data as any).error);if(!(data as any)?.found){setNotice((data as any)?.message||'Processo não localizado.');return}setResult((data as any).process)}catch(e:any){setNotice(e?.message||'Falha na consulta processual.')}finally{setBusy(false)}}
 const mov=[...(result?.movimentos||[])].sort((a:any,b:any)=>String(b.dataHora||b.data||'').localeCompare(String(a.dataHora||a.data||''))).slice(0,30);
 function print(){if(!result)return;const w=window.open('','_blank');if(!w)return;const officeName=office?.trade_name||office?.organization_name||'LEXOFFICE';const subjects=(result.assuntos||[]).map((x:any)=>x.nome||x.codigo).filter(Boolean).join(' · ')||'—';const movements=mov.map((m:any)=>`<div class="movement"><b>${esc(m.nome||m.descricao||`Movimento ${m.codigo||''}`)}</b><span>${esc(fmt(m.dataHora||m.data))}</span></div>`).join('');w.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Consulta Processual</title><style>@page{size:A4;margin:18mm}body{font-family:Georgia,'Times New Roman',serif;color:#1d1d1d;font-size:11.5pt;line-height:1.55}.head{display:flex;align-items:center;gap:18px;border-bottom:2px solid #8f1f3e;padding-bottom:12px;margin-bottom:22px}.head img{width:62px;height:78px;object-fit:contain}.head h1{margin:0;font-size:18pt}.head p{margin:2px 0;font:9.5pt Arial,sans-serif;color:#555}.box{border:1px solid #ccc;padding:14px 16px;margin:0 0 16px;border-radius:6px}.box h2{font-size:13pt;margin:0 0 8px}.box p{margin:5px 0;text-align:justify;hyphens:auto}.movement{padding:8px 0;border-bottom:1px solid #ddd}.movement b{display:block}.movement span{font:9pt Arial,sans-serif;color:#666}.foot{margin-top:24px;border-top:1px solid #aaa;padding-top:8px;font:8.5pt Arial,sans-serif;color:#666}</style></head><body><div class="head">${logo?`<img src="${esc(logo)}">`:''}<div><h1>${esc(officeName)}</h1><p>Consulta Processual</p><p>Emitida em ${new Date().toLocaleString('pt-BR')}</p></div></div><div class="box"><h2>Dados do processo</h2><p><b>Processo:</b> ${esc(result.numeroProcesso||cnj)}</p><p><b>Tribunal:</b> ${esc(result.tribunal||tribunal)}</p><p><b>Classe:</b> ${esc(result.classe?.nome||result.classe?.codigo||'—')}</p><p><b>Órgão julgador:</b> ${esc(result.orgaoJulgador?.nome||'—')}</p><p><b>Assuntos:</b> ${esc(subjects)}</p><p><b>Ajuizamento:</b> ${esc(fmt(result.dataAjuizamento))}</p></div><div class="box"><h2>Andamentos</h2>${movements||'<p>Nenhum andamento público retornado.</p>'}</div><div class="foot">${esc(office?.address||'')}${office?.phone?` · ${esc(office.phone)}`:''}${office?.email?` · ${esc(office.email)}`:''}</div></body></html>`);w.document.close();setTimeout(()=>w.print(),300)}
 return <div className="module"><div className="page-head"><div><h1>Consultas</h1><p>Consulta processual nacional por número CNJ, com dados públicos disponíveis no DataJud.</p></div>{result&&<button className="primary" onClick={print}><Printer size={15}/>Imprimir / PDF com minha logo</button>}</div><div className="system-bar"><span><FileSearch size={14}/> CONSULTA PROCESSUAL</span><span className="online">● FONTE OFICIAL · DATAJUD/CNJ</span></div><div className="integration-panel"><h3><Search size={17}/> Consultar processo</h3><div className="integration-form"><label>Número do processo CNJ<input value={cnj} onChange={e=>setCnj(e.target.value)} placeholder="0000000-00.0000.0.00.0000"/></label><label>Tribunal<select value={tribunal} onChange={e=>setTribunal(e.target.value)}>{tribunals.map(([c,n])=><option value={c} key={c}>{c} — {n}</option>)}</select></label><button className="integration-action" onClick={consult} disabled={busy||!cnj.trim()}><Search size={15}/>{busy?'Consultando...':'Consultar agora'}</button></div>{notice&&<div className="integration-notice">{notice}</div>}</div>{result&&<><div className="cards"><div className="card"><Gavel size={18}/><strong>{result.numeroProcesso||cnj}</strong><span>Processo</span></div><div className="card"><Landmark size={18}/><strong>{result.tribunal||tribunal}</strong><span>Tribunal</span></div><div className="card"><Scale size={18}/><strong>{result.classe?.nome||result.classe?.codigo||'—'}</strong><span>Classe</span></div><div className="card"><CalendarDays size={18}/><strong>{fmt(result.dataAjuizamento)}</strong><span>Ajuizamento</span></div></div><div className="integration-panel"><h3><UserRound size={17}/> Dados do processo</h3><div className="signature-list"><div className="signature-row"><div><strong>Órgão julgador</strong><small>{result.orgaoJulgador?.nome||'—'}</small></div></div><div className="signature-row"><div><strong>Assuntos</strong><small>{(result.assuntos||[]).map((x:any)=>x.nome||x.codigo).filter(Boolean).join(' · ')||'—'}</small></div></div></div></div><div className="integration-panel"><h3><RefreshCw size={17}/> Andamentos encontrados</h3>{mov.length===0?<div className="integration-empty">Nenhum andamento público retornado.</div>:<div className="signature-list">{mov.map((m:any,i:number)=><div className="signature-row" key={i}><div><strong>{m.nome||m.descricao||`Movimento ${m.codigo||''}`}</strong><small>{fmt(m.dataHora||m.data)}</small></div></div>)}</div>}</div></>}</div>}
