import {useEffect,useMemo,useState} from 'react';
import {Search,Database,ShieldCheck,Play,RefreshCw,CheckCircle2,AlertTriangle} from 'lucide-react';
import {supabase} from '../lib/supabase';
import './integrations.css';
import './consultas.css';

type CatalogItem={slug:string;title:string;description:string;category:string;input_kind:string;provider_mode:string;novelty:boolean;sort_order:number};
type SearchResult={slug?:string;title?:string;status:string;source?:string;result?:any;error?:string;search_id?:string};
const label=(k:string)=>({phone:'Telefone',cpf:'CPF',cnpj:'CNPJ',cpf_cnpj:'CPF ou CNPJ',plate:'Placa',name_or_cpf:'Nome ou CPF',name_or_document:'Nome, CPF ou CNPJ'} as Record<string,string>)[k]||'Dado da consulta';
const status=(s:string)=>s==='completed'?'Concluída':s==='provider_required'?'Integração necessária':s==='not_applicable'?'Não aplicável':s==='failed'?'Falhou':s;
async function fnError(error:any){try{const body=await error?.context?.clone?.().json?.();return body?.error||body?.message||error?.message||'Falha na consulta.'}catch{return error?.message||'Falha na consulta.'}}

export default function Consultations(){
 const[catalog,setCatalog]=useState<CatalogItem[]>([]),[selected,setSelected]=useState<CatalogItem|null>(null),[query,setQuery]=useState(''),[category,setCategory]=useState('Todos'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[results,setResults]=useState<SearchResult[]>([]);
 useEffect(()=>{(async()=>{if(!supabase)return;const{data,error}=await supabase.functions.invoke('investigation-search',{body:{action:'catalog'}});if(!error&&Array.isArray(data?.catalog))setCatalog(data.catalog)})()},[]);
 const cats=useMemo(()=>['Todos',...Array.from(new Set(catalog.map(x=>x.category)))],[catalog]);
 const visible=useMemo(()=>catalog.filter(x=>category==='Todos'||x.category===category),[catalog,category]);
 function choose(item:CatalogItem){setSelected(item);setNotice('');setResults([]);setTimeout(()=>document.getElementById('investigation-run-box')?.scrollIntoView({behavior:'smooth',block:'center'}),0)}
 async function run(){if(!selected){setNotice('Selecione uma investigação primeiro.');return}if(!query.trim()){setNotice(`Informe ${label(selected.input_kind).toLowerCase()}.`);return}if(!supabase)return;setBusy(true);setNotice('');setResults([]);try{const{data,error}=await supabase.functions.invoke('investigation-search',{body:{action:'single',slug:selected.slug,query:query.trim()}});if(error)throw new Error(await fnError(error));if(data?.error)throw new Error(data.error);setResults([{slug:selected.slug,title:selected.title,status:data.status,source:data.source,result:data.result,search_id:data.search_id}]);setNotice(data.status==='provider_required'?'Esta investigação depende de integração oficial/autorizada.':'Pesquisa concluída e registrada.')}catch(e:any){setNotice(e?.message||'Falha na investigação.')}finally{setBusy(false)}}
 async function runBatch(){if(!query.trim()){setNotice('Informe o dado que deseja investigar.');return}if(!supabase)return;setBusy(true);setNotice('');setResults([]);try{const{data,error}=await supabase.functions.invoke('investigation-search',{body:{action:'batch',query:query.trim(),slugs:catalog.map(x=>x.slug)}});if(error)throw new Error(await fnError(error));if(data?.error)throw new Error(data.error);setResults(data.results||[]);const s=data.summary||{};setNotice(`${s.completed||0} concluída(s), ${s.provider_required||0} dependente(s) de integração, ${s.not_applicable||0} não aplicável(is), ${s.failed||0} falha(s).`)}catch(e:any){setNotice(e?.message||'Falha nas múltiplas consultas.')}finally{setBusy(false)}}
 return <div className="module investigation-page"><div className="page-head"><div><h1>Investigações</h1><p>Escolha a investigação, informe o dado e execute a consulta.</p></div></div><div className="system-bar"><span><ShieldCheck size={14}/> INVESTIGAÇÃO DE DADOS</span><span className="online">● FONTES AUTORIZADAS E AUDITÁVEIS</span></div>
 <div className="integration-panel"><label className="field investigation-main-field"><span>Dado a investigar</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome, CPF, CNPJ, telefone, placa ou CNJ"/></label><div className="investigation-tabs">{cats.map(c=><button type="button" key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div></div>
 <div className="investigation-grid"><button type="button" className="investigation-card" onClick={runBatch} disabled={busy}><div><strong>Múltiplas Consultas</strong><p>Executa automaticamente as consultas compatíveis com o dado informado.</p><small>{busy?'EXECUTANDO...':'PESQUISAR EM VÁRIAS FONTES'}</small></div></button>{visible.map(item=><button type="button" key={item.slug} aria-pressed={selected?.slug===item.slug} className={`investigation-card ${selected?.slug===item.slug?'selected':''}`} onClick={()=>choose(item)} disabled={busy}><div><strong>{item.title}</strong><p>{item.description}</p><small>{selected?.slug===item.slug?'✓ SELECIONADA':`${item.category} · CLIQUE PARA SELECIONAR`}</small></div></button>)}</div>
 {selected&&<div id="investigation-run-box" className="integration-panel investigation-form"><div className="integration-head"><div><span className="integration-pill">INVESTIGAÇÃO SELECIONADA</span><h2>{selected.title}</h2><p>{selected.description}</p></div></div><label className="field investigation-main-field"><span>{label(selected.input_kind)}</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Informe ${label(selected.input_kind).toLowerCase()}`} onKeyDown={e=>{if(e.key==='Enter')run()}}/></label><button className="primary investigation-run" onClick={run} disabled={busy}>{busy?<RefreshCw className="spin" size={16}/>:<Play size={16}/>} {busy?'Consultando...':'Pesquisar agora'}</button></div>}
 {notice&&<div className="integration-notice">{notice}</div>}{results.length>0&&<div className="integration-panel investigation-results"><h3><Database size={17}/> Resultado</h3><div className="signature-list">{results.map((x,i)=><div className="signature-row" key={`${x.slug||i}-${i}`}><div style={{width:'100%'}}><strong>{x.title||x.slug||'Consulta'}</strong><small>{status(x.status)} · {x.source||'fonte não informada'}</small>{x.error&&<p><AlertTriangle size={14}/> {x.error}</p>}{x.result?.message&&<p>{x.result.message}</p>}{x.result&&x.status==='completed'&&<pre style={{whiteSpace:'pre-wrap',wordBreak:'break-word',maxHeight:360,overflow:'auto'}}>{JSON.stringify(x.result,null,2)}</pre>}{x.status==='completed'&&<small><CheckCircle2 size={12}/> Consulta registrada no LEXOFFICE</small>}</div></div>)}</div></div>}</div>
}
