import {useEffect,useMemo,useState} from 'react';
import {Plus,Save,RefreshCw,UserRound,Phone,Mail} from 'lucide-react';
import {supabase} from '../lib/supabase';
import './crm.css';

const stages=[['novo_lead','Novo lead'],['contato_iniciado','Contato iniciado'],['qualificacao','Qualificação'],['consultoria','Consultoria'],['proposta','Proposta'],['negociacao','Negociação'],['contratado','Contratado'],['cliente','Cliente'],['perdido','Perdido']] as const;
const stageAgent:Record<string,string>={novo_lead:'Triagem',contato_iniciado:'Triagem',qualificacao:'Triagem / Comercial',consultoria:'Agenda / Comercial',proposta:'Comercial',negociacao:'Comercial',contratado:'Triagem pós-contrato',cliente:'Relacionamento / Processo',perdido:'Comercial — recuperação'};
type Lead={id:string;org_id:string;name:string;phone:string|null;whatsapp:string|null;email:string|null;origin:string;stage_key:string;potential_value:number|null;notes:string|null;created_at:string;updated_at:string};
type Draft={name:string;phone:string;email:string;origin:string;potential_value:string;notes:string};
const emptyDraft:Draft={name:'',phone:'',email:'',origin:'whatsapp',potential_value:'',notes:''};

export default function CRM(){
 const [leads,setLeads]=useState<Lead[]>([]),[orgId,setOrgId]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[showNew,setShowNew]=useState(false),[draft,setDraft]=useState<Draft>(emptyDraft),[editing,setEditing]=useState<Lead|null>(null);
 async function load(){if(!supabase)return;setLoading(true);setError('');const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const {data:p,error:pe}=await supabase.from('profiles').select('org_id').eq('id',user.id).maybeSingle();if(pe||!p?.org_id){setError(pe?.message||'Organização do usuário não encontrada.');setLoading(false);return}setOrgId(p.org_id);const {data,error:e}=await supabase.from('leads').select('id,org_id,name,phone,whatsapp,email,origin,stage_key,potential_value,notes,created_at,updated_at').eq('org_id',p.org_id).order('updated_at',{ascending:false});if(e)setError(e.message);else setLeads((data||[]) as Lead[]);setLoading(false)}
 useEffect(()=>{load();const id=setInterval(load,15000);return()=>clearInterval(id)},[]);
 const totalValue=useMemo(()=>leads.reduce((s,l)=>s+Number(l.potential_value||0),0),[leads]);
 async function createLead(){if(!supabase||!orgId||!draft.name.trim())return;setError('');const payload={org_id:orgId,name:draft.name.trim(),phone:draft.phone.trim()||null,whatsapp:draft.phone.trim()||null,email:draft.email.trim()||null,origin:draft.origin||'other',stage_key:'novo_lead',potential_value:draft.potential_value?Number(draft.potential_value):null,notes:draft.notes.trim()||null,updated_at:new Date().toISOString()};const {data,error:e}=await supabase.from('leads').insert(payload).select('*').single();if(e){setError(e.message);return}setLeads(v=>[data as Lead,...v]);setDraft(emptyDraft);setShowNew(false)}
 async function saveEdit(){if(!supabase||!editing)return;setError('');const payload={name:editing.name.trim(),phone:editing.phone?.trim()||null,whatsapp:editing.whatsapp?.trim()||editing.phone?.trim()||null,email:editing.email?.trim()||null,origin:editing.origin,potential_value:editing.potential_value,notes:editing.notes?.trim()||null,updated_at:new Date().toISOString()};const {data,error:e}=await supabase.from('leads').update(payload).eq('id',editing.id).select('*').single();if(e){setError(e.message);return}setLeads(v=>v.map(x=>x.id===editing.id?data as Lead:x));setEditing(null)}
 const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 return <div className="module crm-page">
  <div className="page-head"><div><h1>CRM</h1><p>Pipeline comercial integrado ao atendimento, WhatsApp e agentes de IA.</p></div><button className="integration-action" onClick={()=>setShowNew(v=>!v)}><Plus size={15}/>Novo lead</button></div>
  <div className="system-bar"><span>⚡ CRM + ROTEAMENTO DE AGENTES</span><span className="online">● PIPELINE AUTOMÁTICO</span></div>
  <div className="crm-ruler" aria-label="Etapas do pipeline">{stages.map(([key,label])=>{const count=leads.filter(l=>l.stage_key===key).length;return <div key={key} className={`crm-ruler-step ${count?'has-leads':''}`}>{label}<strong>{count}</strong></div>})}</div>
  <div className="crm-toolbar"><div className="crm-summary"><span className="crm-chip">{leads.length} leads</span><span className="crm-chip">Pipeline {money(totalValue)}</span><span className="crm-chip">Etapas atualizadas automaticamente pelos atendimentos e agentes</span></div><button className="integration-action" onClick={load} disabled={loading}><RefreshCw size={14}/>{loading?'Atualizando...':'Atualizar'}</button></div>
  {error&&<div className="crm-error">{error}</div>}
  {showNew&&<div className="integration-panel crm-editor"><h3><Plus size={16}/> Novo lead</h3><div className="integration-form"><label>Nome<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Telefone / WhatsApp<input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>E-mail<input value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>Origem<select value={draft.origin} onChange={e=>setDraft({...draft,origin:e.target.value})}><option value="whatsapp">WhatsApp</option><option value="instagram">Instagram</option><option value="website">Site</option><option value="google">Google</option><option value="referral">Indicação</option><option value="event">Evento</option><option value="other">Outro</option></select></label><label>Valor potencial<input type="number" step="0.01" value={draft.potential_value} onChange={e=>setDraft({...draft,potential_value:e.target.value})}/></label><label className="wide">Observações<textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="wide integration-notice">O lead entra em <b>Novo lead</b> e muda de etapa automaticamente conforme o atendimento evolui.</div><div className="crm-editor-actions"><button className="integration-action" onClick={createLead}><Save size={14}/>Salvar lead</button><button className="secondary" onClick={()=>{setShowNew(false);setDraft(emptyDraft)}}>Cancelar</button></div></div></div>}
  {editing&&<div className="integration-panel crm-editor"><h3><UserRound size={16}/> Editar lead</h3><div className="integration-form"><label>Nome<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Telefone<input value={editing.phone||''} onChange={e=>setEditing({...editing,phone:e.target.value})}/></label><label>WhatsApp<input value={editing.whatsapp||''} onChange={e=>setEditing({...editing,whatsapp:e.target.value})}/></label><label>E-mail<input value={editing.email||''} onChange={e=>setEditing({...editing,email:e.target.value})}/></label><label>Etapa atual<input value={stages.find(([k])=>k===editing.stage_key)?.[1]||editing.stage_key} disabled readOnly/></label><label>Valor potencial<input type="number" step="0.01" value={editing.potential_value??''} onChange={e=>setEditing({...editing,potential_value:e.target.value===''?null:Number(e.target.value)})}/></label><label className="wide">Observações<textarea value={editing.notes||''} onChange={e=>setEditing({...editing,notes:e.target.value})}/></label><div className="wide integration-notice">A etapa é controlada automaticamente pelo fluxo do atendimento e não é alterada manualmente.</div><div className="crm-editor-actions"><button className="integration-action" onClick={saveEdit}><Save size={14}/>Salvar alterações</button><button className="secondary" onClick={()=>setEditing(null)}>Cancelar</button></div></div></div>}
  <div className="crm-kanban">{stages.map(([key,label])=>{const rows=leads.filter(l=>l.stage_key===key);return <section className="crm-lane" key={key}><div className="crm-lane-head"><b>{label}</b><span>{rows.length}</span></div>{rows.length===0?<div className="crm-empty">Nenhum lead</div>:rows.map(l=><article className="crm-lead-card" key={l.id} onClick={()=>setEditing({...l})}><b>{l.name}</b>{(l.phone||l.whatsapp)&&<small><Phone size={10}/> {l.phone||l.whatsapp}</small>}{l.email&&<small><Mail size={10}/> {l.email}</small>}<small>Origem: {l.origin}</small>{l.potential_value!=null&&<strong>{money(l.potential_value)}</strong>}<small className="crm-agent">Agente: {stageAgent[l.stage_key]||'Triagem'}</small></article>)}</section>})}</div>
 </div>
}
