// @ts-nocheck
import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,ChevronRight,Plus,Wallet} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import './dashboard-reference.css';
import Afazeres from './Afazeres';
type Row=Record<string,any>;const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v||0);const ago=(v?:string)=>{if(!v)return'—';const m=Math.max(1,Math.round((Date.now()-new Date(v).getTime())/60000));return m<60?`há ${m} min`:m<1440?`há ${Math.round(m/60)} h`:`há ${Math.round(m/1440)} d`};
const norm=(v:any)=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const isHearing=(e:Row)=>{const type=norm(e?.event_type),title=norm(e?.title),desc=norm(e?.description);if(['audiencia','hearing','conciliacao','instrucao e julgamento','instrucao'].includes(type))return true;return /\baudiencia\b|\bconciliacao\b|\baudiencia de instrucao\b|\baij\b/.test(`${title} ${desc}`)};
export default function DashboardOverview(){const go=useNavigate(),[finance,setFinance]=useState<Row[]>([]),[events,setEvents]=useState<Row[]>([]),[firstName,setFirstName]=useState(''),[loaded,setLoaded]=useState(false);
useEffect(()=>{(async()=>{if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:p}=await supabase.from('profiles').select('org_id,name').eq('id',user.id).maybeSingle();if(p?.name)setFirstName(String(p.name).trim().split(/\s+/)[0]);if(!p?.org_id)return;const org=p.org_id;const[f,e]=await Promise.all([supabase.from('financial_entries').select('type,amount,status,paid_at').eq('org_id',org).eq('type','income').limit(1500),supabase.from('calendar_events').select('id,title,description,starts_at,location,event_type').eq('org_id',org).gte('starts_at',new Date().toISOString()).neq('status','cancelled').order('starts_at').limit(50)]);setFinance(f.data||[]);setEvents((e.data||[]).filter(isHearing).slice(0,4));setLoaded(true)})().catch(console.error)},[]);
const due=useMemo(()=>finance.reduce((a,x)=>x.type==='income'&&x.status!=='paid'&&!x.paid_at?a+(Number(x.amount)||0):a,0),[finance]);const h=new Date().getHours();const greet=h<12?'Bom dia':h<18?'Boa tarde':'Boa noite';const today=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'});const name=firstName?(/^suzanne$/i.test(firstName)?'Dra. Suzanne':firstName):'';
return <div className="dash-essential"><header className="de-head"><div><h1>{greet}{name?`, ${name}`:''}</h1><p>{today.charAt(0).toUpperCase()+today.slice(1)}</p></div><button type="button" className="de-new" onClick={()=>go('/atendimento')}><Plus size={16}/> Novo atendimento</button></header><section className="de-block" aria-labelledby="de-hoje"><div className="de-title"><h2 id="de-hoje">Hoje</h2><button type="button" onClick={()=>go('/afazeres')}>Ver todos os afazeres <ChevronRight size={15}/></button></div><Afazeres embedded/></section><section className="de-block" aria-labelledby="de-aud"><div className="de-title"><h2 id="de-aud">Próximas audiências</h2><button type="button" onClick={()=>go('/agenda')}>Abrir agenda <ChevronRight size={15}/></button></div>{events.length?<ul className="de-events">{events.map(e=>{const d=new Date(e.starts_at);return <li key={e.id}><button type="button" onClick={()=>go('/agenda')}><time><b>{d.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')}</b>{d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</time><span className="de-ev-body"><b>{e.title}</b><small>{e.location||e.description||'Audiência'}</small></span><span className="de-hour">{d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</span></button></li>})}</ul>:<p className="de-empty"><CalendarDays size={16}/> {loaded?'Nenhuma audiência marcada.':'Carregando...'}</p>}</section><section className="de-block de-money" aria-labelledby="de-rec"><div className="de-title"><h2 id="de-rec">A receber</h2><button type="button" onClick={()=>go('/financeiro')}>Abrir financeiro <ChevronRight size={15}/></button></div><p className="de-amount"><Wallet size={20}/>{brl(due)}</p></section></div>}
