import { useEffect,useMemo,useState } from 'react';
import { FileText,Plus,RefreshCw,UserRound,Scale } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './integrations.css';

type Template={id:string;name:string;category?:string|null;description?:string|null;variables?:any};
type Doc={id:string;title:string;status:string;created_at:string;template_id?:string|null;client_id?:string|null;process_id?:string|null};
type Client={id:string;name:string;cpf_cnpj?:string|null;rg?:string|null;birth_date?:string|null;marital_status?:string|null;profession?:string|null;address?:any;phone?:string|null;whatsapp?:string|null;email?:string|null};
type Process={id:string;client_id?:string|null;cnj_number?:string|null;internal_number?:string|null;opposing_party?:string|null;pole?:string|null;court?:string|null;comarca?:string|null;vara?:string|null;area?:string|null;subject?:string|null;class_name?:string|null;status?:string|null};

function addressText(a:any){if(!a)return '';if(typeof a==='string')return a;return [a.street||a.logradouro,a.number||a.numero,a.complement||a.complemento,a.neighborhood||a.bairro,a.city||a.cidade,a.state||a.uf,a.zip||a.cep].filter(Boolean).join(', ')}

export default function Documents(){
 const [templates,setTemplates]=useState<Template[]>([]),[docs,setDocs]=useState<Doc[]>([]),[clients,setClients]=useState<Client[]>([]),[processes,setProcesses]=useState<Process[]>([]),[templateId,setTemplateId]=useState(''),[clientId,setClientId]=useState(''),[processId,setProcessId]=useState(''),[title,setTitle]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){if(!supabase)return;const [{data:t},{data:d},{data:c},{data:p}]=await Promise.all([supabase.from('document_templates').select('id,name,category,description,variables').eq('active',true).order('name'),supabase.from('generated_documents').select('id,title,status,created_at,template_id,client_id,process_id').order('created_at',{ascending:false}).limit(30),supabase.from('clients').select('id,name,cpf_cnpj,rg,birth_date,marital_status,profession,address,phone,whatsapp,email').order('name').limit(1000),supabase.from('processes').select('id,client_id,cnj_number,internal_number,opposing_party,pole,court,comarca,vara,area,subject,class_name,status').order('updated_at',{ascending:false}).limit(1000)]);setTemplates((t||[]) as Template[]);setDocs((d||[]) as Doc[]);setClients((c||[]) as Client[]);setProcesses((p||[]) as Process[]);if(!templateId&&t?.[0]?.id)setTemplateId(t[0].id)}useEffect(()=>{load()},[]);
 const client=useMemo(()=>clients.find(c=>c.id===clientId),[clients,clientId]);
 const availableProcesses=useMemo(()=>clientId?processes.filter(p=>p.client_id===clientId):processes,[processes,clientId]);
 const process=useMemo(()=>processes.find(p=>p.id===processId),[processes,processId]);
 useEffect(()=>{if(clientId&&processId&&!availableProcesses.some(p=>p.id===processId))setProcessId('')},[clientId]);
 useEffect(()=>{if(!title&&client){const template=templates.find(t=>t.id===templateId);setTitle(`${template?.name||'Documento'} - ${client.name}`)}},[clientId,templateId]);
 function variables(){return {cliente_nome:client?.name||'',cliente_cpf_cnpj:client?.cpf_cnpj||'',cliente_rg:client?.rg||'',cliente_nascimento:client?.birth_date||'',cliente_estado_civil:client?.marital_status||'',cliente_profissao:client?.profession||'',cliente_endereco:addressText(client?.address),cliente_telefone:client?.phone||'',cliente_whatsapp:client?.whatsapp||'',cliente_email:client?.email||'',processo_numero:process?.cnj_number||'',processo_numero_interno:process?.internal_number||'',processo_parte_contraria:process?.opposing_party||'',processo_polo:process?.pole||'',processo_tribunal:process?.court||'',processo_comarca:process?.comarca||'',processo_vara:process?.vara||'',processo_area:process?.area||'',processo_assunto:process?.subject||'',processo_classe:process?.class_name||'',processo_status:process?.status||''}}
 async function create(){if(!supabase||!title.trim()||!clientId)return;setBusy(true);setNotice('');try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão expirada.');const {data:p,error:pe}=await supabase.from('profiles').select('org_id').eq('id',user.id).single();if(pe||!p?.org_id)throw pe||new Error('Organização não encontrada.');const payload={org_id:p.org_id,template_id:templateId||null,client_id:clientId,process_id:processId||null,title:title.trim(),variables:variables(),created_by:user.id};const {data,error}=await supabase.functions.invoke('document-generate',{body:payload});if(error)throw error;if((data as any)?.error)throw new Error((data as any).error);setNotice('Documento criado com os dados do cliente preenchidos automaticamente.');setTitle('');await load()}catch(e:any){setNotice(e?.message||'Falha ao criar documento.')}finally{setBusy(false)}}
 return <><div className="page-title"><h1>Documentos</h1><p>Modelos com preenchimento automático pelos dados cadastrados do cliente e do processo.</p></div><div className="integration-head"><div><span className="integration-pill"><FileText size={14}/> DOCUMENTOS INTELIGENTES</span><h2>Gerar documento preenchido</h2><p>Selecione o cliente e, se desejar, o processo. O LEXOFFICE leva os dados cadastrados automaticamente para o documento.</p></div><button className="integration-action" onClick={load}><RefreshCw size={16}/>Atualizar</button></div>{notice&&<div className="integration-notice">{notice}</div>}<div className="integration-panel"><div className="document-auto-grid"><label><UserRound size={15}/> Cliente<select value={clientId} onChange={e=>{setClientId(e.target.value);setTitle('')}}><option value="">Selecione o cliente</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}{c.cpf_cnpj?` — ${c.cpf_cnpj}`:''}</option>)}</select></label><label><Scale size={15}/> Processo<select value={processId} onChange={e=>setProcessId(e.target.value)}><option value="">Sem processo vinculado</option>{availableProcesses.map(p=><option value={p.id} key={p.id}>{p.cnj_number||p.internal_number||p.subject||'Processo'}</option>)}</select></label><label>Modelo<select value={templateId} onChange={e=>{setTemplateId(e.target.value);setTitle('')}}><option value="">Sem modelo</option>{templates.map(t=><option value={t.id} key={t.id}>{t.name}{t.category?` — ${t.category}`:''}</option>)}</select></label><label>Título<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Título do documento"/></label></div>{client&&<div className="autofill-preview"><strong>Dados que serão preenchidos automaticamente</strong><div><span>Nome: {client.name}</span><span>CPF/CNPJ: {client.cpf_cnpj||'—'}</span><span>RG: {client.rg||'—'}</span><span>Profissão: {client.profession||'—'}</span><span>Estado civil: {client.marital_status||'—'}</span><span>Telefone: {client.phone||client.whatsapp||'—'}</span><span>E-mail: {client.email||'—'}</span><span>Endereço: {addressText(client.address)||'—'}</span>{process&&<><span>Processo: {process.cnj_number||'—'}</span><span>Vara: {process.vara||'—'}</span><span>Comarca: {process.comarca||'—'}</span><span>Parte contrária: {process.opposing_party||'—'}</span></>}</div></div>}<button className="integration-action document-create" onClick={create} disabled={busy||!title.trim()||!clientId}><Plus size={16}/>{busy?'Gerando...':'Gerar documento preenchido'}</button></div><div className="integration-panel"><h3>Documentos recentes</h3>{docs.length===0?<div className="integration-empty"><FileText size={28}/><p>Nenhum documento gerado.</p></div>:<div className="signature-list">{docs.map(d=><div className="signature-row" key={d.id}><div><strong>{d.title}</strong><small>{new Date(d.created_at).toLocaleString('pt-BR')}</small></div><span className="status-dot">{d.status}</span></div>)}</div>}</div></>}
