import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {CalendarDays,Clock3,RefreshCw,Sparkles,Wallet,FileText} from 'lucide-react';
import {supabase} from '../lib/supabase';
type Item={id:string;title:string;when:string;detail?:string;process_id?:string|null};
type Brief={events:Item[];hearings:Item[];deadlines:Item[];finance:{count:number,total:number};updated:string;org_id:string};
const dt=(s:string)=>new Date(s).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n);
export default function Donna(){
 const [data,setData]=useState<Brief|null>(null),[busy,setBusy]=useState(false),[aiBusy,setAiBusy]=useState(false),[error,setError]=useState(''),[brief,setBrief]=useState('');
 async function load(){if(!supabase){setError('Serviço de dados indisponível.');return;}setBusy(true);setError('');try{
 const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Acesso não autenticado.');const {data:p,error:e}=await supabase.from('profiles').select('org_id').eq('id',user.id).maybeSingle();if(e||!p?.org_id)throw new Error('Escritório não identificado.');
 const now=new Date(),end=new Date(now.getTime()+7*86400000),start=new Date(now.getFullYear(),now.getMonth(),now.getDate());const from=start.toISOString(),to=end.toISOString();
 const [a,h,d,f]=await Promise.all([
 supabase.from('calendar_events').select('id,title,description,starts_at,process_id').eq('org_id',p.org_id).gte('starts_at',from).lte('starts_at',to).order('starts_at',{ascending:true}).limit(40),
 supabase.from('process_hearings').select('id,title,hearing_type,starts_at,process_id').eq('org_id',p.org_id).gte('starts_at',from).lte('starts_at',to).order('starts_at',{ascending:true}).limit(40),
 supabase.from('process_deadlines').select('id,title,description,due_at,status,process_id').eq('org_id',p.org_id).lte('due_at',to).not('status','in','(completed,concluido,done,cancelled,cancelado)').order('due_at',{ascending:true}).limit(60),
 supabase.from('financial_entries').select('amount,status,type').eq('org_id',p.org_id).eq('type','income').in('status',['pending','overdue']).limit(1000)
 ]);for(const result of [a,h,d,f])if(result.error)throw result.error;
 const events=(a.data||[]).map((x:any)=>({id:x.id,title:x.title||'Compromisso',when:x.starts_at,detail:x.description,process_id:x.process_id}));
 const hearings=(h.data||[]).map((x:any)=>({id:x.id,title:x.title||x.hearing_type||'Audiência',when:x.starts_at,process_id:x.process_id}));
 const deadlines=(d.data||[]).map((x:any)=>({id:x.id,title:x.title||'Prazo',when:x.due_at,detail:x.description,process_id:x.process_id}));
 const amounts=(f.data||[]).map((x:any)=>Number(x.amount)||0);setData({events,hearings,deadlines,finance:{count:amounts.length,total:amounts.reduce((a:number,b:number)=>a+b,0)},updated:new Date().toISOString(),org_id:p.org_id});
 }catch(e:any){setError(e?.message||'Falha ao consultar o escritório.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function generate(){if(!data||!supabase)return;setAiBusy(true);setError('');try{const {org_id,...source}=data;const r=await supabase.functions.invoke('ai-provider-gateway',{body:{org_id,purpose:'executive_briefing',instructions:'Você é Donna, secretária executiva do escritório. Prepare um briefing PRIVADO para a titular, em português objetivo, elegante e altamente prático. Utilize exclusivamente os registros fornecidos, sem criar fatos ou afirmar que prazos e agendas estão completos. Estruture: AGENDA DOS PRÓXIMOS 7 DIAS; AUDIÊNCIAS E PREPARAÇÃO; PRAZOS E PRIORIDADES (inclua vencidos quando houver); HONORÁRIOS PENDENTES (apenas total e quantidade); AÇÕES PRIORITÁRIAS; LIMITAÇÕES DOS DADOS. Não invente prazos, nomes, reuniões ou providências. Não interprete ausência de registros como ausência definitiva de compromissos. Não inclua conteúdo sensível em canais externos. Não afirme que enviou notificações.',input:JSON.stringify(source)}});if(r.error||!r.data?.ok||!r.data?.text)throw r.error||new Error(r.data?.error||'O briefing não pôde ser gerado.');setBrief(String(r.data.text));}catch(e:any){setError(e?.message||'Falha ao gerar briefing.')}finally{setAiBusy(false)}}
 const section=(title:string,items:Item[],href:string)=><section style={{border:'1px solid #7775',borderRadius:14,padding:16,display:'grid',gap:10}}><h2 style={{fontSize:18,margin:0}}>{title} ({items.length})</h2>{!items.length?<p style={{margin:0,opacity:.7}}>Nenhum registro retornado para o período consultado.</p>:items.slice(0,12).map(x=><div key={x.id} style={{borderTop:'1px solid #7773',paddingTop:9,display:'grid',gap:3}}><strong>{x.title}</strong><small>{dt(x.when)}</small>{x.process_id&&<Link to={'/conducao-processual?processo='+encodeURIComponent(x.process_id)} style={{color:'#c9a44c'}}>Ver processo</Link>}</div>)}<Link to={href} style={{color:'#c9a44c'}}>Abrir módulo</Link></section>;
 return <div style={{maxWidth:1240,margin:'auto',padding:'22px 16px',display:'grid',gap:20}}><header style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'center',flexWrap:'wrap'}}><div><h1 style={{margin:0,display:'flex',alignItems:'center',gap:8}}><Sparkles color="#c9a44c"/> Donna · Secretária Executiva</h1><p style={{opacity:.8}}>Seu briefing privado: agenda, prazos, audiências e prioridades do escritório.</p></div><button onClick={()=>void load()} disabled={busy} style={{padding:'10px 16px',border:'1px solid #c9a44c',borderRadius:9,background:'transparent',color:'inherit'}}><RefreshCw size={16} style={{verticalAlign:'middle'}}/> {busy?'Consultando...':'Atualizar'}</button></header>{error&&<p role="alert" style={{color:'#e88a83'}}>{error}</p>}
 {data&&<><p style={{fontSize:13,opacity:.7,margin:0}}>Dados consultados em {dt(data.updated)}. Agenda para os próximos sete dias; prazos abertos até esse horizonte, inclusive vencidos; valores pendentes registrados.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12}}>{[[CalendarDays,'Compromissos',data.events.length],[CalendarDays,'Audiências',data.hearings.length],[Clock3,'Prazos',data.deadlines.length],[Wallet,'Valores pendentes',money(data.finance.total)]].map(([Icon,label,value],i)=><div key={i} style={{border:'1px solid #c9a44c',padding:16,borderRadius:12}}><strong style={{display:'block',fontSize:23}}>{String(value)}</strong><span>{String(label)}</span></div>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(270px,1fr))',gap:13}}>{section('Compromissos',data.events,'/agenda')}{section('Audiências',data.hearings,'/audiencias')}{section('Prazos abertos e vencidos',data.deadlines,'/conducao-processual')}</div><div style={{border:'1px solid #c9a44c',borderRadius:14,padding:20,display:'grid',gap:12}}><h2 style={{margin:0}}>Briefing executivo da Donna</h2><p style={{margin:0}}>Gere uma síntese estratégica para sua leitura. Nenhuma mensagem é enviada automaticamente.</p><button disabled={aiBusy} onClick={()=>void generate()} style={{padding:'12px 18px',borderRadius:9,border:'none',background:'#c9a44c',color:'#17130c',width:'fit-content',cursor:'pointer'}}><Sparkles size={16} style={{verticalAlign:'middle'}}/> {aiBusy?'Donna está preparando...':'Gerar briefing executivo'}</button>{brief&&<><button onClick={()=>navigator.clipboard.writeText(brief)} style={{width:'fit-content',borderRadius:8,padding:8}}>Copiar briefing</button><pre style={{fontFamily:'inherit',whiteSpace:'pre-wrap',lineHeight:1.7,overflowWrap:'anywhere'}}>{brief}</pre></>}</div><p style={{fontSize:13,opacity:.7}}>A entrega automática diária por WhatsApp ainda não foi ativada: requer confirmação do canal, destinatário e teste de recebimento.</p></>}
 </div>;
}