import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {CalendarDays,FileText,Scale,RefreshCw,ClipboardList,ExternalLink} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Hearing={id:string;process_id:string|null;title:string|null;hearing_type:string|null;starts_at:string;location:string|null;meeting_url:string|null;notes:string|null;status:string|null};
type Process={id:string;cnj_number:string|null;internal_number:string|null;subject:string|null;clients?:{name:string}|{name:string}[]|null};
const dateText=(s:string)=>new Date(s).toLocaleString('pt-BR',{dateStyle:'full',timeStyle:'short'});
const caseClient=(p?:Process)=>Array.isArray(p?.clients)?p?.clients[0]?.name:p?.clients?.name;
export default function Hearings(){
 const [items,setItems]=useState<Hearing[]>([]),[processes,setProcesses]=useState<Record<string,Process>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState<'upcoming'|'all'>('upcoming'),[selected,setSelected]=useState<string|null>(null);
 async function load(){if(!supabase){setLoading(false);setError('Integração de dados indisponível.');return;}setLoading(true);setError('');const {data:{user}}=await supabase.auth.getUser();if(!user){setError('Entre na conta para consultar as audiências.');setLoading(false);return;}const {data:profile,error:profileError}=await supabase.from('profiles').select('org_id').eq('id',user.id).maybeSingle();if(profileError||!profile?.org_id){setError('Não foi possível identificar o escritório.');setLoading(false);return;}const [h,p]=await Promise.all([supabase.from('process_hearings').select('id,process_id,title,hearing_type,starts_at,location,meeting_url,notes,status').eq('org_id',profile.org_id).order('starts_at',{ascending:true}).limit(500),supabase.from('processes').select('id,cnj_number,internal_number,subject,clients(name)').eq('org_id',profile.org_id).limit(1000)]);if(h.error||p.error){setError(h.error?.message||p.error?.message||'Falha ao carregar audiências.');setLoading(false);return;}setItems((h.data||[]) as Hearing[]);setProcesses(Object.fromEntries(((p.data||[]) as unknown as Process[]).map(x=>[x.id,x])));setLoading(false);}
 useEffect(()=>{void load()},[]);
 const today=Date.now();const upcoming=useMemo(()=>items.filter(h=>new Date(h.starts_at).getTime()>=today&&!['cancelada','cancelado','canceled','cancelled'].includes((h.status||'').toLowerCase())),[items,today]);const visible=filter==='upcoming'?upcoming:items;const chosen=items.find(h=>h.id===selected);
 const checklist=['Conferir petição inicial, contestação e decisões','Identificar fatos controvertidos e ônus da prova','Revisar documentos e possíveis contradições','Conferir rol e disponibilidade de testemunhas','Preparar perguntas para partes e testemunhas','Verificar poderes para acordo e limites autorizados','Confirmar endereço/link, horário, documentos e equipamentos'];
 return <div style={{padding:'20px 16px',maxWidth:1250,margin:'0 auto',display:'grid',gap:18}}>
  <header style={{display:'flex',alignItems:'flex-start',justifyContent:'space-between',gap:14,flexWrap:'wrap'}}><div><div style={{display:'flex',gap:9,alignItems:'center',color:'#c9a44c'}}><CalendarDays size={25}/><h1 style={{margin:0}}>Audiências</h1></div><p style={{margin:'9px 0 0',opacity:.8}}>Pauta do escritório e preparação estratégica para atuação em audiência.</p></div><button onClick={()=>void load()} disabled={loading} style={{padding:'10px 16px',borderRadius:9,border:'1px solid #c9a44c',background:'transparent',color:'inherit',cursor:'pointer'}}><RefreshCw size={15} style={{verticalAlign:'middle'}}/> Atualizar</button></header>
  <div style={{display:'flex',gap:12,flexWrap:'wrap'}}><div style={{border:'1px solid #c9a44c',borderRadius:12,padding:'15px 20px',minWidth:160}}><strong style={{fontSize:26}}>{upcoming.length}</strong><div>Próximas audiências</div></div><div style={{border:'1px solid #7775',borderRadius:12,padding:'15px 20px',minWidth:160}}><strong style={{fontSize:26}}>{items.length}</strong><div>Audiências cadastradas</div></div></div>
  <div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button onClick={()=>setFilter('upcoming')} aria-pressed={filter==='upcoming'} style={{padding:'10px 14px',borderRadius:8,background:filter==='upcoming'?'#c9a44c':'transparent',color:filter==='upcoming'?'#17130c':'inherit',border:'1px solid #c9a44c'}}>Próximas</button><button onClick={()=>setFilter('all')} aria-pressed={filter==='all'} style={{padding:'10px 14px',borderRadius:8,background:filter==='all'?'#c9a44c':'transparent',color:filter==='all'?'#17130c':'inherit',border:'1px solid #c9a44c'}}>Todas</button></div>
  {error&&<p role="alert" style={{color:'#ed857e'}}>{error}</p>}{loading?<p>Carregando audiências...</p>:visible.length===0?<section style={{padding:20,border:'1px solid #7775',borderRadius:12}}>Nenhuma audiência encontrada para este filtro. Consulte também <Link to="/agenda">Agenda</Link> ou a aba Audiências da ficha do processo.</section>:
  <div style={{display:'grid',gap:12}}>{visible.map(h=>{const p=h.process_id?processes[h.process_id]:undefined;return <article key={h.id} style={{border:'1px solid #7776',borderRadius:12,padding:16,display:'grid',gap:9}}>
   <strong style={{fontSize:18}}>{h.title||h.hearing_type||'Audiência'}</strong><div><CalendarDays size={16} style={{verticalAlign:'middle'}}/> {dateText(h.starts_at)}</div><div>{caseClient(p)||'Cliente não identificado'} · {p?.cnj_number||p?.internal_number||'Processo não vinculado'}</div>{h.location&&<div>Local: {h.location}</div>}{h.status&&<small>Situação: {h.status}</small>}
   <div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button onClick={()=>setSelected(selected===h.id?null:h.id)} style={{border:'1px solid #c9a44c',borderRadius:8,background:'#c9a44c',color:'#17130c',padding:'9px 12px',cursor:'pointer'}}><ClipboardList size={15} style={{verticalAlign:'middle'}}/> {selected===h.id?'Fechar preparação':'Preparar audiência'}</button>{h.process_id&&<Link to={'/conducao-processual?processo='+encodeURIComponent(h.process_id)} style={{padding:'9px 12px',border:'1px solid #c9a44c',borderRadius:8,color:'inherit'}}><Scale size={15} style={{verticalAlign:'middle'}}/> Análise do juízo</Link>}{h.process_id&&<Link to={'/dossie/'+h.process_id} style={{padding:'9px 12px',border:'1px solid #7776',borderRadius:8,color:'inherit'}}><FileText size={15} style={{verticalAlign:'middle'}}/> Dossiê do processo</Link>}{h.meeting_url&&/^https:\/\//i.test(h.meeting_url)&&<a href={h.meeting_url} target="_blank" rel="noopener noreferrer" style={{padding:'9px 12px',border:'1px solid #7776',borderRadius:8,color:'inherit'}}><ExternalLink size={15} style={{verticalAlign:'middle'}}/> Link da audiência</a>}</div>
   {chosen?.id===h.id&&<section style={{padding:15,borderRadius:10,background:'rgba(201,164,76,.07)',border:'1px solid #c9a44c'}}><h3 style={{marginTop:0}}>Preparação estratégica · checklist</h3><p>Confira os autos e marque os itens antes da audiência. O roteiro de perguntas personalizado ainda depende de implementação e revisão jurídica.</p><div style={{display:'grid',gap:9}}>{checklist.map((c,i)=><label key={i} style={{display:'flex',gap:9,alignItems:'flex-start'}}><input type="checkbox"/> {c}</label>)}</div>{h.notes&&<p><strong>Observações cadastradas:</strong> {h.notes}</p>}</section>}
  </article>})}</div>}
 </div>;
}