import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {CalendarDays,FileText,Scale,RefreshCw,ClipboardList,ExternalLink} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Hearing={id:string;process_id:string|null;title:string|null;hearing_type:string|null;starts_at:string;location:string|null;meeting_url:string|null;notes:string|null;status:string|null};
type Process={id:string;cnj_number:string|null;internal_number:string|null;subject:string|null;clients?:{name:string}|{name:string}[]|null};
const dateText=(s:string)=>new Date(s).toLocaleString('pt-BR',{dateStyle:'full',timeStyle:'short'});
const caseClient=(p?:Process)=>Array.isArray(p?.clients)?p?.clients[0]?.name:p?.clients?.name;
export default function Hearings(){
 const [orgId,setOrgId]=useState(''),[briefs,setBriefs]=useState<Record<string,string>>({}),[generating,setGenerating]=useState<string|null>(null),[briefError,setBriefError]=useState('');
 const [items,setItems]=useState<Hearing[]>([]),[processes,setProcesses]=useState<Record<string,Process>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState<'upcoming'|'all'>('upcoming'),[selected,setSelected]=useState<string|null>(null);
 async function load(){if(!supabase){setLoading(false);setError('Integração de dados indisponível.');return;}setLoading(true);setError('');const {data:{user}}=await supabase.auth.getUser();if(!user){setError('Entre na conta para consultar as audiências.');setLoading(false);return;}const {data:profile,error:profileError}=await supabase.from('profiles').select('org_id').eq('id',user.id).maybeSingle();if(profileError||!profile?.org_id){setError('Não foi possível identificar o escritório.');setLoading(false);return;}setOrgId(profile.org_id);const [h,p]=await Promise.all([supabase.from('process_hearings').select('id,process_id,title,hearing_type,starts_at,location,meeting_url,notes,status').eq('org_id',profile.org_id).order('starts_at',{ascending:true}).limit(500),supabase.from('processes').select('id,cnj_number,internal_number,subject,clients(name)').eq('org_id',profile.org_id).limit(1000)]);if(h.error||p.error){setError(h.error?.message||p.error?.message||'Falha ao carregar audiências.');setLoading(false);return;}setItems((h.data||[]) as Hearing[]);setProcesses(Object.fromEntries(((p.data||[]) as unknown as Process[]).map(x=>[x.id,x])));setLoading(false);}
 useEffect(()=>{void load()},[]);
 const today=Date.now();const upcoming=useMemo(()=>items.filter(h=>new Date(h.starts_at).getTime()>=today&&!['cancelada','cancelado','canceled','cancelled'].includes((h.status||'').toLowerCase())),[items,today]);const visible=filter==='upcoming'?upcoming:items;const chosen=items.find(h=>h.id===selected);
 async function generateBrief(h:Hearing){if(!supabase||!h.process_id||!orgId){setBriefError('Vincule a audiência a um processo antes de gerar o dossiê.');return;}setGenerating(h.id);setBriefError('');try{
 const [pr,m,d,j,docs]=await Promise.all([
  supabase.from('processes').select('cnj_number,internal_number,subject,area,vara,comarca,court,opposing_party,class_name,clients(name)').eq('id',h.process_id).eq('org_id',orgId).maybeSingle(),
  supabase.from('process_movements').select('movement_date,title,description').eq('process_id',h.process_id).order('movement_date',{ascending:false}).limit(35),
  supabase.from('process_deadlines').select('title,due_at,status,description').eq('process_id',h.process_id).order('due_at',{ascending:true}).limit(30),
  supabase.from('process_judge_analyses').select('result,created_at,sample_size').eq('process_id',h.process_id).order('created_at',{ascending:false}).limit(1).maybeSingle(),
  supabase.from('documents').select('name,category,created_at').eq('process_id',h.process_id).order('created_at',{ascending:false}).limit(80)
 ]);
 const errors=[pr,m,d,j,docs].map(x=>x.error).filter(Boolean);if(errors.length)throw errors[0];if(!pr.data)throw new Error('Processo não encontrado ou sem acesso.');
 const source={audiencia:{data:h.starts_at,tipo:h.hearing_type,titulo:h.title,local:h.location,observacoes:h.notes},processo:pr.data,andamentos:m.data||[],prazos:d.data||[],perfil_do_juizo:j.data?.result||null,amostra_perfil_juizo:j.data?.sample_size||null,documentos_disponiveis_apenas_metadados:docs.data||[]};
 const result=await supabase.functions.invoke('ai-provider-gateway',{body:{org_id:orgId,purpose:'process_dossier',instructions:'Você prepara um Dossiê Estratégico de Audiência para revisão exclusiva da advogada. Use SOMENTE os dados fornecidos. Não afirme ter lido o conteúdo de documentos quando apenas nomes/metadados estão disponíveis. Não invente depoimentos, provas, pedidos, decisões, comportamento do magistrado ou jurisprudência. Responda em português jurídico, estruturado com seções: 1. Identificação e logística; 2. Síntese do processo e cronologia; 3. Pontos controvertidos confirmados e pontos a conferir nos autos; 4. Provas favoráveis e contrárias efetivamente identificáveis; 5. Contradições identificadas com referência ao dado de origem; 6. Perfil do juízo (distinguir observação estatística de fato e informar limites da amostra); 7. Perguntas SUGERIDAS para partes e testemunhas, condicionadas à confirmação dos fatos e da pertinência; 8. Estratégia e riscos a conferir; 9. Acordo: critérios e limites a validar, sem inventar valores; 10. Checklist de véspera e dia. Em cada seção com dados insuficientes, registrar expressamente Não identificado nos dados disponíveis e quais documentos faltam. Não prometer resultado. Não criar perguntas que pressuponham fatos não comprovados.',input:JSON.stringify(source)}});
 if(result.error||!result.data?.ok||!result.data?.text)throw result.error||new Error(result.data?.error||'A IA não retornou o dossiê.');setBriefs(prev=>({...prev,[h.id]:String(result.data.text)}));setSelected(h.id);
 }catch(e:any){setBriefError(e?.message||'Erro ao preparar dossiê.')}finally{setGenerating(null)}}
 function downloadBrief(h:Hearing){const content=briefs[h.id];if(!content)return;const blob=new Blob([content],{type:'text/plain;charset=utf-8'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download='dossie-audiencia-'+h.starts_at.slice(0,10)+'.txt';a.click();URL.revokeObjectURL(u);}
 const checklist=['Conferir petição inicial, contestação e decisões','Identificar fatos controvertidos e ônus da prova','Revisar documentos e possíveis contradições','Conferir rol e disponibilidade de testemunhas','Preparar perguntas para partes e testemunhas','Verificar poderes para acordo e limites autorizados','Confirmar endereço/link, horário, documentos e equipamentos'];
 return <div style={{padding:'20px 16px',maxWidth:1250,margin:'0 auto',display:'grid',gap:18}}>
  <header style={{display:'flex',alignItems:'flex-start',justifyContent:'space-between',gap:14,flexWrap:'wrap'}}><div><div style={{display:'flex',gap:9,alignItems:'center',color:'#c9a44c'}}><CalendarDays size={25}/><h1 style={{margin:0}}>Audiências</h1></div><p style={{margin:'9px 0 0',opacity:.8}}>Pauta do escritório e preparação estratégica para atuação em audiência.</p></div><button onClick={()=>void load()} disabled={loading} style={{padding:'10px 16px',borderRadius:9,border:'1px solid #c9a44c',background:'transparent',color:'inherit',cursor:'pointer'}}><RefreshCw size={15} style={{verticalAlign:'middle'}}/> Atualizar</button></header>
  <div style={{display:'flex',gap:12,flexWrap:'wrap'}}><div style={{border:'1px solid #c9a44c',borderRadius:12,padding:'15px 20px',minWidth:160}}><strong style={{fontSize:26}}>{upcoming.length}</strong><div>Próximas audiências</div></div><div style={{border:'1px solid #7775',borderRadius:12,padding:'15px 20px',minWidth:160}}><strong style={{fontSize:26}}>{items.length}</strong><div>Audiências cadastradas</div></div></div>
  <div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button onClick={()=>setFilter('upcoming')} aria-pressed={filter==='upcoming'} style={{padding:'10px 14px',borderRadius:8,background:filter==='upcoming'?'#c9a44c':'transparent',color:filter==='upcoming'?'#17130c':'inherit',border:'1px solid #c9a44c'}}>Próximas</button><button onClick={()=>setFilter('all')} aria-pressed={filter==='all'} style={{padding:'10px 14px',borderRadius:8,background:filter==='all'?'#c9a44c':'transparent',color:filter==='all'?'#17130c':'inherit',border:'1px solid #c9a44c'}}>Todas</button></div>
  {error&&<p role="alert" style={{color:'#ed857e'}}>{error}</p>}{briefError&&<p role="alert" style={{color:'#ed857e'}}>{briefError}</p>}{loading?<p>Carregando audiências...</p>:visible.length===0?<section style={{padding:20,border:'1px solid #7775',borderRadius:12}}>Nenhuma audiência encontrada para este filtro. Consulte também <Link to="/agenda">Agenda</Link> ou a aba Audiências da ficha do processo.</section>:
  <div style={{display:'grid',gap:12}}>{visible.map(h=>{const p=h.process_id?processes[h.process_id]:undefined;return <article key={h.id} style={{border:'1px solid #7776',borderRadius:12,padding:16,display:'grid',gap:9}}>
   <strong style={{fontSize:18}}>{h.title||h.hearing_type||'Audiência'}</strong><div><CalendarDays size={16} style={{verticalAlign:'middle'}}/> {dateText(h.starts_at)}</div><div>{caseClient(p)||'Cliente não identificado'} · {p?.cnj_number||p?.internal_number||'Processo não vinculado'}</div>{h.location&&<div>Local: {h.location}</div>}{h.status&&<small>Situação: {h.status}</small>}
   <div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button onClick={()=>setSelected(selected===h.id?null:h.id)} style={{border:'1px solid #c9a44c',borderRadius:8,background:'#c9a44c',color:'#17130c',padding:'9px 12px',cursor:'pointer'}}><ClipboardList size={15} style={{verticalAlign:'middle'}}/> {selected===h.id?'Fechar preparação':'Preparar audiência'}</button>{h.process_id&&<button disabled={generating===h.id} onClick={()=>void generateBrief(h)} style={{padding:'9px 12px',border:'1px solid #c9a44c',borderRadius:8,background:'transparent',color:'inherit',cursor:'pointer'}}>{generating===h.id?'Preparando dossiê...':'Gerar Dossiê Estratégico com IA'}</button>}{h.process_id&&<Link to={'/conducao-processual?processo='+encodeURIComponent(h.process_id)} style={{padding:'9px 12px',border:'1px solid #c9a44c',borderRadius:8,color:'inherit'}}><Scale size={15} style={{verticalAlign:'middle'}}/> Análise do juízo</Link>}{h.process_id&&<Link to={'/dossie/'+h.process_id} style={{padding:'9px 12px',border:'1px solid #7776',borderRadius:8,color:'inherit'}}><FileText size={15} style={{verticalAlign:'middle'}}/> Dossiê do processo</Link>}{h.meeting_url&&/^https:\/\//i.test(h.meeting_url)&&<a href={h.meeting_url} target="_blank" rel="noopener noreferrer" style={{padding:'9px 12px',border:'1px solid #7776',borderRadius:8,color:'inherit'}}><ExternalLink size={15} style={{verticalAlign:'middle'}}/> Link da audiência</a>}</div>
   {chosen?.id===h.id&&<section style={{padding:15,borderRadius:10,background:'rgba(201,164,76,.07)',border:'1px solid #c9a44c'}}><h3 style={{marginTop:0}}>Preparação estratégica · checklist</h3><p>Confira os autos antes de utilizar o material. A IA trabalha apenas com os registros disponíveis; o conteúdo integral dos documentos pode não estar incluído.</p><div style={{display:'grid',gap:9}}>{checklist.map((c,i)=><label key={i} style={{display:'flex',gap:9,alignItems:'flex-start'}}><input type="checkbox"/> {c}</label>)}</div>{h.notes&&<p><strong>Observações cadastradas:</strong> {h.notes}</p>}{briefs[h.id]&&<div style={{marginTop:18}}><h3>Dossiê Estratégico para revisão</h3><button type="button" onClick={()=>downloadBrief(h)} style={{padding:'9px 14px',marginBottom:10,border:'1px solid #c9a44c',borderRadius:8}}>Baixar texto do dossiê</button><pre style={{whiteSpace:'pre-wrap',fontFamily:'inherit',lineHeight:1.6,overflowWrap:'anywhere',padding:15,background:'rgba(0,0,0,.15)',borderRadius:10}}>{briefs[h.id]}</pre></div>}</section>}
  </article>})}</div>}
 </div>;
}