import { useEffect,useState } from 'react';
import { FileUp,RefreshCw,UploadCloud,CheckCircle2,AlertTriangle } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './integrations.css';

type Job={id:string;import_type:string;file_name:string;status:string;total_rows:number;imported_rows:number;error_rows:number;duplicate_rows:number;created_at:string};
type Row=Record<string,string>;

function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)return{headers:[] as string[],rows:[] as Row[]};const semi=(lines[0].match(/;/g)||[]).length;const comma=(lines[0].match(/,/g)||[]).length;const delimiter=semi>=comma?';':',';const split=(line:string)=>{const out:string[]=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++}else quoted=!quoted}else if(c===delimiter&&!quoted){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out};const headers=split(lines[0]).map(v=>v.toLowerCase().trim().replace(/\s+/g,'_'));return{headers,rows:lines.slice(1).map(line=>{const values=split(line);const row:Row={};headers.forEach((h,i)=>row[h]=values[i]||'');return row})}}
function pick(row:Row,...keys:string[]){for(const key of keys){const value=row[key]?.trim();if(value)return value}return''}

export default function Imports(){const db:any=supabase;const [jobs,setJobs]=useState<Job[]>([]);const [type,setType]=useState('clients');const [file,setFile]=useState<File|null>(null);const [headers,setHeaders]=useState<string[]>([]);const [rows,setRows]=useState<Row[]>([]);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
async function load(){const {data}=await db.from('import_jobs').select('id,import_type,file_name,status,total_rows,imported_rows,error_rows,duplicate_rows,created_at').order('created_at',{ascending:false}).limit(20);setJobs((data||[]) as Job[])}
useEffect(()=>{void load()},[]);
async function choose(next:File|null){setFile(next);setNotice('');if(!next){setHeaders([]);setRows([]);return}if(!next.name.toLowerCase().endsWith('.csv')){setHeaders([]);setRows([]);setNotice('Use um arquivo CSV.');return}const parsed=parseCsv(await next.text());setHeaders(parsed.headers);setRows(parsed.rows)}
async function run(){const currentFile=file;if(!currentFile||!rows.length||busy)return;setBusy(true);setNotice('');try{const userResult=await db.auth.getUser();const user=userResult.data.user;if(!user)throw new Error('Sessão expirada.');const profileResult=await db.from('profiles').select('org_id').eq('id',user.id).single();if(profileResult.error||!profileResult.data?.org_id)throw new Error('Organização não encontrada.');const orgId=profileResult.data.org_id;const jobResult=await db.from('import_jobs').insert({org_id:orgId,created_by:user.id,import_type:type,file_name:currentFile.name,status:'processing',total_rows:rows.length,started_at:new Date().toISOString(),column_mapping:{headers}}).select('id').single();if(jobResult.error||!jobResult.data?.id)throw new Error(jobResult.error?.message||'Falha ao criar a importação.');const jobId=jobResult.data.id;let imported=0,errors=0,duplicates=0,valid=0;
for(let i=0;i<rows.length;i++){const raw=rows[i];const validation:string[]=[];let normalized:any={};let status='error';let recordId:string|null=null;try{if(type==='clients'){const name=pick(raw,'name','nome');if(!name)throw new Error('Nome do cliente não informado.');valid++;normalized={name,cpf_cnpj:pick(raw,'cpf_cnpj','cpf','cnpj')||null,email:pick(raw,'email','e_mail')||null,phone:pick(raw,'phone','telefone','celular')||null,whatsapp:pick(raw,'whatsapp','telefone_whatsapp')||null,profession:pick(raw,'profession','profissao')||null,notes:pick(raw,'notes','observacoes')||null};let existing:any=null;if(normalized.cpf_cnpj)existing=(await db.from('clients').select('id').eq('cpf_cnpj',normalized.cpf_cnpj).maybeSingle()).data;else if(normalized.email)existing=(await db.from('clients').select('id').eq('email',normalized.email).maybeSingle()).data;if(existing?.id){duplicates++;status='duplicate';recordId=existing.id}else{const created=await db.from('clients').insert({org_id:orgId,...normalized}).select('id').single();if(created.error)throw new Error(created.error.message);recordId=created.data.id;imported++;status='imported'}}else{const cnj=pick(raw,'cnj_number','numero_processo','processo','cnj');if(!cnj)throw new Error('Número CNJ não informado.');valid++;normalized={cnj_number:cnj,opposing_party:pick(raw,'opposing_party','parte_contraria')||null,court:pick(raw,'court','tribunal')||null,comarca:pick(raw,'comarca')||null,vara:pick(raw,'vara')||null,area:pick(raw,'area')||null,subject:pick(raw,'subject','assunto')||null,class_name:pick(raw,'class_name','classe')||null,notes:pick(raw,'notes','observacoes')||null};const existing=(await db.from('processes').select('id').eq('cnj_number',cnj).maybeSingle()).data;if(existing?.id){duplicates++;status='duplicate';recordId=existing.id}else{const created=await db.from('processes').insert({org_id:orgId,...normalized,source:'import'}).select('id').single();if(created.error)throw new Error(created.error.message);recordId=created.data.id;imported++;status='imported'}}}catch(error:any){errors++;validation.push(error?.message||'Erro ao importar linha.');status='error'}await db.from('import_rows').insert({org_id:orgId,import_job_id:jobId,row_number:i+2,raw_data:raw,normalized_data:normalized,status,validation_errors:validation,imported_record_id:recordId})}
await db.from('import_jobs').update({status:errors?'completed_with_errors':'completed',valid_rows:valid,imported_rows:imported,error_rows:errors,duplicate_rows:duplicates,finished_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',jobId);setNotice(`Importação concluída: ${imported} importados, ${duplicates} duplicados e ${errors} erros.`);setFile(null);setHeaders([]);setRows([]);await load()}catch(error:any){setNotice(error?.message||'Falha na importação.')}finally{setBusy(false)}}
return <><div className="page-title"><h1>Importações</h1><p>Importe clientes e processos em lote com validação e histórico.</p></div><div className="integration-head"><div><span className="integration-pill"><FileUp size={14}/> IMPORTAÇÃO DE DADOS</span><h2>Planilhas CSV</h2><p>Validação de linhas, prevenção de duplicidades e registro completo do processamento.</p></div><button className="integration-action" onClick={()=>void load()}><RefreshCw size={16}/>Atualizar histórico</button></div><div className="integration-panel"><div className="integration-form"><label>Tipo de importação<select value={type} onChange={e=>setType(e.target.value)}><option value="clients">Clientes</option><option value="processes">Processos</option></select></label><label>Arquivo CSV<input type="file" accept=".csv,text/csv" onChange={e=>void choose(e.target.files?.[0]||null)}/></label>{rows.length>0&&<div className="integration-notice"><CheckCircle2 size={15}/> {rows.length} linhas detectadas • {headers.length} colunas</div>}{notice&&<div className="integration-notice"><AlertTriangle size={15}/> {notice}</div>}<button className="integration-action" disabled={busy||!file||!rows.length} onClick={()=>void run()}><UploadCloud size={16}/>{busy?'Importando...':'Iniciar importação'}</button></div></div><div className="integration-panel"><h3>Histórico recente</h3>{jobs.length===0?<div className="integration-empty"><FileUp size={28}/><p>Nenhuma importação registrada.</p></div>:<div className="signature-list">{jobs.map(j=><div className="signature-row" key={j.id}><div><strong>{j.file_name}</strong><small>{j.import_type==='clients'?'Clientes':'Processos'} • {new Date(j.created_at).toLocaleString('pt-BR')} • {j.total_rows} linhas</small></div><span className="status-dot">{j.status} • {j.imported_rows} importados • {j.duplicate_rows} duplicados • {j.error_rows} erros</span></div>)}</div>}</div></>}
