import { useEffect,useState } from 'react';
import { FileUp,ClipboardPaste,RefreshCw } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './integrations.css';

type Job={id:string;extractor_key:string;file_name?:string|null;status:string;created_at:string};
export default function Imports(){const [orgId,setOrgId]=useState(''),[userId,setUserId]=useState(''),[text,setText]=useState(''),[kind,setKind]=useState('process_document'),[jobs,setJobs]=useState<Job[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
async function init(){if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;setUserId(user.id);const {data:p}=await supabase.from('profiles').select('org_id').eq('id',user.id).maybeSingle();if(p?.org_id){setOrgId(p.org_id);loadJobs(p.org_id)}}
async function loadJobs(org=orgId){if(!supabase||!org)return;const {data,error}=await supabase.from('extraction_jobs').select('id,extractor_key,file_name,status,created_at').eq('org_id',org).order('created_at',{ascending:false}).limit(30);if(error)setNotice(error.message);else setJobs((data||[]) as Job[])}
useEffect(()=>{init()},[]);
async function submit(){if(!supabase||!orgId||!text.trim())return;setBusy(true);setNotice('');const {data,error}=await supabase.functions.invoke('extractor-run',{body:{org_id:orgId,extractor_key:kind,input_text:text.trim(),created_by:userId||null}});setBusy(false);if(error)setNotice(error.message);else if((data as any)?.error)setNotice((data as any).error);else{setText('');setNotice('Importação criada e enviada para processamento.');await loadJobs()}}
return <><div className="page-title"><h1>Importações</h1><p>Entrada estruturada de documentos e dados para processamento no LEXOFFICE</p></div><div className="integration-head"><div><span className="integration-pill"><FileUp size={14}/> IMPORTAÇÃO INTELIGENTE</span><h2>Enviar conteúdo para extração</h2><p>Cole o conteúdo do documento e gere um trabalho real de extração no backend.</p></div><button className="integration-action" onClick={()=>loadJobs()}><RefreshCw size={16}/>Atualizar</button></div>{notice&&<div className="integration-notice">{notice}</div>}<div className="integration-panel"><label>Tipo de importação<select value={kind} onChange={e=>setKind(e.target.value)}><option value="process_document">Documento processual</option><option value="client_document">Documento de cliente</option><option value="contract">Contrato</option><option value="petition">Petição</option><option value="generic_document">Documento genérico</option></select></label><label>Conteúdo<textarea value={text} onChange={e=>setText(e.target.value)} rows={12} placeholder="Cole aqui o texto do documento, petição, contrato ou relatório..."/></label><button className="integration-action" onClick={submit} disabled={busy||!text.trim()}><ClipboardPaste size={16}/>{busy?'Enviando...':'Criar importação'}</button></div><div className="integration-panel"><h3>Processamentos recentes</h3>{jobs.length===0?<div className="integration-empty"><FileUp size={30}/><p>Nenhuma importação encontrada.</p></div>:<div className="signature-list">{jobs.map(j=><div className="signature-row" key={j.id}><div><strong>{j.file_name||j.extractor_key}</strong><small>{new Date(j.created_at).toLocaleString('pt-BR')}</small></div><span className="status-dot">{j.status}</span></div>)}</div>}</div></>}
