import { useEffect,useMemo,useState } from 'react';
import { FileUp,RefreshCw,UploadCloud,CheckCircle2,AlertTriangle } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './integrations.css';

type Job={id:string;import_type:string;file_name:string;status:string;total_rows:number;valid_rows:number;imported_rows:number;error_rows:number;duplicate_rows:number;created_at:string;error_message?:string|null};
type Parsed={headers:string[];rows<Record<string,string>>};
function parseCsv(text:string):Parsed{const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return{headers:[],rows:[]};const delimiter=(lines[0].match(/;/g)||[]).length>=(lines[0].match(/,/g)||[]).length?';':',';const split=(line:string)=>{const out:string[]=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===delimiter&&!q){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out};const headers=split(lines[0]).map(h=>h.trim().toLowerCase().replace(/\s+/g,'_'));const rows=lines.slice(1).map(line=>{const vals=split(line);return Object.fromEntries(headers.map((h,i)=>[h,vals[i]??'']))});return{headers,rows}}
const pick=(r:Record<string,string>,...keys:string[])=>{for(const k of keys)if(r[k]?.trim())return r[k].trim();return''};
export default function Imports(){const [jobs,setJobs]=useState<Job[]>([]),[type,setType]=useState<'clients'|'processes'>('clients'),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[preview,setPreview]=useState<Parsed>({headers:[],rows:[]});
async function load(){if(!supabase)return;const {data}=await supabase.from('import_jobs').select('id,import_type,file_name,status,total_rows,valid_rows,imported_rows,error_rows,duplicate_rows,created_at,error_message').order('created_at',{ascending:false}).limit(20);setJobs((data||[]) as Job[])}useEffect(()=>{load()},[]);
async function choose(f:File|null){setFile(f);setNotice('');if(!f){setPreview({headers:[],rows:[]});return}if(!/\.csv$/i.test(f.name)){setNotice('Use um arquivo CSV.');setPreview({headers:[],rows:[]});return}setPreview(parseCsv(await f.text()))}
const required=useMemo(()=>type==='clients'?['name']:['cnj_number'],[type]);
async function run(){if(!supabase||!file||!preview.rows.length)return;setBusy(true);setNotice('');try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão expirada.');const {data:profile,error:pe}=await supabase.from('profiles').select('org_id').eq('id',user.id).single();if(pe||!profile?.org_id)throw pe||new Error('Organização não encontrada.');const org_id=profile.org_id;const {data:job,error:je}=await supabase.from('import_jobs').insert({org_id,created_by:user.id,import_type:type,file_name:file.name,status:'processing',total_rows:preview.rows.length,started_at:new Date().toISOString(),column_mapping:{headers:preview.headers}}).select('id').single();if(je||!job)throw je||new Error('Falha ao criar importação.');let imported=0,errors=0,duplicates=0,valid=0;
for(let i=0;i<preview.rows.length;i++){const raw=preview.rows[i];const validation:string[]=[];for(const key of required){if(!pick(raw,key,key==='name'?'nome':'numero_processo','processo','cnj'))validation.push(`Campo obrigatório ausente: ${key}`)}let normalized:any={};let status='error';let recordId:string|null=null;if(!validation.length){valid++;try{if(type==='clients'){normalized={name:pick(raw,'name','nome'),cpf_cnpj:pick(raw,'cpf_cnpj','cpf','cnpj')||null,email:pick(raw,'email','e_mail')||null,phone:pick(raw,'phone','telefone','celular')||null,whatsapp:pick(raw,'whatsapp','telefone_whatsapp')||null,profession:pick(raw,'profession','profissao')||null,notes:pick(raw,'notes','observacoes')||null};let exists:any=null;if(normalized.cpf_cnpj){exists=(await supabase.from('clients').select('id').eq('cpf_cnpj',normalized.cpf_cnpj).maybeSingle()).data}else if(normalized.email){exists=(await supabase.from('clients').select('id').eq('email',normalized.email).maybeSingle()).data}if(exists){duplicates++;status='duplicate';recordId=exists.id}else{const ins=await supabase.from('clients').insert({org_id,...normalized}).select('id').single();if(ins.error)throw ins.error;recordId=ins.data.id;imported++;status='imported'}}else{normalized={cnj_number:pick(raw,'cnj_number','numero_processo','processo','cnj'),opposing_party:pick(raw,'opposing_party','parte_contraria')||null,court:pick(raw,'court','tribunal')||null,comarca:pick(raw,'comarca')||null,vara:pick(raw,'vara')||null,area:pick(raw,'area')||null,subject:pick(raw,'subject','assunto')||null,class_name:pick(raw,'class_name','classe')||null,notes:pick(raw,'notes','observacoes')||null};const existing=(await supabase.from('processes').select('id').eq('cnj_number',normalized.cnj_number).maybeSingle()).data;if(existing){duplicates++;status='duplicate';recordId=existing.id}else{const ins=await supabase.from('processes').insert({org_id,...normalized,source:'import'}).select('id').single();if(ins.error)throw ins.error;recordId=ins.data.id;imported++;status='imported'}}}catch(e:any){errors++;validation.push(e?.message||'Erro ao importar linha.');status='error'}}else errors++;await supabase.from('import_rows').insert({org_id,import_job_id:job.id,row_number:i+2,raw_data:raw,normalized_data:normalized,status,validation_errors:validation,imported_record_id:recordId});}
await supabase.from('import_jobs').update({status:errors?'completed_with_errors':'completed',valid_rows:valid,imported_rows:imported,error_rows:errors,duplicate_rows:duplicates,finished_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',job.id);setNotice(`Importação concluída: ${imported} registros importados, ${duplicates} duplicados e ${errors} com erro.`);setFile(null);setPreview({headers:[],rows:[]});await load()}catch(e:any){setNotice(e?.message||'Falha na importação.')}finally{setBusy(false)}}
return <><div className="page-title"><h1>Importações</h1><p>Importe clientes e processos em lote com validação e histórico.</p></div><div className="integration-head"><div><span className="integration-pill"><FileUp size={14}/> IMPORTAÇÃO DE DADOS</span><h2>Planilhas CSV</h2><p>O LEXOFFICE valida cada linha, evita duplicidades e registra o resultado da operação.</p></div><button className="integration-action" onClick={load}><RefreshCw size={16}/>Atualizar histórico</button></div><div className="integration-panel"><div className="integration-form"><label>Tipo de importação<select value={type} onChange={e=>setType(e.target.value as any)}><option value="clients">Clientes</option><option value="processes">Processos</option></select></label><label>Arquivo CSV<input type="file" accept=".csv,text/csv" onChange={e=>choose(e.target.files?.[0]||null)}/></label>{preview.rows.length>0&&<div className="integration-notice"><CheckCircle2 size={15}/> {preview.rows.length} linhas detectadas • colunas: {preview.headers.join(', ')}</div>}{notice&&<div className="integration-notice"><AlertTriangle size={15}/> {notice}</div>}<button className="integration-action" disabled={busy||!file||!preview.rows.length} onClick={run}><UploadCloud size={16}/>{busy?'Importando...':'Iniciar importação'}</button></div></div><div className="integration-panel"><h3>Histórico recente</h3>{jobs.length===0?<div className="integration-empty"><FileUp size={28}/><p>Nenhuma importação registrada.</p></div>:<div className="signature-list">{jobs.map(j=><div className="signature-row" key={j.id}><div><strong>{j.file_name}</strong><small>{j.import_type==='clients'?'Clientes':'Processos'} • {new Date(j.created_at).toLocaleString('pt-BR')} • {j.total_rows} linhas</small></div><span className="status-dot">{j.status} • {j.imported_rows} importados • {j.duplicate_rows} duplicados • {j.error_rows} erros</span></div>)}</div>}</div></>}
