import { useEffect,useState } from 'react';
import { Megaphone,Plus,Play,RefreshCw } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './integrations.css';

type List={id:string;name:string};type Campaign={id:string;name:string;channel:string;status:string;scheduled_at?:string|null;daily_limit?:number|null;respect_opt_out:boolean;stop_on_reply:boolean;created_at:string;list_id?:string|null};
export default function Marketing(){const [campaigns,setCampaigns]=useState<Campaign[]>([]),[lists,setLists]=useState<List[]>([]),[orgId,setOrgId]=useState(''),[form,setForm]=useState({name:'',channel:'whatsapp',list_id:'',daily_limit:'',scheduled_at:'',stop_on_reply:true,respect_opt_out:true}),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
async function load(){if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:p}=await supabase.from('profiles').select('org_id').eq('id',user.id).single();if(!p?.org_id)return;setOrgId(p.org_id);const [{data:c},{data:l}]=await Promise.all([supabase.from('marketing_campaigns').select('id,name,channel,status,scheduled_at,daily_limit,respect_opt_out,stop_on_reply,created_at,list_id').order('created_at',{ascending:false}).limit(50),supabase.from('marketing_lists').select('id,name').eq('active',true).order('name')]);setCampaigns((c||[]) as Campaign[]);setLists((l||[]) as List[])}useEffect(()=>{load()},[]);
async function create(){if(!supabase||!orgId||!form.name.trim())return;setBusy(true);setNotice('');const {error}=await supabase.from('marketing_campaigns').insert({org_id:orgId,name:form.name.trim(),channel:form.channel,list_id:form.list_id||null,status:'draft',scheduled_at:form.scheduled_at?new Date(form.scheduled_at).toISOString():null,daily_limit:form.daily_limit?Number(form.daily_limit):null,stop_on_reply:form.stop_on_reply,respect_opt_out:form.respect_opt_out});setBusy(false);if(error)setNotice(error.message);else{setForm({name:'',channel:'whatsapp',list_id:'',daily_limit:'',scheduled_at:'',stop_on_reply:true,respect_opt_out:true});setNotice('Campanha criada como rascunho.');await load()}}
async function run(id:string){if(!supabase)return;setBusy(true);setNotice('');const {data,error}=await supabase.functions.invoke('marketing-campaign-run',{body:{campaign_id:id}});setBusy(false);if(error)setNotice(error.message);else if((data as any)?.error)setNotice((data as any).error);else setNotice((data as any)?.message||'Campanha validada pelo backend.')}
return <><div className="page-title"><h1>Marketing</h1><p>Campanhas, listas e automações de comunicação.</p></div><div className="integration-head"><div><span className="integration-pill"><Megaphone size={14}/> CAMPANHAS</span><h2>Nova campanha</h2><p>Campanhas respeitam opt-out e podem interromper a sequência quando houver resposta.</p></div><button className="integration-action" onClick={load}><RefreshCw size={16}/>Atualizar</button></div>{notice&&<div className="integration-notice">{notice}</div>}<div className="integration-panel"><div className="integration-form"><label>Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Canal<select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}><option value="whatsapp">WhatsApp</option><option value="email">E-mail</option></select></label><label>Lista<select value={form.list_id} onChange={e=>setForm({...form,list_id:e.target.value})}><option value="">Sem lista</option>{lists.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select></label><label>Limite diário<input type="number" min="1" value={form.daily_limit} onChange={e=>setForm({...form,daily_limit:e.target.value})}/></label><label>Agendar para<input type="datetime-local" value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/></label><label><input type="checkbox" checked={form.stop_on_reply} onChange={e=>setForm({...form,stop_on_reply:e.target.checked})}/> Parar ao receber resposta</label><label><input type="checkbox" checked={form.respect_opt_out} onChange={e=>setForm({...form,respect_opt_out:e.target.checked})}/> Respeitar opt-out</label><button className="integration-action" onClick={create} disabled={busy||!form.name.trim()}><Plus size={16}/>Criar campanha</button></div></div><div className="integration-panel"><h3>Campanhas</h3>{campaigns.length===0?<div className="integration-empty"><Megaphone size={28}/><p>Nenhuma campanha.</p></div>:<div className="signature-list">{campaigns.map(c=><div className="signature-row" key={c.id}><div><strong>{c.name}</strong><small>{c.channel} • {c.scheduled_at?new Date(c.scheduled_at).toLocaleString('pt-BR'):'sem agendamento'} • opt-out {c.respect_opt_out?'ativo':'inativo'}</small></div><div className="signature-actions"><span className="status-dot">{c.status}</span><button className="integration-action" onClick={()=>run(c.id)} disabled={busy}><Play size={14}/>Validar</button></div></div>)}</div>}</div></>}
