import {useEffect,useState} from 'react';
import {Facebook,KeyRound,CheckCircle2,AlertTriangle} from 'lucide-react';
import {supabase} from '../lib/supabase';

declare global{interface Window{FB:any;fbAsyncInit?:()=>void}}
export default function MetaPartnerConnect(){
 const [status,setStatus]=useState<any>(null),[appId,setAppId]=useState(''),[appSecret,setAppSecret]=useState(''),[configId,setConfigId]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){if(!supabase)return;const r=await supabase.functions.invoke('meta-whatsapp-oauth',{body:{action:'status'}});if(!r.error){setStatus(r.data);if(r.data?.app_id)setAppId(String(r.data.app_id));if(r.data?.embedded_configuration_id)setConfigId(String(r.data.embedded_configuration_id))}}
 useEffect(()=>{load()},[]);
 async function save(){if(!supabase||!appId.trim()||!appSecret.trim()||!configId.trim())return;setBusy(true);setNotice('');const r=await supabase.functions.invoke('meta-whatsapp-oauth',{body:{action:'configure_app',app_id:appId.trim(),app_secret:appSecret.trim(),configuration_id:configId.trim()}});setBusy(false);if(r.error||r.data?.error){setNotice(r.data?.error||r.error?.message||'Falha ao salvar configuração da Meta.');return}setAppSecret('');setNotice('Configuração de parceiro salva. Agora use Conectar como parceiro.');await load()}
 function sdk(){return new Promise<void>((resolve,reject)=>{if(window.FB){window.FB.init({appId,status:false,cookie:true,xfbml:false,version:'v23.0'});resolve();return}window.fbAsyncInit=()=>{window.FB.init({appId,status:false,cookie:true,xfbml:false,version:'v23.0'});resolve()};const old=document.getElementById('facebook-jssdk');if(old){setTimeout(()=>window.FB?resolve():reject(new Error('SDK da Meta não carregou.')),1200);return}const s=document.createElement('script');s.id='facebook-jssdk';s.async=true;s.defer=true;s.crossOrigin='anonymous';s.src='https://connect.facebook.net/pt_BR/sdk.js';s.onerror=()=>reject(new Error('Não foi possível carregar o SDK da Meta.'));document.body.appendChild(s)})}
 async function connectPartner(){if(!supabase||!appId.trim()||!configId.trim())return;setBusy(true);setNotice('');try{await sdk();window.FB.login(async(response:any)=>{const code=response?.authResponse?.code;if(!code){setBusy(false);setNotice('A Meta não devolveu o código de conexão. Verifique se a configuração do Embedded Signup está publicada.');return}const r=await supabase.functions.invoke('meta-whatsapp-oauth',{body:{action:'embedded_exchange',code}});setBusy(false);if(r.error||r.data?.error){setNotice(r.data?.error||r.error?.message||'Falha ao concluir conexão como parceiro.');return}setNotice('WhatsApp Business conectado pela Meta como parceiro.');await load()},{config_id:configId.trim(),response_type:'code',override_default_response_type:true,extras:{setup:{},featureType:'whatsapp_business_app_onboarding',sessionInfoVersion:'3'}})}catch(e:any){setBusy(false);setNotice(e?.message||'Falha ao abrir conexão da Meta.')}}
 const connected=status?.connection?.status==='connected';
 return <div className={`meta-partner-box ${connected?'connected':''}`}><div className="meta-config-title"><Facebook size={17}/><b>Conexão como parceiro — Embedded Signup</b></div><p>Fluxo indicado para o LEXOFFICE conectar WhatsApp Business pela Meta sem depender do redirecionamento OAuth comum. É necessário criar uma configuração de Facebook Login for Business / WhatsApp Embedded Signup no aplicativo Meta.</p><div className="provider-status-row"><span className={status?.configured?'ok':'warn'}>{status?.configured?<CheckCircle2 size={14}/>:<AlertTriangle size={14}/>} App Meta</span><span className={status?.embedded_ready?'ok':'warn'}>{status?.embedded_ready?<CheckCircle2 size={14}/>:<AlertTriangle size={14}/>} Embedded Signup</span><span className={connected?'ok':'warn'}>{connected?<CheckCircle2 size={14}/>:<AlertTriangle size={14}/>} WhatsApp Oficial</span></div><div className="integration-form"><label>Meta App ID<input value={appId} onChange={e=>setAppId(e.target.value)} placeholder="ID do aplicativo"/></label><label>Meta App Secret<input type="password" value={appSecret} onChange={e=>setAppSecret(e.target.value)} placeholder={status?.configured?'Somente para substituir':'App Secret'}/></label><label>ID da configuração Embedded Signup<input value={configId} onChange={e=>setConfigId(e.target.value)} placeholder="Configuration ID do Facebook Login for Business"/></label><button className="secondary" disabled={busy||!appId.trim()||!appSecret.trim()||!configId.trim()} onClick={save}><KeyRound size={15}/>Salvar configuração parceiro</button><button className="integration-action" disabled={busy||!appId.trim()||!configId.trim()||!status?.embedded_ready} onClick={connectPartner}><Facebook size={15}/>{busy?'Conectando...':'Conectar como parceiro'}</button></div>{notice&&<div className="integration-notice">{notice}</div>}{status?.redirect_uri&&<small className="meta-redirect-note">OAuth direto continua disponível. Callback cadastrado: {status.redirect_uri}</small>}</div>
}
