import { useEffect,useMemo,useState } from 'react';
import { Building2,Users,CreditCard,ScrollText,Activity,Plus,RefreshCw,ShieldCheck,CheckCircle2,AlertCircle } from 'lucide-react';
import { supabase } from '../lib/supabase';

type Org={id:string;name:string;slug:string;plan:string;status:string;created_at:string};
type Profile={id:string;org_id:string;name:string;email:string;role_key:string;status:string;created_at:string};
type Sub={id:string;org_id:string;plan:string;status:string;amount_cents:number|null;currency:string;billing_cycle:string;next_due_at:string|null;last_payment_at:string|null;updated_at:string};
type Log={id:string;org_id:string;user_id:string|null;action:string;entity:string;entity_id:string|null;created_at:string};
const tabs=[['overview','Visão Geral',Activity],['organizations','Organizações',Building2],['subscriptions','Assinaturas',CreditCard],['users','Usuários',Users],['logs','Logs / Auditoria',ScrollText],['health','Saúde do Sistema',ShieldCheck]] as const;
const dt=(v?:string|null)=>v?new Date(v).toLocaleString('pt-BR'):'—';
const money=(v:number|null,c='BRL')=>v==null?'Não configurado':new Intl.NumberFormat('pt-BR',{style:'currency',currency:c}).format(v/100);
export default function PlatformAdmin(){
 const[tab,setTab]=useState('overview'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const[orgs,setOrgs]=useState<Org[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[subs,setSubs]=useState<Sub[]>([]),[logs,setLogs]=useState<Log[]>([]);
 const[form,setForm]=useState({org_name:'',name:'',email:'',password:''});
 async function load(){if(!supabase)return;setLoading(true);setError('');const[o,p,s,l]=await Promise.all([supabase.from('organizations').select('id,name,slug,plan,status,created_at').order('created_at',{ascending:false}),supabase.from('profiles').select('id,org_id,name,email,role_key,status,created_at').order('created_at',{ascending:false}),supabase.from('platform_subscriptions').select('id,org_id,plan,status,amount_cents,currency,billing_cycle,next_due_at,last_payment_at,updated_at').order('updated_at',{ascending:false}),supabase.from('audit_logs').select('id,org_id,user_id,action,entity,entity_id,created_at').order('created_at',{ascending:false}).limit(200)]);const e=o.error||p.error||s.error||l.error;if(e)setError(e.message);setOrgs((o.data||[]) as Org[]);setProfiles((p.data||[]) as Profile[]);setSubs((s.data||[]) as Sub[]);setLogs((l.data||[]) as Log[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const byOrg=useMemo(()=>new Map(orgs.map(o=>[o.id,o.name])),[orgs]);
 async function createOrg(e:any){e.preventDefault();if(!supabase||busy)return;setBusy(true);setError('');setNotice('');const{data,error}=await supabase.functions.invoke('create-organization',{body:form});setBusy(false);if(error||!data?.ok){setError(data?.error||error?.message||'Não foi possível criar a organização.');return}setNotice('Organização e primeiro usuário criados com sucesso.');setForm({org_name:'',name:'',email:'',password:''});await load();setTab('organizations')}
 async function updateSub(id:string,patch:any){if(!supabase)return;setError('');const{error}=await supabase.from('platform_subscriptions').update({...patch,updated_at:new Date().toISOString()}).eq('id',id);if(error){setError(error.message);return}await load()}
 const cards=[['Organizações',orgs.length,Building2],['Usuários',profiles.length,Users],['Assinaturas ativas',subs.filter(x=>x.status==='active').length,CreditCard],['Em atraso',subs.filter(x=>x.status==='past_due').length,AlertCircle]] as const;
 return <div className="module"><div className="page-head"><div><span className="eyebrow">ADMINISTRAÇÃO DA PLATAFORMA</span><h1>LEXOFFICE Admin</h1><p>Organizações, usuários, assinaturas, auditoria e saúde operacional.</p></div><button className="secondary" onClick={load} disabled={loading}><RefreshCw size={15}/>{loading?'Atualizando...':'Atualizar'}</button></div><div className="settings-section-nav">{tabs.map(([k,l,I])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><I size={15}/>{l}</button>)}</div>{error&&<div className="status-message error"><AlertCircle size={16}/>{error}</div>}{notice&&<div className="status-message success"><CheckCircle2 size={16}/>{notice}</div>}
 {tab==='overview'&&<><div className="dashboard-kpis">{cards.map(([l,v,I])=><div className="dashboard-kpi" key={l}><div className="dashboard-kpi-head"><div className="dashboard-kpi-icon"><I size={17}/></div></div><strong>{v}</strong><span>{l}</span></div>)}</div><div className="settings-feature-card wide"><h3><Plus size={17}/> Nova organização</h3><p>Crie a organização e o primeiro usuário proprietário em um único fluxo administrativo.</p><form className="form-grid" onSubmit={createOrg}><label>Organização<input value={form.org_name} onChange={e=>setForm({...form,org_name:e.target.value})} required/></label><label>Primeiro usuário<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Senha temporária<input type="password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label><div><button className="primary" disabled={busy}>{busy?'Criando...':'Criar organização e owner'}</button></div></form></div></>}
 {tab==='organizations'&&<div className="module-box"><h3>Organizações</h3><div className="table-wrap"><table><thead><tr><th>Organização</th><th>Plano</th><th>Status</th><th>Usuários</th><th>Criada em</th></tr></thead><tbody>{orgs.map(o=><tr key={o.id}><td><b>{o.name}</b><small style={{display:'block'}}>{o.slug}</small></td><td>{o.plan}</td><td>{o.status}</td><td>{profiles.filter(p=>p.org_id===o.id).length}</td><td>{dt(o.created_at)}</td></tr>)}</tbody></table></div></div>}
 {tab==='users'&&<div className="module-box"><h3>Usuários</h3><div className="table-wrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Organização</th><th>Perfil</th><th>Status</th></tr></thead><tbody>{profiles.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.email}</td><td>{byOrg.get(p.org_id)||'—'}</td><td>{p.role_key}</td><td>{p.status}</td></tr>)}</tbody></table></div></div>}
 {tab==='subscriptions'&&<div className="module-box"><h3>Assinaturas</h3><p>Até integrar um gateway, o acompanhamento pode ser mantido administrativamente nesta central.</p><div className="table-wrap"><table><thead><tr><th>Organização</th><th>Plano</th><th>Status</th><th>Valor</th><th>Vencimento</th><th>Ação</th></tr></thead><tbody>{subs.map(s=><tr key={s.id}><td>{byOrg.get(s.org_id)||'—'}</td><td>{s.plan}</td><td><select value={s.status} onChange={e=>updateSub(s.id,{status:e.target.value})}><option value="not_configured">Não configurado</option><option value="trial">Teste</option><option value="active">Ativa</option><option value="past_due">Em atraso</option><option value="suspended">Suspensa</option><option value="canceled">Cancelada</option></select></td><td>{money(s.amount_cents,s.currency)}</td><td>{dt(s.next_due_at)}</td><td><button className="secondary" onClick={()=>updateSub(s.id,{last_payment_at:new Date().toISOString(),status:'active'})}>Registrar pagamento</button></td></tr>)}</tbody></table></div></div>}
 {tab==='logs'&&<div className="module-box"><h3>Logs e auditoria</h3><div className="table-wrap"><table><thead><tr><th>Data</th><th>Ação</th><th>Entidade</th><th>Organização</th><th>Usuário</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{dt(l.created_at)}</td><td>{l.action}</td><td>{l.entity}</td><td>{byOrg.get(l.org_id)||'—'}</td><td>{profiles.find(p=>p.id===l.user_id)?.email||'Sistema'}</td></tr>)}</tbody></table></div></div>}
 {tab==='health'&&<div className="settings-feature-grid"><div className="settings-feature-card"><h3><CheckCircle2 size={17}/> Banco de dados</h3><p>{error?'Requer atenção':'Consultas administrativas respondendo normalmente.'}</p></div><div className="settings-feature-card"><h3><ShieldCheck size={17}/> Controle de acesso</h3><p>Acesso restrito aos administradores ativos da plataforma.</p></div><div className="settings-feature-card"><h3><Activity size={17}/> Auditoria</h3><p>{logs.length} eventos recentes disponíveis.</p></div></div>}
 </div>}
