import { useEffect,useMemo,useState } from 'react';
import { Building2,Users,CreditCard,ScrollText,Activity,Plus,RefreshCw,ShieldCheck,CheckCircle2,AlertCircle,Search,Package,PauseCircle,PlayCircle } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { humanize,roleLabels,statusLabels } from '../lib/ux';

type Org={id:string;name:string;slug:string;plan:string;status:string;document?:string|null;contact_email?:string|null;contact_phone?:string|null;external_customer_id?:string|null;suspended_at?:string|null;suspension_reason?:string|null;created_at:string};
type Profile={id:string;org_id:string;name:string;email:string;role_key:string;status:string;created_at:string};
type Plan={id:string;code:string;name:string;description:string|null;status:string;price_cents:number|null;currency:string;billing_cycle:string;max_users:number|null;features:any;external_product_id:string|null;external_price_id:string|null};
type Sub={id:string;org_id:string;plan:string;plan_id?:string|null;status:string;external_status?:string|null;amount_cents:number|null;currency:string;billing_cycle:string;next_due_at:string|null;access_until?:string|null;synced_at?:string|null;provider?:string|null;updated_at:string};
type Log={id:string;org_id:string;user_id:string|null;action:string;entity:string;entity_id:string|null;created_at:string};
const tabs=[['overview','Visão Geral',Activity],['organizations','Empresas',Building2],['users','Usuários e funcionários',Users],['plans','Planos',Package],['subscriptions','Assinaturas',CreditCard],['logs','Auditoria',ScrollText],['health','Sistema',ShieldCheck]] as const;
const dt=(v?:string|null)=>v?new Date(v).toLocaleString('pt-BR'):'—';const money=(v:number|null,c='BRL')=>v==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:c}).format(v/100);
export default function PlatformAdmin(){
 const[tab,setTab]=useState('overview'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState('all');
 const[orgs,setOrgs]=useState<Org[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[plans,setPlans]=useState<Plan[]>([]),[subs,setSubs]=useState<Sub[]>([]),[logs,setLogs]=useState<Log[]>([]);
 const[orgForm,setOrgForm]=useState({org_name:'',name:'',email:'',password:''});const[userForm,setUserForm]=useState({org_id:'',name:'',email:'',password:'',role_key:'assistant'});const[planForm,setPlanForm]=useState({code:'',name:'',description:'',price:'',billing_cycle:'monthly',max_users:'',external_product_id:'',external_price_id:''});
 async function load(){if(!supabase)return;setLoading(true);setError('');const[o,p,pl,s,l]=await Promise.all([supabase.from('organizations').select('id,name,slug,plan,status,document,contact_email,contact_phone,external_customer_id,suspended_at,suspension_reason,created_at').order('created_at',{ascending:false}),supabase.from('profiles').select('id,org_id,name,email,role_key,status,created_at').order('created_at',{ascending:false}),supabase.from('platform_plans').select('*').order('name'),supabase.from('platform_subscriptions').select('id,org_id,plan,plan_id,status,external_status,amount_cents,currency,billing_cycle,next_due_at,access_until,synced_at,provider,updated_at').order('updated_at',{ascending:false}),supabase.from('audit_logs').select('id,org_id,user_id,action,entity,entity_id,created_at').order('created_at',{ascending:false}).limit(200)]);const e=o.error||p.error||pl.error||s.error||l.error;if(e)setError(e.message);setOrgs((o.data||[]) as Org[]);setProfiles((p.data||[]) as Profile[]);setPlans((pl.data||[]) as Plan[]);setSubs((s.data||[]) as Sub[]);setLogs((l.data||[]) as Log[]);setLoading(false)}useEffect(()=>{load()},[]);
 const byOrg=useMemo(()=>new Map(orgs.map(o=>[o.id,o.name])),[orgs]);const byPlan=useMemo(()=>new Map(plans.map(p=>[p.id,p])),[plans]);const norm=query.trim().toLowerCase();const match=(v:string)=>!norm||v.toLowerCase().includes(norm);
 const filteredOrgs=orgs.filter(o=>match(`${o.name} ${o.slug} ${o.document||''} ${o.status}`)&&(statusFilter==='all'||o.status===statusFilter));const filteredUsers=profiles.filter(p=>match(`${p.name} ${p.email} ${byOrg.get(p.org_id)||''} ${p.role_key}`)&&(statusFilter==='all'||p.status===statusFilter));const filteredSubs=subs.filter(s=>match(`${byOrg.get(s.org_id)||''} ${s.plan} ${s.status} ${s.provider||''}`)&&(statusFilter==='all'||s.status===statusFilter));
 async function createOrg(e:any){e.preventDefault();if(!supabase||busy)return;setBusy(true);const{data,error}=await supabase.functions.invoke('create-organization',{body:orgForm});setBusy(false);if(error||!data?.ok){setError(data?.error||error?.message||'Falha ao criar empresa.');return}setOrgForm({org_name:'',name:'',email:'',password:''});setNotice('Empresa e proprietário criados.');await load()}
 async function setOrgStatus(o:Org,status:string){if(!supabase)return;const patch:any={status,suspended_at:status==='suspended'?new Date().toISOString():null,suspension_reason:status==='suspended'?'Suspensão administrativa pelo Super Admin':null};const{error}=await supabase.from('organizations').update(patch).eq('id',o.id);if(error)setError(error.message);else{setNotice(status==='suspended'?'Empresa suspensa.':'Empresa reativada.');await load()}}
 async function adminAction(body:any){if(!supabase)return false;setBusy(true);setError('');setNotice('');const{data,error}=await supabase.functions.invoke('create-organization',{body});setBusy(false);if(error||!data?.ok){setError(data?.error||error?.message||'Operação administrativa não concluída.');return false}await load();return true}
 async function createUser(e:any){e.preventDefault();if(await adminAction({action:'create_user',...userForm})){setUserForm({org_id:'',name:'',email:'',password:'',role_key:'assistant'});setNotice('Usuário incluído na empresa com sucesso.')}}
 async function setUserStatus(p:Profile,status:string){if(await adminAction({action:'update_user',user_id:p.id,status}))setNotice('Acesso do usuário atualizado.')}
 async function moveUser(p:Profile,org_id:string){if(org_id&&org_id!==p.org_id&&await adminAction({action:'update_user',user_id:p.id,org_id}))setNotice('Usuário transferido para a empresa selecionada.')}
 async function changeRole(p:Profile,role_key:string){if(role_key!==p.role_key&&await adminAction({action:'update_user',user_id:p.id,role_key}))setNotice('Perfil do usuário atualizado.')}
 async function createPlan(e:any){e.preventDefault();if(!supabase)return;setBusy(true);const payload={code:planForm.code.trim().toLowerCase().replace(/\s+/g,'_'),name:planForm.name.trim(),description:planForm.description||null,price_cents:planForm.price?Math.round(Number(planForm.price.replace(',','.'))*100):null,billing_cycle:planForm.billing_cycle,max_users:planForm.max_users?Number(planForm.max_users):null,external_product_id:planForm.external_product_id||null,external_price_id:planForm.external_price_id||null,status:'active'};const{error}=await supabase.from('platform_plans').insert(payload);setBusy(false);if(error){setError(error.message);return}setPlanForm({code:'',name:'',description:'',price:'',billing_cycle:'monthly',max_users:'',external_product_id:'',external_price_id:''});setNotice('Plano criado.');await load()}
 async function setPlanStatus(p:Plan,status:string){if(!supabase)return;const{error}=await supabase.from('platform_plans').update({status,updated_at:new Date().toISOString()}).eq('id',p.id);if(error)setError(error.message);else await load()}
 const toolbar=(show=true)=><div className="table-tools ux-toolbar"><div className="input-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar"/></div>{show&&<select className="ux-filter" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">Todos</option><option value="active">Ativo</option><option value="suspended">Suspenso</option><option value="inactive">Inativo</option><option value="past_due">Em atraso</option><option value="canceled">Cancelado</option></select>}</div>;
 const cards=[['Empresas',orgs.length,Building2],['Usuários',profiles.length,Users],['Planos ativos',plans.filter(x=>x.status==='active').length,Package],['Assinaturas ativas',subs.filter(x=>x.status==='active').length,CreditCard]] as const;
 return <div className="module"><div className="page-head"><div><span className="eyebrow">ACESSO EXCLUSIVO SUPER ADMIN</span><h1>LEXOFFICE Super Admin</h1><p>Controle global de empresas, pessoas, planos, assinaturas e acessos da plataforma.</p></div><button className="secondary" onClick={load}><RefreshCw size={15}/>{loading?'Atualizando...':'Atualizar'}</button></div><div className="settings-section-nav">{tabs.map(([k,l,I])=><button key={k} className={tab===k?'active':''} onClick={()=>{setTab(k);setQuery('');setStatusFilter('all')}}><I size={15}/>{l}</button>)}</div>{error&&<div className="status-message error"><AlertCircle size={16}/>{error}</div>}{notice&&<div className="status-message success"><CheckCircle2 size={16}/>{notice}</div>}
 {tab==='overview'&&<><div className="dashboard-kpis">{cards.map(([l,v,I])=><div className="dashboard-kpi" key={l}><div className="dashboard-kpi-icon"><I size={17}/></div><strong>{v}</strong><span>{l}</span></div>)}</div><div className="settings-feature-card wide"><h3><Plus size={17}/> Nova empresa</h3><p>Cadastro administrativo. A venda e cobrança permanecem na aplicação externa.</p><form className="form-grid" onSubmit={createOrg}><label>Empresa<input required value={orgForm.org_name} onChange={e=>setOrgForm({...orgForm,org_name:e.target.value})}/></label><label>Proprietário<input required value={orgForm.name} onChange={e=>setOrgForm({...orgForm,name:e.target.value})}/></label><label>E-mail<input type="email" required value={orgForm.email} onChange={e=>setOrgForm({...orgForm,email:e.target.value})}/></label><label>Senha temporária<input type="password" minLength={8} required value={orgForm.password} onChange={e=>setOrgForm({...orgForm,password:e.target.value})}/></label><button className="primary" disabled={busy}>Criar empresa</button></form></div></>}
 {tab==='organizations'&&<div className="module-box"><h3>Empresas clientes</h3>{toolbar()}<div className="table-wrap"><table><thead><tr><th>Empresa</th><th>Status</th><th>Usuários</th><th>Assinatura</th><th>Ação</th></tr></thead><tbody>{filteredOrgs.map(o=>{const s=subs.find(x=>x.org_id===o.id);return <tr key={o.id}><td><b>{o.name}</b><small style={{display:'block'}}>{o.document||o.slug}</small></td><td>{humanize(o.status,statusLabels)}</td><td>{profiles.filter(p=>p.org_id===o.id).length}</td><td>{s?`${byPlan.get(s.plan_id||'')?.name||s.plan} · ${humanize(s.status,statusLabels)}`:'Sem assinatura'}</td><td><button className="secondary" onClick={()=>setOrgStatus(o,o.status==='suspended'?'active':'suspended')}>{o.status==='suspended'?<PlayCircle size={14}/>:<PauseCircle size={14}/>} {o.status==='suspended'?'Reativar':'Suspender'}</button></td></tr>})}</tbody></table></div></div>}
 {tab==='users'&&<><div className="settings-feature-card wide"><h3><Plus size={17}/> Incluir usuário em empresa</h3><p>Crie o acesso e já vincule o profissional à empresa correta.</p><form className="form-grid" onSubmit={createUser}><label>Empresa<select required value={userForm.org_id} onChange={e=>setUserForm({...userForm,org_id:e.target.value})}><option value="">Selecione</option>{orgs.filter(o=>o.status==='active').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Nome<input required value={userForm.name} onChange={e=>setUserForm({...userForm,name:e.target.value})}/></label><label>E-mail<input type="email" required value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})}/></label><label>Senha temporária<input type="password" minLength={8} required value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})}/></label><label>Perfil<select value={userForm.role_key} onChange={e=>setUserForm({...userForm,role_key:e.target.value})}><option value="assistant">Profissional do escritório</option><option value="lawyer">Advogado(a)</option><option value="owner">Proprietário</option></select></label><button className="primary" disabled={busy}>{busy?'Salvando...':'Incluir usuário'}</button></form></div><div className="module-box"><h3>Usuários e funcionários</h3>{toolbar()}<div className="table-wrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Empresa</th><th>Perfil</th><th>Status</th><th>Ação</th></tr></thead><tbody>{filteredUsers.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.email}</td><td><select value={p.org_id} onChange={e=>moveUser(p,e.target.value)}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></td><td><select value={p.role_key} onChange={e=>changeRole(p,e.target.value)}><option value="owner">Proprietário</option><option value="lawyer">Advogado(a)</option><option value="assistant">Profissional</option></select></td><td>{humanize(p.status,statusLabels)}</td><td><button className="secondary" onClick={()=>setUserStatus(p,p.status==='active'?'inactive':'active')}>{p.status==='active'?'Bloquear':'Reativar'}</button></td></tr>)}</tbody></table></div></div></>}
 {tab==='plans'&&<><div className="settings-feature-card wide"><h3><Plus size={17}/> Novo plano</h3><form className="form-grid" onSubmit={createPlan}><label>Código<input required value={planForm.code} onChange={e=>setPlanForm({...planForm,code:e.target.value})}/></label><label>Nome<input required value={planForm.name} onChange={e=>setPlanForm({...planForm,name:e.target.value})}/></label><label>Preço de referência<input placeholder="149,90" value={planForm.price} onChange={e=>setPlanForm({...planForm,price:e.target.value})}/></label><label>Máx. usuários<input type="number" min="1" value={planForm.max_users} onChange={e=>setPlanForm({...planForm,max_users:e.target.value})}/></label><label>Ciclo<select value={planForm.billing_cycle} onChange={e=>setPlanForm({...planForm,billing_cycle:e.target.value})}><option value="monthly">Mensal</option><option value="yearly">Anual</option></select></label><label>ID produto externo<input value={planForm.external_product_id} onChange={e=>setPlanForm({...planForm,external_product_id:e.target.value})}/></label><label>ID preço externo<input value={planForm.external_price_id} onChange={e=>setPlanForm({...planForm,external_price_id:e.target.value})}/></label><label>Descrição<input value={planForm.description} onChange={e=>setPlanForm({...planForm,description:e.target.value})}/></label><button className="primary" disabled={busy}>Criar plano</button></form></div><div className="module-box"><div className="table-wrap"><table><thead><tr><th>Plano</th><th>Preço</th><th>Ciclo</th><th>Limite</th><th>Status</th><th>Ação</th></tr></thead><tbody>{plans.map(p=><tr key={p.id}><td><b>{p.name}</b><small style={{display:'block'}}>{p.code}</small></td><td>{money(p.price_cents,p.currency)}</td><td>{p.billing_cycle}</td><td>{p.max_users??'Ilimitado'}</td><td>{p.status}</td><td><button className="secondary" onClick={()=>setPlanStatus(p,p.status==='active'?'inactive':'active')}>{p.status==='active'?'Desativar':'Ativar'}</button></td></tr>)}</tbody></table></div></div></>}
 {tab==='subscriptions'&&<div className="module-box"><h3>Assinaturas recebidas da aplicação externa</h3><p>A LexOffice controla acesso e sincronização. Pagamento e checkout não são realizados aqui.</p>{toolbar()}<div className="table-wrap"><table><thead><tr><th>Empresa</th><th>Plano</th><th>Status</th><th>Provedor</th><th>Próximo vencimento</th><th>Acesso até</th><th>Sincronizado</th></tr></thead><tbody>{filteredSubs.map(s=><tr key={s.id}><td>{byOrg.get(s.org_id)||'—'}</td><td>{byPlan.get(s.plan_id||'')?.name||s.plan}</td><td>{humanize(s.status,statusLabels)}</td><td>{s.provider||'Externo'}</td><td>{dt(s.next_due_at)}</td><td>{dt(s.access_until)}</td><td>{dt(s.synced_at||s.updated_at)}</td></tr>)}</tbody></table></div></div>}
 {tab==='logs'&&<div className="module-box"><h3>Logs e auditoria</h3>{toolbar(false)}<div className="table-wrap"><table><thead><tr><th>Data</th><th>Ação</th><th>Entidade</th><th>Empresa</th><th>Usuário</th></tr></thead><tbody>{logs.filter(l=>match(`${l.action} ${l.entity} ${byOrg.get(l.org_id)||''}`)).map(l=><tr key={l.id}><td>{dt(l.created_at)}</td><td>{l.action}</td><td>{l.entity}</td><td>{byOrg.get(l.org_id)||'—'}</td><td>{profiles.find(p=>p.id===l.user_id)?.email||'Sistema'}</td></tr>)}</tbody></table></div></div>}
 {tab==='health'&&<div className="settings-feature-grid"><div className="settings-feature-card"><h3><CheckCircle2 size={17}/> Banco</h3><p>Estrutura Super Admin disponível.</p></div><div className="settings-feature-card"><h3><ShieldCheck size={17}/> Segurança</h3><p>Área protegida por administrador ativo da plataforma.</p></div><div className="settings-feature-card"><h3><Activity size={17}/> Integração externa</h3><p>Campos de produto, preço, cliente, status e sincronização preparados para o sistema de assinatura.</p></div></div>}
 </div>}
