import { useEffect,useMemo,useState } from 'react';
import { Activity,RefreshCw,Search,Gavel,Bot,Clock3,User,ExternalLink } from 'lucide-react';
import { supabase } from '../lib/supabase';

const dt=(v:any)=>v?new Date(v).toLocaleString('pt-BR'):'—';
export default function ProcessMovements(){
 const [rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[updated,setUpdated]=useState<Date|null>(null);
 async function load(){if(!supabase)return;setLoading(true);const {data}=await supabase.from('process_movements').select('id,process_id,movement_date,title,description,source,client_message,approved_for_client,sent_to_client_at,processes(cnj_number,internal_number,subject,clients(name))').order('movement_date',{ascending:false}).limit(1000);setRows(data||[]);setUpdated(new Date());setLoading(false)}
 useEffect(()=>{load();const id=window.setInterval(load,45000);const focus=()=>load();window.addEventListener('focus',focus);return()=>{clearInterval(id);window.removeEventListener('focus',focus)}},[]);
 const filtered=useMemo(()=>rows.filter(x=>`${x.title||''} ${x.description||''} ${x.source||''} ${x.processes?.cnj_number||''} ${x.processes?.internal_number||''} ${x.processes?.clients?.name||''}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 return <div className="module"><div className="page-head"><div><h1>Andamentos</h1><p>Todos os andamentos processuais em uma linha do tempo atualizada automaticamente.</p></div><button className="primary" onClick={load}><RefreshCw size={15}/> Atualizar agora</button></div><div className="system-bar"><span><Activity size={14}/> MONITORAMENTO PROCESSUAL</span><span className="online">● ATUALIZAÇÃO AUTOMÁTICA · 45s</span></div><div className="cards"><div className="card"><strong>{rows.length}</strong><span>Andamentos carregados</span></div><div className="card"><strong>{new Set(rows.map(x=>x.process_id)).size}</strong><span>Processos com andamento</span></div><div className="card"><strong>{rows.filter(x=>x.client_message).length}</strong><span>Com mensagem ao cliente</span></div></div><div className="table-panel"><div className="table-tools"><div className="input-search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar processo, cliente, andamento ou tribunal"/></div><span>{updated?`Atualizado ${updated.toLocaleTimeString('pt-BR')}`:'Atualizando...'}</span></div>{loading&&rows.length===0?<div className="empty">Carregando andamentos...</div>:<div className="signature-list process-movement-feed">{filtered.length===0?<div className="empty">Nenhum andamento encontrado.</div>:filtered.map(x=><a className="signature-row" key={x.id} href={`/processos?processo=${x.process_id}`}><div><strong><Gavel size={15}/> {x.title||'Movimentação processual'}</strong><small><Clock3 size={12}/> {dt(x.movement_date)} · {x.source||'fonte não informada'}</small><small><User size={12}/> {x.processes?.clients?.name||'Cliente não identificado'} · {x.processes?.cnj_number||x.processes?.internal_number||'Processo sem número'}</small>{x.description&&<p>{x.description}</p>}{x.client_message&&<div className="movement-ai"><Bot size={14}/><span><b>Comunicação preparada:</b> {x.client_message}</span></div>}</div><ExternalLink size={16}/></a>)}</div>}</div></div>
}
