import { FormEvent,useEffect,useState } from 'react';
import { CheckCircle2,Loader2,ShieldCheck } from 'lucide-react';

const ENDPOINT='https://dcpwcuototomxoiszukt.supabase.co/functions/v1/client-intake-public';
const blank:any={name:'',cpf_cnpj:'',rg:'',birth_date:'',gender:'',mother_name:'',marital_status:'',profession:'',email:'',phone:'',whatsapp:'',notes:'',address:{zip:'',street:'',number:'',complement:'',neighborhood:'',city:'',state:''}};
export default function PublicClientForm({token}:{token:string}){
 const [state,setState]=useState<'checking'|'ready'|'sending'|'success'|'invalid'>('checking'),[form,setForm]=useState<any>(blank),[error,setError]=useState(''),[office,setOffice]=useState('LEXOFFICE'),[expires,setExpires]=useState('');
 async function call(action:string,data?:any){const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token,data})});const json=await r.json().catch(()=>({}));if(!r.ok)throw new Error(json?.error||'Não foi possível processar o formulário.');return json}
 useEffect(()=>{call('validate').then(d=>{setOffice(d.organization_name||'LEXOFFICE');setExpires(d.expires_at||'');setState('ready')}).catch(e=>{setError(e.message);setState('invalid')})},[token]);
 const set=(k:string,v:string)=>setForm((f:any)=>({...f,[k]:v}));const addr=(k:string,v:string)=>setForm((f:any)=>({...f,address:{...f.address,[k]:v}}));
 async function submit(e:FormEvent){e.preventDefault();setError('');setState('sending');try{await call('submit',form);setState('success')}catch(e:any){setError(e.message);setState('ready')}}
 if(state==='checking')return <main className="public-intake-state"><Loader2 className="spin"/><h1>Validando formulário...</h1></main>;
 if(state==='invalid')return <main className="public-intake-state"><h1>Formulário indisponível</h1><p>{error||'O link expirou, já foi utilizado ou não é válido.'}</p></main>;
 if(state==='success')return <main className="public-intake-state success"><CheckCircle2/><h1>Cadastro enviado com sucesso</h1><p>Seus dados foram recebidos pelo escritório. Você já pode fechar esta página.</p></main>;
 return <main className="public-intake-page"><section className="public-intake-card"><header><div className="public-intake-logo">⚖</div><div><span>{office}</span><h1>Cadastro de cliente</h1><p>Preencha seus dados com atenção. As informações serão enviadas diretamente e com segurança ao escritório.</p></div></header><div className="public-intake-security"><ShieldCheck size={16}/> Link individual e de uso único{expires?` • válido até ${new Date(expires).toLocaleString('pt-BR')}`:''}</div>
 <form onSubmit={submit}>
  <h2>Dados pessoais</h2><div className="intake-grid">
   <label className="wide">Nome completo *<input required maxLength={180} value={form.name} onChange={e=>set('name',e.target.value)} autoComplete="name"/></label>
   <label>CPF/CNPJ<input maxLength={30} value={form.cpf_cnpj} onChange={e=>set('cpf_cnpj',e.target.value)}/></label><label>RG<input maxLength={40} value={form.rg} onChange={e=>set('rg',e.target.value)}/></label>
   <label>Data de nascimento<input type="date" value={form.birth_date} onChange={e=>set('birth_date',e.target.value)}/></label><label>Gênero<input maxLength={40} value={form.gender} onChange={e=>set('gender',e.target.value)}/></label>
   <label className="wide">Nome da mãe<input maxLength={180} value={form.mother_name} onChange={e=>set('mother_name',e.target.value)}/></label><label>Estado civil<select value={form.marital_status} onChange={e=>set('marital_status',e.target.value)}><option value="">Selecione</option><option value="single">Solteiro(a)</option><option value="married">Casado(a)</option><option value="divorced">Divorciado(a)</option><option value="widowed">Viúvo(a)</option><option value="separated">Separado(a)</option></select></label><label>Profissão<input maxLength={120} value={form.profession} onChange={e=>set('profession',e.target.value)}/></label>
  </div>
  <h2>Contato</h2><div className="intake-grid"><label>E-mail<input type="email" maxLength={254} value={form.email} onChange={e=>set('email',e.target.value)} autoComplete="email"/></label><label>Telefone<input maxLength={40} value={form.phone} onChange={e=>set('phone',e.target.value)} autoComplete="tel"/></label><label className="wide">WhatsApp<input maxLength={40} value={form.whatsapp} onChange={e=>set('whatsapp',e.target.value)}/></label></div>
  <h2>Endereço</h2><div className="intake-grid"><label>CEP<input maxLength={12} value={form.address.zip} onChange={e=>addr('zip',e.target.value)}/></label><label className="wide">Rua / Avenida<input maxLength={180} value={form.address.street} onChange={e=>addr('street',e.target.value)}/></label><label>Número<input maxLength={30} value={form.address.number} onChange={e=>addr('number',e.target.value)}/></label><label>Complemento<input maxLength={120} value={form.address.complement} onChange={e=>addr('complement',e.target.value)}/></label><label>Bairro<input maxLength={120} value={form.address.neighborhood} onChange={e=>addr('neighborhood',e.target.value)}/></label><label>Cidade<input maxLength={120} value={form.address.city} onChange={e=>addr('city',e.target.value)}/></label><label>UF<input maxLength={2} value={form.address.state} onChange={e=>addr('state',e.target.value.toUpperCase())}/></label></div>
  <h2>Observações</h2><label>Informações adicionais<textarea maxLength={4000} value={form.notes} onChange={e=>set('notes',e.target.value)} placeholder="Se desejar, escreva aqui alguma informação importante para o escritório."/></label>
  {error&&<div className="public-intake-error" role="alert">{error}</div>}<button className="public-intake-submit" disabled={state==='sending'}>{state==='sending'?<><Loader2 className="spin" size={18}/> Enviando...</>:<>Enviar cadastro</>}</button><p className="public-intake-privacy">Ao enviar, os dados serão armazenados no cadastro interno do escritório para atendimento jurídico.</p>
 </form></section></main>;
}
