import { Check, Scale, Sparkles, ShieldCheck } from 'lucide-react';
const plans=[
{name:'Essencial',key:'essencial',price:'149',annual:'119',features:['1 usuário','Até 100 processos','CRM e clientes','Processos e prazos','Agenda e documentos']},
{name:'Profissional',key:'profissional',price:'299',annual:'239',featured:true,features:['Até 3 usuários','Até 500 processos','Financeiro e cobranças','Assinatura eletrônica','WhatsApp + 2 agentes de IA','300 conversas/mês']},
{name:'Avançado',key:'avancado',price:'499',annual:'399',features:['Até 10 usuários','Processos ilimitados','Todos os agentes de IA','Investigação PRO','24 Calculadoras PRO','Escavador e Marketing']},
{name:'Enterprise',key:'enterprise',features:['Usuários ilimitados','Múltiplas OABs','Tudo do Avançado','IA premium','Customização e suporte prioritário']}
];
const go=(key:string)=>{window.location.href=key==='enterprise'?'/checkout?plano=enterprise':`/checkout?plano=${key}`};
export default function PublicPlans(){return <div style={page}><section style={hero}><div style={justice}><Scale size={500} strokeWidth={.6}/></div><div style={{position:'relative',maxWidth:900}}><b style={{letterSpacing:3}}><Scale size={22} style={{verticalAlign:'middle',marginRight:8}}/>LEX<span style={{color:'#c83257'}}>OFFICE</span></b><h1 style={title}>Seu escritório.<br/>Uma nova inteligência.</h1><p style={lead}>Gestão, processos, atendimento, financeiro e inteligência artificial reunidos em um único ecossistema jurídico.</p><button style={button} onClick={()=>go('profissional')}>TESTE GRÁTIS POR 7 DIAS</button> <a href="#planos" style={outline}>CONHECER OS PLANOS</a><small style={{display:'block',color:'#818b97',marginTop:14}}>Sem cartão de crédito para iniciar o teste.</small></div></section><section id="planos" style={{maxWidth:1200,margin:'0 auto',padding:'70px 20px'}}><div style={{textAlign:'center',marginBottom:35}}><span style={{color:'#d24c6c',fontWeight:800}}>PLANOS LEXOFFICE</span><h2 style={{fontSize:38,margin:'9px 0'}}>Escolha a estrutura do seu escritório</h2><p style={{color:'#919ba7'}}>Preço Fundador para o lançamento. Economize no pagamento anual.</p></div><div style={grid}>{plans.map(p=><article key={p.key} style={{...card,border:p.featured?'1px solid #c83257':'1px solid #2b333d'}}>{p.featured&&<span style={{color:'#e15b79',fontSize:11,fontWeight:900}}>MAIS ESCOLHIDO</span>}<h3 style={{fontSize:24}}>{p.name}</h3>{p.price?<><div><strong style={{fontSize:42}}>R$ {p.price}</strong><span style={{color:'#89939f'}}>/mês</span></div><small style={{color:'#89939f'}}>Anual: equivalente a R$ {p.annual}/mês</small></>:<strong style={{fontSize:28}}>Sob consulta</strong>}<button style={{...button,width:'100%',margin:'22px 0'}} onClick={()=>go(p.key)}>{p.key==='enterprise'?'FALAR COM ESPECIALISTA':'ESCOLHER '+p.name.toUpperCase()}</button>{p.features.map(f=><p key={f} style={{display:'flex',gap:8,color:'#c4cbd3',fontSize:14}}><Check size={16} color="#d24c6c"/>{f}</p>)}</article>)}</div><div style={addons}><div style={addon}><Sparkles/><span><b>Calculadoras PRO</b><small style={{display:'block',color:'#8d97a3'}}>24 calculadoras, PDFs e relatórios</small></span><strong>R$ 69/mês</strong></div><div style={addon}><ShieldCheck/><span><b>Investigação PRO</b><small style={{display:'block',color:'#8d97a3'}}>Consultas e fontes integradas</small></span><strong>R$ 99/mês</strong></div></div><p style={{textAlign:'center',color:'#929ca8',marginTop:35}}>Pagamento por <b style={{color:'#fff'}}>PIX, boleto ou cartão</b>. Ativação após confirmação.</p></section></div>}
const page:React.CSSProperties={minHeight:'100vh',background:'#0d1117',color:'#f5f7fa',fontFamily:'Inter,Segoe UI,Arial,sans-serif'};
const hero:React.CSSProperties={position:'relative',minHeight:540,display:'grid',placeItems:'center',padding:'60px 20px',textAlign:'center',overflow:'hidden'};
const justice:React.CSSProperties={position:'absolute',inset:0,display:'grid',placeItems:'center',opacity:.055};
const title:React.CSSProperties={fontSize:'clamp(42px,7vw,76px)',lineHeight:1.03,letterSpacing:'-.04em',margin:'30px 0 18px'};
const lead:React.CSSProperties={maxWidth:700,margin:'0 auto 28px',color:'#aeb7c2',fontSize:20,lineHeight:1.6};
const button:React.CSSProperties={border:'1px solid #d44a6b',borderRadius:10,background:'linear-gradient(135deg,#bd294d,#8f1c39)',color:'#fff',fontWeight:900,padding:'14px 20px',cursor:'pointer'};
const outline:React.CSSProperties={...button,display:'inline-block',background:'#171d24',border:'1px solid #39434f',textDecoration:'none'};
const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(245px,1fr))',gap:16};
const card:React.CSSProperties={background:'#151b22',borderRadius:18,padding:25};
const addons:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16,marginTop:24};
const addon:React.CSSProperties={display:'grid',gridTemplateColumns:'auto 1fr auto',gap:14,alignItems:'center',background:'#151b22',border:'1px solid #2b333d',borderRadius:14,padding:20};