import { useEffect,useState } from 'react';
import { Save,Upload,Image as ImageIcon,Building2,Users,Headphones,Bot,CalendarDays,Plug,ShieldCheck,Clock3,MessageCircle,Tags,Workflow,UserPlus,Building,KeyRound,ArrowUpRight } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { humanize,roleLabels } from '../lib/ux';
import Integrations from './Integrations';

const empty={organization_name:'',trade_name:'',document_number:'',email:'',phone:'',whatsapp:'',website:'',timezone:'America/Sao_Paulo',locale:'pt-BR',logo_storage_path:'',primary_color:'#8f1c3b',secondary_color:'#5b1022'};
const baseSections=[['office','Escritório',Building2],['team','Equipe',Users],['service','Atendimento',Headphones],['ai','IA',Bot],['agenda','Agenda',CalendarDays],['connections','Conexões',Plug],['security','Segurança',ShieldCheck]] as const;
const roles=[['admin','Administrador'],['lawyer','Advogado(a)'],['responsible_lawyer','Advogado(a) responsável'],['assistant','Assistente'],['finance','Financeiro'],['marketing','Marketing'],['supervisor','Supervisor'],['support','Atendimento'],['custom','Personalizado']] as const;
export default function Settings(){
 const [form,setForm]=useState<any>(empty),[orgId,setOrgId]=useState(''),[id,setId]=useState(''),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[logoUrl,setLogoUrl]=useState(''),[notice,setNotice]=useState(''),[section,setSection]=useState('office');
 const [isPlatformAdmin,setIsPlatformAdmin]=useState(false),[members,setMembers]=useState<any[]>([]),[adminNotice,setAdminNotice]=useState(''),[creatingUser,setCreatingUser]=useState(false),[resettingUser,setResettingUser]=useState('');
 const [userForm,setUserForm]=useState<any>({name:'',email:'',password:'',role_key:'lawyer',phone:'',title:'',oab_number:'',oab_uf:''});
 const sections:any[]=[...baseSections,...(isPlatformAdmin?[['administration','Administração',Building] as const]:[])];
 async function loadMembers(oid=orgId){if(!supabase||!oid)return;const {data}=await supabase.from('profiles').select('id,name,email,phone,title,role_key,status,created_at').eq('org_id',oid).order('name');setMembers(data||[])}
 useEffect(()=>{(async()=>{if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:p}=await supabase.from('profiles').select('org_id,name,email,phone').eq('id',user.id).maybeSingle();if(!p?.org_id)return;setOrgId(p.org_id);const {data:pa}=await supabase.from('platform_admins').select('user_id').eq('user_id',user.id).eq('status','active').maybeSingle();setIsPlatformAdmin(!!pa);const {data:o}=await supabase.from('organizations').select('name').eq('id',p.org_id).maybeSingle();const {data:s}=await supabase.from('organization_settings').select('id,organization_name,trade_name,document_number,email,phone,whatsapp,website,timezone,locale,logo_storage_path,primary_color,secondary_color').eq('org_id',p.org_id).maybeSingle();if(s){setId(s.id);setForm({...empty,...s});if(s.logo_storage_path){const {data:u}=await supabase.storage.from('lexoffice-documents').createSignedUrl(s.logo_storage_path,3600);setLogoUrl(u?.signedUrl||'')}}else setForm({...empty,organization_name:o?.name||'',trade_name:o?.name||'',email:p.email||'',phone:p.phone||''});await loadMembers(p.org_id)})()},[]);
 function change(k:string,v:string){setForm((x:any)=>({...x,[k]:v}))}
 async function uploadLogo(file?:File){if(!supabase||!orgId||!file)return;if(!file.type.startsWith('image/')){setNotice('Selecione um arquivo de imagem para a logo.');return}setUploading(true);setNotice('');const ext=(file.name.split('.').pop()||'png').toLowerCase();const path=`${orgId}/branding/logo.${ext}`;const {error}=await supabase.storage.from('lexoffice-documents').upload(path,file,{upsert:true,contentType:file.type});if(error){setNotice('Não foi possível enviar a logo: '+error.message);setUploading(false);return}setForm((x:any)=>({...x,logo_storage_path:path}));const {data:u}=await supabase.storage.from('lexoffice-documents').createSignedUrl(path,3600);setLogoUrl(u?.signedUrl||'');setUploading(false);setNotice('Logo carregada. Clique em Salvar para aplicar ao timbrado.')}
 async function save(){if(!supabase||!orgId)return;setSaving(true);setNotice('');const payload={org_id:orgId,organization_name:form.organization_name||null,trade_name:form.trade_name||null,document_number:form.document_number||null,email:form.email||null,phone:form.phone||null,whatsapp:form.whatsapp||null,website:form.website||null,timezone:form.timezone||'America/Sao_Paulo',locale:form.locale||'pt-BR',logo_storage_path:form.logo_storage_path||null,primary_color:form.primary_color||'#8f1c3b',secondary_color:form.secondary_color||'#5b1022',updated_at:new Date().toISOString()};const q=id?supabase.from('organization_settings').update(payload).eq('id',id).select('id').single():supabase.from('organization_settings').insert(payload).select('id').single();const {data,error}=await q as any;if(!error&&data?.id)setId(data.id);setNotice(error?'Não foi possível salvar as configurações: '+error.message:'Configurações e identidade visual salvas com sucesso.');setSaving(false)}
 async function createUser(e:any){e.preventDefault();if(!supabase||!orgId)return;setCreatingUser(true);setAdminNotice('');const {data,error}=await supabase.functions.invoke('create-user',{body:{...userForm,org_id:orgId}});if(error||data?.error)setAdminNotice('Não foi possível criar o usuário: '+(data?.error||error?.message||'erro desconhecido'));else{setAdminNotice('Usuário criado com sucesso.');setUserForm({name:'',email:'',password:'',role_key:'lawyer',phone:'',title:'',oab_number:'',oab_uf:''});await loadMembers()}setCreatingUser(false)}
 async function resetPassword(member:any){if(!supabase||!member?.id)return;const newPassword=window.prompt(`Digite uma nova senha temporária para ${member.name||member.email}.\nA senha deve ter pelo menos 8 caracteres.`);if(newPassword===null)return;if(newPassword.length<8){setAdminNotice('A nova senha deve ter pelo menos 8 caracteres.');return}const confirmPassword=window.prompt('Confirme a nova senha temporária:');if(confirmPassword===null)return;if(confirmPassword!==newPassword){setAdminNotice('As senhas informadas não coincidem.');return}setResettingUser(member.id);setAdminNotice('');const {data,error}=await supabase.functions.invoke('reset-user-password',{body:{user_id:member.id,new_password:newPassword}});if(error||data?.error)setAdminNotice('Não foi possível redefinir a senha: '+(data?.error||error?.message||'erro desconhecido'));else setAdminNotice(`Senha de ${member.email} redefinida com sucesso.`);setResettingUser('')}
 const go=(path:string)=>{location.href=path};
 return <div className="module"><div className="page-head"><div><h1>Configurações</h1><p>Empresa, equipe, atendimento, inteligência e conexões do escritório</p></div>{section==='office'&&<button className="primary" onClick={save} disabled={saving}><Save size={15}/>{saving?'Salvando...':'Salvar'}</button>}</div><div className="settings-section-nav">{sections.map(([k,l,I])=><button key={k} className={section===k?'active':''} onClick={()=>setSection(k)}><I size={15}/> {l}</button>)}</div>
 {section==='office'&&<div className="module-box settings-panel"><h3><ImageIcon size={16}/> Identidade do escritório</h3><div className="form-grid"><label>Logo / timbrado<div style={{display:'flex',alignItems:'center',gap:12,marginTop:8}}>{logoUrl?<img src={logoUrl} alt="Logo do escritório" style={{width:68,height:68,objectFit:'contain',borderRadius:12,background:'#fff',padding:6}}/>:<div style={{width:68,height:68,border:'1px dashed #394252',borderRadius:12,display:'grid',placeItems:'center',fontWeight:700}}>SF</div>}<label className="secondary" style={{cursor:'pointer',display:'inline-flex',alignItems:'center',gap:8,padding:'9px 12px'}}><Upload size={15}/>{uploading?'Enviando...':'Escolher logo'}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" style={{display:'none'}} disabled={uploading} onChange={e=>uploadLogo(e.target.files?.[0])}/></label></div></label><label>Cor principal<input type="color" value={form.primary_color||'#8f1c3b'} onChange={e=>change('primary_color',e.target.value)}/></label><label>Cor secundária<input type="color" value={form.secondary_color||'#5b1022'} onChange={e=>change('secondary_color',e.target.value)}/></label></div><h3 style={{marginTop:24}}>Dados institucionais</h3><div className="form-grid"><label>Razão social<input value={form.organization_name} onChange={e=>change('organization_name',e.target.value)}/></label><label>Nome fantasia<input value={form.trade_name} onChange={e=>change('trade_name',e.target.value)}/></label><label>CPF/CNPJ<input value={form.document_number} onChange={e=>change('document_number',e.target.value)}/></label><label>E-mail<input type="email" value={form.email} onChange={e=>change('email',e.target.value)}/></label><label>Telefone<input value={form.phone} onChange={e=>change('phone',e.target.value)}/></label><label>WhatsApp<input value={form.whatsapp} onChange={e=>change('whatsapp',e.target.value)}/></label><label>Website<input value={form.website} onChange={e=>change('website',e.target.value)}/></label><label>Fuso horário<select value={form.timezone} onChange={e=>change('timezone',e.target.value)}><option value="America/Sao_Paulo">Brasília / São Paulo</option><option value="America/Manaus">Manaus</option><option value="America/Rio_Branco">Rio Branco</option></select></label><label>Idioma<select value={form.locale} onChange={e=>change('locale',e.target.value)}><option value="pt-BR">Português (Brasil)</option></select></label></div>{notice&&<div className="login-notice" role="status">{notice}</div>}</div>}
 {section==='team'&&<div className="settings-feature-grid"><form className="settings-feature-card wide" onSubmit={createUser}><h3><UserPlus size={17}/> Novo usuário</h3><p>Cadastre um membro diretamente na organização atual. A conta é criada com acesso isolado a este escritório.</p><div className="form-grid"><label>Nome completo<input value={userForm.name} onChange={e=>setUserForm({...userForm,name:e.target.value})} required/></label><label>E-mail<input type="email" value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})} required/></label><label>Senha temporária<input type="password" minLength={8} value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})} required/></label><label>Perfil<select value={userForm.role_key} onChange={e=>setUserForm({...userForm,role_key:e.target.value})}>{roles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Telefone<input value={userForm.phone} onChange={e=>setUserForm({...userForm,phone:e.target.value})}/></label><label>Cargo / função<input value={userForm.title} onChange={e=>setUserForm({...userForm,title:e.target.value})}/></label><label>OAB<input value={userForm.oab_number} onChange={e=>setUserForm({...userForm,oab_number:e.target.value})}/></label><label>UF da OAB<input maxLength={2} value={userForm.oab_uf} onChange={e=>setUserForm({...userForm,oab_uf:e.target.value.toUpperCase()})}/></label></div><button className="integration-action" disabled={creatingUser}><UserPlus size={15}/>{creatingUser?'Criando...':'Criar usuário'}</button></form><div className="settings-feature-card wide"><h3><Users size={17}/> Usuários do escritório</h3><p>{members.length} usuário(s) cadastrado(s) nesta organização.</p><div style={{display:'grid',gap:8,marginTop:12}}>{members.map(m=><div key={m.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,padding:'12px 14px',border:'1px solid #303846',borderRadius:10,background:'#101722'}}><div><strong>{m.name}</strong><div style={{opacity:.72,fontSize:13}}>{m.email}{m.title?' • '+m.title:''}</div></div><div style={{display:'flex',alignItems:'center',gap:8,flexWrap:'wrap',justifyContent:'flex-end'}}><span className="settings-chip ready">{humanize(m.role_key,roleLabels)}</span><button className="secondary" type="button" disabled={resettingUser===m.id} onClick={()=>resetPassword(m)}><KeyRound size={14}/>{resettingUser===m.id?'Redefinindo...':'Redefinir senha'}</button></div></div>)}</div></div><div className="settings-feature-card"><h3><ShieldCheck size={17}/> Perfis e segurança</h3><p>Controle acesso por função e mantenha os dados de cada organização isolados.</p><button className="secondary" type="button" onClick={()=>go('/seguranca')}>Abrir Segurança</button></div>{adminNotice&&<div className="login-notice" style={{gridColumn:'1/-1'}} role="status">{adminNotice}</div>}</div>}
 {section==='administration'&&isPlatformAdmin&&<div className="settings-feature-grid"><div className="settings-feature-card wide"><h3><Building size={17}/> Administração da plataforma</h3><p>Organizações, usuários globais, assinaturas, auditoria e saúde do sistema ficam concentrados no console administrativo do LEXOFFICE. Este é o ponto oficial para administrar a plataforma.</p><button className="integration-action" type="button" onClick={()=>go('/admin')}><ArrowUpRight size={15}/> Abrir LEXOFFICE Admin</button></div></div>}
 {section==='service'&&<div className="settings-feature-grid"><div className="settings-feature-card"><h3><Clock3 size={17}/> SLA e horário de atendimento</h3><p>Centralize o tempo de resposta e os horários usados pelos fluxos de atendimento.</p><div className="settings-chip-row"><span className="settings-chip ready">Atendimento humano</span><span className="settings-chip">Fora do expediente</span></div><button className="integration-action" onClick={()=>go('/atendimento')}>Configurar atendimento</button></div><div className="settings-feature-card"><h3><MessageCircle size={17}/> Templates e canais</h3><p>Mensagens, WhatsApp e canais conectados ficam acessíveis sem duplicar configurações.</p><button className="secondary" onClick={()=>go('/whatsapp')}>Abrir canais</button></div><div className="settings-feature-card wide"><h3><Tags size={17}/> Tags e organização</h3><p>Use CRM e atendimento para classificar leads, clientes e conversas. As configurações continuam ligadas aos dados reais do LEXOFFICE.</p><button className="secondary" onClick={()=>go('/crm')}>Abrir CRM</button></div></div>}
 {section==='ai'&&<div className="settings-feature-grid"><div className="settings-feature-card"><h3><Bot size={17}/> Agentes e provedores de IA</h3><p>Configure agentes e escolha provedores com política de gratuito primeiro.</p><div className="settings-chip-row"><span className="settings-chip ready">Groq</span><span className="settings-chip ready">Gemini</span><span className="settings-chip ready">OpenRouter</span><span className="settings-chip">Ollama</span><span className="settings-chip">OpenAI</span></div><button className="integration-action" onClick={()=>go('/agentes-ia')}>Configurar IA</button></div><div className="settings-feature-card"><h3><Workflow size={17}/> Follow-up automático</h3><p>O acompanhamento automático deve usar os agentes e o CRM, sem criar uma automação paralela ou simulada.</p><button className="secondary" onClick={()=>go('/agentes-ia')}>Abrir automações dos agentes</button></div><div className="settings-note">As chaves de IA permanecem protegidas no backend/Vault. Esta tela não exibe segredos.</div></div>}
 {section==='agenda'&&<div className="settings-feature-grid"><div className="settings-feature-card"><h3><CalendarDays size={17}/> Agenda e disponibilidade</h3><p>Horários, compromissos e integrações de calendário ficam concentrados na Agenda.</p><button className="integration-action" onClick={()=>go('/agenda')}>Abrir Agenda</button></div><div className="settings-feature-card"><h3><Clock3 size={17}/> Regras de agendamento</h3><p>Use a disponibilidade real do escritório para evitar horários duplicados e conflitos.</p><button className="secondary" onClick={()=>go('/agenda')}>Gerenciar horários</button></div></div>}
 {section==='connections'&&<Integrations embedded/>}
 {section==='security'&&<div className="settings-feature-grid"><div className="settings-feature-card wide"><h3><ShieldCheck size={17}/> Segurança e permissões</h3><p>Auditoria, acessos e isolamento entre organizações continuam concentrados no módulo Segurança.</p><button className="integration-action" onClick={()=>go('/seguranca')}>Abrir Segurança</button></div></div>}
 </div>}
