import { useEffect,useState } from 'react';
import { Send,PenTool,RefreshCw,ShieldCheck,KeyRound } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './integrations.css';

type RequestRow={id:string;title?:string|null;status?:string|null;external_id?:string|null;sent_at?:string|null;expires_at?:string|null;document_id?:string|null;created_at?:string|null};
export default function Signatures(){
 const [rows,setRows]=useState<RequestRow[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[notice,setNotice]=useState(''),[accountEmail,setAccountEmail]=useState(''),[token,setToken]=useState(''),[configured,setConfigured]=useState(false),[integrationStatus,setIntegrationStatus]=useState('não configurada');
 async function load(){if(!supabase)return;setLoading(true);setNotice('');const [{data,error},{data:cfg,error:cfgError}]=await Promise.all([supabase.from('signature_requests').select('id,title,status,external_id,sent_at,expires_at,document_id,created_at').order('created_at',{ascending:false}),supabase.functions.invoke('zapsign-configure',{body:{action:'status'}})]);if(error)setNotice(error.message);else setRows((data||[]) as RequestRow[]);if(!cfgError&&cfg){setConfigured(Boolean((cfg as any).configured));setIntegrationStatus((cfg as any).status||'não configurada');setAccountEmail((cfg as any).account_email||'')}setLoading(false)}
 useEffect(()=>{load()},[]);
 async function saveConfig(){if(!supabase||!token.trim())return;setBusy('config');setNotice('');const {data,error}=await supabase.functions.invoke('zapsign-configure',{body:{account_email:accountEmail.trim(),token:token.trim()}});if(error)setNotice(error.message);else if((data as any)?.error)setNotice((data as any).error);else{setConfigured(true);setIntegrationStatus('configured');setToken('');setNotice('ZapSign configurada. A credencial foi armazenada no cofre seguro do servidor.')}setBusy(null)}
 async function send(id:string){if(!supabase)return;setBusy(id);setNotice('');const {data,error}=await supabase.functions.invoke('zapsign-send-signature',{body:{signature_request_id:id}});if(error)setNotice(error.message);else if((data as any)?.error)setNotice((data as any).error);else{setNotice('Documento enviado para assinatura pela ZapSign.');await load()}setBusy(null)}
 return <><div className="page-title"><h1>Assinaturas</h1><p>Solicitações de assinatura eletrônica integradas à ZapSign.</p></div><div className="integration-head"><div><span className="integration-pill"><PenTool size={14}/> ZAPSIGN</span><h2>Central de assinaturas</h2><p>Configure a conta, envie documentos e acompanhe o status das solicitações.</p></div><button className="integration-action" onClick={load}><RefreshCw size={16}/>Atualizar</button></div>{notice&&<div className="integration-notice">{notice}</div>}<div className="integration-panel"><h3><KeyRound size={17}/> Configuração ZapSign</h3><div className="integration-form"><label>E-mail da conta<input type="email" value={accountEmail} onChange={e=>setAccountEmail(e.target.value)} placeholder="conta@escritorio.com"/></label><label>Token / API key (senha de integração)<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder={configured?'•••••••• configurado':'Cole o token da ZapSign'}/></label><label>Status<input value={configured?`Configurada • ${integrationStatus}`:'Não configurada'} readOnly/></label><button className="integration-action" onClick={saveConfig} disabled={busy==='config'||!token.trim()}><ShieldCheck size={16}/>{busy==='config'?'Salvando...':'Salvar integração'}</button></div></div><div className="integration-panel">{loading?<p>Carregando solicitações...</p>:rows.length===0?<div className="integration-empty"><PenTool size={30}/><h3>Nenhuma solicitação encontrada</h3><p>As solicitações criadas no LEXOFFICE aparecerão aqui para envio à ZapSign.</p></div>:<div className="signature-list">{rows.map(r=><div className="signature-row" key={r.id}><div><strong>{r.title||'Documento para assinatura'}</strong><small>Status: {r.status||'pendente'}{r.expires_at?` • vence ${new Date(r.expires_at).toLocaleDateString('pt-BR')}`:''}</small></div><div className="signature-actions"><span className={`status-dot ${r.status==='signed'?'ok':''}`}>{r.status||'pending'}</span>{!r.external_id&&r.status!=='sent'&&r.status!=='signed'&&<button className="integration-action" disabled={busy===r.id||!r.document_id||!configured} onClick={()=>send(r.id)}><Send size={15}/>{busy===r.id?'Enviando...':'Enviar ZapSign'}</button>}</div></div>)}</div>}</div></>
}
