import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock3, FileCheck2, FileText, KeyRound, Mail, MessageCircle, Plug, RefreshCw, Send, Settings2, ShieldCheck, Upload, Usb, UserRound, Wifi, WifiOff } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './signatures-clicksign.css';

type Row={id:string;title?:string|null;status?:string|null;signer_name?:string|null;created_at?:string|null;sent_at?:string|null;signed_at?:string|null;provider?:string|null;document_id?:string|null;client_id?:string|null;process_id?:string|null;signed_document_id?:string|null;signed_file_captured_at?:string|null;icp_validated_document_id?:string|null;icp_validated_at?:string|null};
type Client={id:string;name:string;email?:string|null;phone?:string|null;whatsapp?:string|null;cpf_cnpj?:string|null};
type Process={id:string;client_id?:string|null;cnj_number?:string|null;internal_number?:string|null;subject?:string|null;status?:string|null};
type DocumentRow={id:string;name:string;file_path?:string|null;client_id?:string|null;process_id?:string|null;mime_type?:string|null};
type LocalCert={subject:string;issuer:string;serial?:string;fingerprint:string;notBefore?:string;notAfter?:string};
type Status={configured:boolean;status?:string;account_email?:string;last_error?:string|null;last_sync_at?:string|null};

const BRIDGE='http://127.0.0.1:17681';
const ICP_POLICY_OID='2.16.76.1.7.1.11.1.3';
const pt=(v?:string|null)=>v?new Date(v).toLocaleString('pt-BR'):'—';
const label=(v?:string|null)=>({signed:'Assinado pelo cliente',sent:'Aguardando cliente',viewed:'Visualizado',draft:'Aguardando envio',cancelled:'Cancelado',pending:'Pendente',declined:'Recusado',expired:'Expirado'} as any)[(v||'').toLowerCase()]||v||'Registrado';
const cn=(dn?:string)=>{if(!dn)return '';const part=dn.split(',').map(x=>x.trim()).find(x=>x.startsWith('CN='));return part?part.slice(3):dn};
const hex=(b:ArrayBuffer)=>Array.from(new Uint8Array(b)).map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase();

export default function Signatures(){
 const[tab,setTab]=useState<'send'|'track'|'config'>('send'),[rows,setRows]=useState<Row[]>([]),[clients,setClients]=useState<Client[]>([]),[processes,setProcesses]=useState<Process[]>([]),[documents,setDocuments]=useState<DocumentRow[]>([]),[status,setStatus]=useState<Status>({configured:false}),[notice,setNotice]=useState(''),[busy,setBusy]=useState<string|null>(null);
 const[token,setToken]=useState(''),[accountEmail,setAccountEmail]=useState('');
 const[clientId,setClientId]=useState(''),[processId,setProcessId]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[cpf,setCpf]=useState(''),[files,setFiles]=useState<File[]>([]),[authType,setAuthType]=useState('screen'),[delivery,setDelivery]=useState<'whatsapp'|'email'>('email');
 const[bridgeOnline,setBridgeOnline]=useState(false),[bridgeVersion,setBridgeVersion]=useState(''),[certs,setCerts]=useState<LocalCert[]>([]),[certFingerprint,setCertFingerprint]=useState(''),[visibleSeal,setVisibleSeal]=useState(true);

 async function loadStatus(show=false){if(!supabase)return;const{data,error}=await supabase.functions.invoke('zapsign-configure',{body:{action:'status'}});if(data)setStatus(data as Status);if(show)setNotice(error?.message||((data as any)?.configured?'ZapSign configurada e pronta para envio.':'ZapSign ainda não está configurada.'))}
 async function load(){if(!supabase)return;const[{data:r,error:re},{data:c,error:ce},{data:p,error:pe},{data:d,error:de}]=await Promise.all([
   supabase.from('signature_requests').select('id,title,status,signer_name,created_at,sent_at,signed_at,provider,document_id,client_id,process_id,signed_document_id,signed_file_captured_at,icp_validated_document_id,icp_validated_at').order('created_at',{ascending:false}).limit(300),
   supabase.from('clients').select('id,name,email,phone,whatsapp,cpf_cnpj').order('name').limit(1000),
   supabase.from('processes').select('id,client_id,cnj_number,internal_number,subject,status').order('created_at',{ascending:false}).limit(2000),
   supabase.from('documents').select('id,name,file_path,client_id,process_id,mime_type').eq('mime_type','application/pdf').order('created_at',{ascending:false}).limit(2000)
 ]);if(re||ce||pe||de)setNotice(re?.message||ce?.message||pe?.message||de?.message||'Falha ao carregar assinaturas.');setRows((r||[]) as Row[]);setClients((c||[]) as Client[]);setProcesses((p||[]) as Process[]);setDocuments((d||[]) as DocumentRow[]);await loadStatus(false)}
 useEffect(()=>{load();checkBridge(false)},[]);

 function chooseClient(id:string){setClientId(id);setProcessId('');const c=clients.find(x=>x.id===id);if(c){setName(c.name||'');setEmail(c.email||'');setPhone(c.whatsapp||c.phone||'');setCpf(c.cpf_cnpj||'');if(c.email)setDelivery('email');else if(c.whatsapp||c.phone)setDelivery('whatsapp');const ps=processes.filter(p=>p.client_id===id);if(ps.length===1)setProcessId(ps[0].id)}}
 async function connect(){if(!supabase||!token.trim())return;setBusy('config');setNotice('Salvando credencial ZapSign…');const{data,error}=await supabase.functions.invoke('zapsign-configure',{body:{token:token.trim(),account_email:accountEmail.trim()}});setBusy(null);if(error||(data as any)?.error){setNotice((data as any)?.error||error?.message||'Falha na conexão.');return}setToken('');setNotice((data as any)?.message||'ZapSign configurada.');await loadStatus(false)}

 async function send(){if(!supabase)return;if(!files.length){setNotice('Etapa 2: selecione pelo menos um PDF.');return}if(!name.trim()){setNotice('Etapa 1: informe ou selecione o destinatário.');return}if(!email.trim()&&!phone.trim()){setNotice('Informe ao menos e-mail ou WhatsApp do signatário.');return}setBusy('send');setNotice('Preparando documento para envio pela ZapSign…');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão inválida.');const{data:p,error:pe}=await supabase.from('profiles').select('org_id').eq('id',user.id).single();if(pe||!p?.org_id)throw pe||new Error('Organização não encontrada.');for(const f of files){if((f.type&&f.type!=='application/pdf')&&!f.name.toLowerCase().endsWith('.pdf'))throw new Error(`${f.name} não é um PDF.`);const safe=f.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const path=`${p.org_id}/signatures/zapsign/${Date.now()}-${crypto.randomUUID()}-${safe}`;const{error:ue}=await supabase.storage.from('lexoffice-documents').upload(path,f,{contentType:'application/pdf'});if(ue)throw ue;const{data:d,error:de}=await supabase.from('documents').insert({org_id:p.org_id,client_id:clientId||null,process_id:processId||null,name:f.name,file_path:path,mime_type:'application/pdf',size_bytes:f.size,category:'Documento para assinatura',notes:'Enviado ao cliente para assinatura eletrônica pela ZapSign',uploaded_by:user.id}).select('id').single();if(de)throw de;const{data:req,error:rq}=await supabase.from('signature_requests').insert({org_id:p.org_id,owner_user_id:user.id,document_id:d.id,client_id:clientId||null,process_id:processId||null,title:f.name,status:'draft',provider:'zapsign',signer_name:name.trim(),signer_email:email.trim()||null,signer_phone:phone.trim()||null}).select('id').single();if(rq)throw rq;const{data,error}=await supabase.functions.invoke('zapsign-send-signature',{body:{signature_request_id:req.id,signer:{name:name.trim(),email:email.trim()||null,phone:phone.trim()||null,document_number:cpf.trim()||null}}});if(error||(data as any)?.error)throw new Error((data as any)?.error||error?.message||'Falha no envio pela ZapSign.')}setNotice('✅ Documento(s) enviado(s) ao cliente pela ZapSign. A assinatura A3 da Dra. Suzanne só será liberada depois que o PDF final do cliente for capturado.');setFiles([]);setTab('track');await load()}catch(e:any){setNotice(`❌ ${e?.message||'Falha ao enviar documentos.'}`)}finally{setBusy(null)}}

 async function checkBridge(show=true){setBusy('bridge');try{const response=await fetch(`${BRIDGE}/health`,{signal:AbortSignal.timeout(4000)});if(!response.ok)throw new Error('Ponte indisponível');const h=await response.json();if(!h?.ok)throw new Error('Resposta inválida da ponte');if(h?.policy_oid&&h.policy_oid!==ICP_POLICY_OID)throw new Error(`Política PAdES inesperada: ${h.policy_oid}`);setBridgeOnline(true);setBridgeVersion(String(h.version||''));if(show)setNotice(`Ponte A3 conectada${h.version?` • versão ${h.version}`:''} • PAdES AD-RB 1.3.`)}catch(e:any){setBridgeOnline(false);setCerts([]);setCertFingerprint('');if(show)setNotice('Ponte ICP-Brasil não encontrada em 127.0.0.1:17681. Abra o programa local da ponte e tente novamente.')}finally{setBusy(null)}}
 async function bridgeNonce(){const r=await fetch(`${BRIDGE}/challenge`,{signal:AbortSignal.timeout(4000)});if(!r.ok)throw new Error((await r.text())||'Não foi possível autorizar a ponte local.');const j=await r.json();if(!j?.nonce)throw new Error('Challenge da ponte inválido.');return String(j.nonce)}
 async function loadCertificates(){if(!bridgeOnline){setNotice('Verifique a ponte antes de acessar o token A3.');return}setBusy('certs');setNotice('A janela de PIN será exibida somente no seu computador. O PIN não passa pelo navegador.');try{const nonce=await bridgeNonce();const r=await fetch(`${BRIDGE}/certificates`,{headers:{'X-Lexoffice-Nonce':nonce},signal:AbortSignal.timeout(90000)});const raw=await r.text();let j:any={};try{j=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(j?.error||raw||'Não foi possível acessar o token A3.');const list=(Array.isArray(j)?j:j.certificates||[]) as LocalCert[];setCerts(list);setCertFingerprint(prev=>list.some(c=>c.fingerprint===prev)?prev:(list[0]?.fingerprint||''));setNotice(list.length?`${list.length} certificado(s) com chave privada disponível(is) no token. Selecione o certificado da Dra. Suzanne.`:'Nenhum certificado utilizável foi localizado no token.')}catch(e:any){setNotice(e?.message||'Falha ao ler os certificados locais.')}finally{setBusy(null)}}

 async function signIcp(row:Row){if(!supabase)return;if(row.icp_validated_document_id){setNotice('Este documento já possui versão final ICP-Brasil registrada.');return}if((row.status||'').toLowerCase()!=='signed'||!row.signed_document_id){setNotice('A assinatura A3 só é liberada depois que o cliente assina e o PDF final da ZapSign é capturado.');return}if(!bridgeOnline||!certFingerprint){setNotice('Conecte a ponte e selecione o certificado A3 antes de assinar.');return}const signedDoc=documents.find(d=>d.id===row.signed_document_id);if(!signedDoc?.file_path){setNotice('O PDF assinado pelo cliente ainda não está disponível na biblioteca. Atualize o painel.');return}setBusy(`icp:${row.id}`);setNotice('Preparando o mesmo PDF assinado pelo cliente para a assinatura A3 da Dra. Suzanne…');let uploadedPath='';let finalDocumentId='';try{
   const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão expirada.');const{data:p,error:pe}=await supabase.from('profiles').select('org_id').eq('id',user.id).single();if(pe||!p?.org_id)throw pe||new Error('Organização não identificada.');
   const{data:pdf,error:downloadError}=await supabase.storage.from('lexoffice-documents').download(signedDoc.file_path);if(downloadError||!pdf)throw downloadError||new Error('PDF assinado pelo cliente não encontrado.');
   const nonce=await bridgeNonce();const form=new FormData();form.append('file',pdf,signedDoc.name.replace(/\.[^.]+$/,'')+'.pdf');form.append('certificateFingerprint',certFingerprint);form.append('visibleSeal',String(visibleSeal));form.append('sealText','ASSINADO DIGITALMENTE - ICP-BRASIL');
   const response=await fetch(`${BRIDGE}/sign/pades`,{method:'POST',headers:{'X-Lexoffice-Nonce':nonce},body:form,signal:AbortSignal.timeout(120000)});if(!response.ok){const raw=await response.text();throw new Error(raw||'A assinatura ICP-Brasil não foi concluída.')}const validation=response.headers.get('X-Lexoffice-Validation');const policy=response.headers.get('X-Lexoffice-Policy');const returnedFingerprint=response.headers.get('X-Lexoffice-Certificate-Fingerprint');const bridge=response.headers.get('X-Lexoffice-Bridge-Version')||bridgeVersion;if(validation!=='valid')throw new Error('A ponte não confirmou a validação criptográfica do PDF.');if(policy!==ICP_POLICY_OID)throw new Error(`A assinatura retornou política PAdES inesperada (${policy||'ausente'}).`);if(returnedFingerprint&&returnedFingerprint.toUpperCase()!==certFingerprint.toUpperCase())throw new Error('O certificado usado na assinatura não corresponde ao certificado selecionado.');
   const blob=await response.blob();if(!blob.size)throw new Error('O PDF assinado retornou vazio.');const digest=hex(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()));
   const base=signedDoc.file_path.replace(/\.pdf$/i,'');uploadedPath=`${base}-final-icpbr-${Date.now()}.pdf`;const{error:uploadError}=await supabase.storage.from('lexoffice-documents').upload(uploadedPath,blob,{contentType:'application/pdf',upsert:false});if(uploadError)throw uploadError;
   const cert=certs.find(c=>c.fingerprint===certFingerprint);const now=new Date().toISOString();const{data:finalDoc,error:docError}=await supabase.from('documents').insert({org_id:p.org_id,client_id:signedDoc.client_id||row.client_id||null,process_id:signedDoc.process_id||row.process_id||null,name:`${(row.title||signedDoc.name).replace(/\.pdf$/i,'')} — Final ICP-Brasil.pdf`,file_path:uploadedPath,mime_type:'application/pdf',size_bytes:blob.size,category:'Documento final assinado ICP-Brasil',notes:`Cliente: assinatura eletrônica ZapSign. Dra. Suzanne: assinatura digital PAdES ICP-Brasil AD-RB 1.3.`,uploaded_by:user.id}).select('id').single();if(docError||!finalDoc)throw docError||new Error('Não foi possível registrar a versão final.');finalDocumentId=finalDoc.id;
   const{error:auditError}=await supabase.from('icp_signature_audit').insert({org_id:p.org_id,signature_request_id:row.id,document_id:finalDoc.id,certificate_subject:cert?.subject||null,certificate_issuer:cert?.issuer||null,certificate_serial:cert?.serial||null,certificate_fingerprint:certFingerprint,signature_algorithm:'PAdES AD-RB 1.3 / SHA-256',document_hash_sha256:digest,signed_at:now,bridge_version:bridge||null,validation_status:'valid',validation_details:{local_crypto_validated:true,policy_oid:policy,certificate_fingerprint:returnedFingerprint||certFingerprint,source:'lexoffice-loopback-bridge'},created_by:user.id});if(auditError)throw auditError;
   const{error:reqError}=await supabase.from('signature_requests').update({icp_validated_document_id:finalDoc.id,icp_validated_at:now,updated_at:now}).eq('id',row.id);if(reqError)throw reqError;
   setNotice('✅ PDF final assinado com o A3 da Dra. Suzanne, validado criptograficamente pela ponte e arquivado. O painel foi liberado para verde.');await load();
 }catch(e:any){if(uploadedPath&&finalDocumentId){try{await supabase.from('documents').delete().eq('id',finalDocumentId)}catch{}try{await supabase.storage.from('lexoffice-documents').remove([uploadedPath])}catch{}}setNotice(`❌ ${e?.message||'Não foi possível concluir a assinatura ICP-Brasil.'}`)}finally{setBusy(null)}}

 const stats=useMemo(()=>({total:rows.length,final:rows.filter(r=>!!r.icp_validated_document_id).length,ready:rows.filter(r=>r.status==='signed'&&!!r.signed_document_id&&!r.icp_validated_document_id).length,waiting:rows.filter(r=>!r.icp_validated_document_id&&['sent','viewed','pending'].includes(r.status||'')).length}),[rows]);
 const selected=clients.find(c=>c.id===clientId);const clientProcesses=processes.filter(p=>p.client_id===clientId);
 function stage(r:Row){if(r.icp_validated_document_id)return{txt:'Final ICP-Brasil',bg:'rgba(28,146,86,.14)',fg:'#1c9256',bd:'rgba(28,146,86,.35)'};if((r.status||'').toLowerCase()==='draft')return{txt:'Aguardando envio',bg:'rgba(235,140,36,.14)',fg:'#d97706',bd:'rgba(235,140,36,.38)'};return{txt:r.status==='signed'?(r.signed_document_id?'Cliente assinou • falta A3':'Cliente assinou • capturando PDF'):label(r.status),bg:'rgba(190,42,42,.10)',fg:'#b91c1c',bd:'rgba(190,42,42,.28)'}}

 return <div className="module cs-page">
  <header className="cs-hero"><div><span className="cs-kicker">ZAPSIGN + ICP-BRASIL A3</span><h1>Central de Assinaturas</h1><p>Cliente assina eletronicamente pela ZapSign; depois a Dra. Suzanne assina o mesmo PDF com certificado A3 ICP-Brasil.</p></div><div className={`cs-connection ${status.configured?'ok':''}`}><span className="dot"/>ZapSign {status.configured?'configurada':'não configurada'}</div></header>
  <nav className="cs-tabs" aria-label="Central de assinaturas"><button className={tab==='send'?'active':''} onClick={()=>setTab('send')}><Upload/><span>1. Novo envio</span></button><button className={tab==='track'?'active':''} onClick={()=>setTab('track')}><FileCheck2/><span>2. Acompanhar e A3</span></button><button className={tab==='config'?'active':''} onClick={()=>setTab('config')}><Settings2/><span>3. Configuração</span></button></nav>
  {notice&&<div className="cs-notice" role="status">{notice}</div>}
  {tab==='send'&&<section className="cs-panel">
   <div className="cs-progress"><span className="on">1 Cliente</span><span>2 Processo</span><span>3 Documentos</span><span>4 Envio</span></div>
   <div className="cs-step"><b>1</b><div><h2>Selecione o cliente</h2><p>Usamos automaticamente CPF, e-mail e WhatsApp já cadastrados no LEXOFFICE.</p></div></div>
   <div className="cs-grid"><label className="cs-wide"><span>Cliente cadastrado</span><select value={clientId} onChange={e=>chooseClient(e.target.value)}><option value="">Outro destinatário — preencher manualmente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span>Nome completo</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome e sobrenome"/></label><label><span>CPF</span><input value={cpf} onChange={e=>setCpf(e.target.value)} placeholder="000.000.000-00"/></label><label><span>E-mail</span><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="cliente@email.com"/></label><label><span>WhatsApp</span><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(31) 99999-9999"/></label>{clientId&&<label className="cs-wide"><span>Processo vinculado</span><select value={processId} onChange={e=>setProcessId(e.target.value)}><option value="">Sem processo específico</option>{clientProcesses.map(p=><option key={p.id} value={p.id}>{p.cnj_number||p.internal_number||p.subject||'Processo'}{p.subject&&p.cnj_number?` — ${p.subject}`:''}</option>)}</select></label>}</div>
   {selected&&<div className="cs-client-ok"><UserRound/><div><strong>{selected.name}</strong><span>Dados carregados. O processo escolhido será preservado no documento original, no PDF do cliente e no PDF final ICP-Brasil.</span></div><CheckCircle2/></div>}
   <div className="cs-divider"/><div className="cs-step"><b>2</b><div><h2>Adicione os documentos</h2><p>Selecione um ou vários PDFs para assinatura.</p></div></div><label className="cs-drop"><Upload size={36}/><strong>Escolher documentos PDF</strong><span>Clique aqui — você pode selecionar vários arquivos</span><input type="file" accept="application/pdf,.pdf" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label>{files.length>0&&<div className="cs-files">{files.map((f,i)=><div key={i}><FileText/><span>{f.name}</span><strong>{(f.size/1024/1024).toFixed(2)} MB</strong></div>)}</div>}
   <div className="cs-divider"/><div className="cs-step"><b>3</b><div><h2>Assinatura do cliente</h2><p>Esta etapa é eletrônica pela ZapSign. Ela não é convertida em ICP-Brasil pela assinatura posterior da advogada.</p></div></div><div className="cs-auth"><button type="button" className={authType==='screen'?'selected':''} onClick={()=>setAuthType('screen')}><span>Assinatura eletrônica ZapSign</span><small>Assinatura em tela pelo fluxo seguro da ZapSign.</small></button></div>
   <div className="cs-divider"/><div className="cs-step"><b>4</b><div><h2>Contato do signatário</h2><p>O e-mail é usado automaticamente pela ZapSign quando informado; o WhatsApp fica registrado no signatário.</p></div></div><div className="cs-delivery"><button type="button" className={delivery==='email'?'selected':''} onClick={()=>setDelivery('email')}><Mail/><span><strong>E-mail</strong><small>{email||'Nenhum e-mail cadastrado'}</small></span></button><button type="button" className={delivery==='whatsapp'?'selected':''} onClick={()=>setDelivery('whatsapp')}><MessageCircle/><span><strong>WhatsApp</strong><small>{phone||'Nenhum WhatsApp cadastrado'}</small></span></button></div>
   <button className="cs-send" disabled={busy==='send'||!status.configured} onClick={send}><Send/>{busy==='send'?'Enviando…':'Enviar documentos pela ZapSign'}</button>{!status.configured&&<p className="cs-help">Antes do primeiro envio, abra a aba Configuração e conecte sua conta ZapSign.</p>}
  </section>}
  {tab==='track'&&<section className="cs-panel">
   <div className="cs-step"><b><ShieldCheck/></b><div><h2>Etapa final ICP-Brasil A3</h2><p>O PIN nunca é solicitado pelo LEXOFFICE. Ele aparece somente na ponte local do Windows e não é armazenado.</p></div></div>
   <div className="cs-actions"><button className="cs-secondary" onClick={()=>checkBridge(true)} disabled={busy==='bridge'}>{bridgeOnline?<Wifi/>:<WifiOff/>}{busy==='bridge'?'Verificando…':'Verificar ponte A3'}</button><button className="cs-primary" onClick={loadCertificates} disabled={!bridgeOnline||busy==='certs'}><Usb/>{busy==='certs'?'Aguardando PIN local…':'Carregar certificado A3'}</button></div>
   {bridgeOnline&&<div className="cs-success"><CheckCircle2/> Ponte local conectada{bridgeVersion?` • versão ${bridgeVersion}`:''} • 127.0.0.1 • PAdES AD-RB 1.3.</div>}
   {certs.length>0&&<div className="cs-grid config"><label className="cs-wide"><span>Certificado A3 da Dra. Suzanne</span><select value={certFingerprint} onChange={e=>setCertFingerprint(e.target.value)}>{certs.map(c=><option key={c.fingerprint} value={c.fingerprint}>{cn(c.subject)} — {cn(c.issuer)}</option>)}</select></label><label><span>Selo visual</span><select value={visibleSeal?'sim':'nao'} onChange={e=>setVisibleSeal(e.target.value==='sim')}><option value="sim">Aplicar no PDF</option><option value="nao">Não aplicar</option></select></label></div>}
   <div className="cs-stats"><div><FileText/><b>{stats.total}</b><span>Total</span></div><div><Clock3/><b>{stats.waiting}</b><span>Aguardando cliente</span></div><div><KeyRound/><b>{stats.ready}</b><span>Prontos para A3</span></div><div><FileCheck2/><b>{stats.final}</b><span>Final ICP-Brasil</span></div></div>
   <div className="table-wrap"><table><thead><tr><th>Documento</th><th>Destinatário</th><th>Etapa</th><th>Cliente</th><th>Dra. Suzanne</th><th>Ação</th></tr></thead><tbody>{rows.map(r=>{const s=stage(r);const canSign=r.status==='signed'&&!!r.signed_document_id&&!r.icp_validated_document_id;return <tr key={r.id}><td><strong>{r.title||'Documento'}</strong><small style={{display:'block',opacity:.7}}>{pt(r.sent_at||r.created_at)}</small></td><td>{r.signer_name||'—'}</td><td><span className="cs-badge" style={{background:s.bg,color:s.fg,border:`1px solid ${s.bd}`}}>{s.txt}</span></td><td>{r.status==='signed'?<span>✓ eletrônica</span>:<span>{label(r.status)}</span>}</td><td>{r.icp_validated_document_id?<span style={{color:'#1c9256',fontWeight:700}}>✓ PAdES ICP-Brasil</span>:<span>pendente</span>}</td><td>{canSign?<button className="cs-primary" disabled={!bridgeOnline||!certFingerprint||busy===`icp:${r.id}`} onClick={()=>signIcp(r)}><KeyRound/>{busy===`icp:${r.id}`?'Assinando…':'Assinar final com A3'}</button>:r.icp_validated_document_id?<span style={{color:'#1c9256',fontWeight:700}}>Concluído</span>:<span style={{opacity:.65}}>—</span>}</td></tr>})}</tbody></table></div>
  </section>}
  {tab==='config'&&<section className="cs-panel"><div className="cs-step"><b><Plug/></b><div><h2>Configuração ZapSign</h2><p>A credencial fica protegida no backend do LEXOFFICE. Esta credencial não tem relação com o PIN do certificado A3.</p></div></div><div className="cs-grid config"><label><span>E-mail da conta (opcional)</span><input value={accountEmail} onChange={e=>setAccountEmail(e.target.value)} placeholder="conta@escritorio.com"/></label><label><span>Token / API Key</span><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Cole o token da ZapSign"/></label></div><div className="cs-actions"><button className="cs-primary" disabled={busy==='config'||!token.trim()} onClick={connect}><Plug/>Conectar ZapSign</button><button className="cs-secondary" onClick={()=>loadStatus(true)}><RefreshCw/>Testar configuração</button></div>{status.configured&&<div className="cs-success"><CheckCircle2/> ZapSign configurada{status.account_email?<> para <b>{status.account_email}</b></>:null}.</div>}</section>}
 </div>;
}
