import {useEffect,useMemo,useState} from 'react';
import {Landmark,Plus,RefreshCw,ShieldCheck,KeyRound,Search,Gavel,UserCheck,LockKeyhole,EyeOff,BookOpen,CheckCircle2,AlertTriangle} from 'lucide-react';
import {supabase} from '../lib/supabase';
import './integrations.css';

type Conn={id:string;tribunal_code:string;tribunal_name:string;judicial_system:string|null;oab_number:string|null;oab_uf:string|null;status:string;requires_2fa:boolean;last_authenticated_at:string|null;last_sync_at:string|null;error_message:string|null};
const ufs=['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'];
const national=[['STF','Supremo Tribunal Federal'],['STJ','Superior Tribunal de Justiça'],['TST','Tribunal Superior do Trabalho'],['TSE','Tribunal Superior Eleitoral'],['STM','Superior Tribunal Militar'],...[1,2,3,4,5,6].map(n=>[`TRF${n}`,`Tribunal Regional Federal da ${n}ª Região`]),...ufs.map(uf=>[`TJ${uf}`,`Tribunal de Justiça de ${uf}`]),...Array.from({length:24},(_,i)=>[`TRT${i+1}`,`Tribunal Regional do Trabalho da ${i+1}ª Região`]),...ufs.map(uf=>[`TRE${uf}`,`Tribunal Regional Eleitoral de ${uf}`])] as [string,string][];
const platforms=['PJe','eproc','Projudi','SAJ / e-SAJ','DataJud','SEEU','Creta','Apolo','Sistema próprio','Outro'];
const tribunalName=(code:string)=>national.find(x=>x[0]===code)?.[1]||code;
const emptyConn={tribunal_code:'TJMG',tribunal_name:'Tribunal de Justiça de MG',judicial_system:'PJe',oab_number:'',oab_uf:'MG',requires_2fa:true};
const emptyProcess={client_id:'',cnj_number:'',internal_number:'',opposing_party:'',tribunal_code:'TJMG',tribunal_name:'Tribunal de Justiça de MG',judicial_system:'PJe',court:'',comarca:'',vara:'',area:'',subject:'',class_name:'',is_confidential:false,confidentiality_level:'1'};
const text=(v:any)=>typeof v==='string'?v:(v?.nome||v?.name||'—');
export default function Tribunals(){
 const[tab,setTab]=useState('consult'),[connections,setConnections]=useState<Conn[]>([]),[clients,setClients]=useState<any[]>([]),[form,setForm]=useState({...emptyConn}),[cred,setCred]=useState({tribunal_code:'TJMG',judicial_system:'PJe',login:'',password:''}),[two,setTwo]=useState({tribunal_code:'TJMG',judicial_system:'PJe',code:''}),[proc,setProc]=useState({...emptyProcess}),[consult,setConsult]=useState({tribunal_code:'TJMG',cnj_number:''}),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[noticeType,setNoticeType]=useState<'ok'|'error'>('ok'),[q,setQ]=useState('');
 async function invoke(body:any){if(!supabase)throw new Error('Supabase indisponível.');const r=await supabase.functions.invoke('tribunal-connection-manager',{body});const msg=r.data?.error||r.error?.message;if(r.error||r.data?.error)throw new Error(msg==='Edge Function returned a non-2xx status code'?'A operação não foi concluída. Atualize a tela e tente novamente. Se persistir, o LEXOFFICE registrará o erro técnico no backend.':msg||'Falha na integração com tribunais.');return r.data}
 async function load(silent=false){if(!supabase)return;try{const[r,c]=await Promise.all([invoke({action:'list'}),supabase.from('clients').select('id,name,cpf_cnpj').order('name').limit(2000)]);setConnections(r.connections||[]);setClients(c.data||[]);if(!silent)setNotice('');}catch(e:any){if(!silent){setNoticeType('error');setNotice(e?.message||'Falha ao carregar tribunais.')}}}
 useEffect(()=>{load();const id=window.setInterval(()=>load(true),45000);return()=>clearInterval(id)},[]);
 const catalog=useMemo(()=>{const s=q.trim().toLowerCase();return s?national.filter(([c,n])=>(c+' '+n).toLowerCase().includes(s)):national},[q]);
 function chooseTribunal(code:string,name:string){const found=connections.find(c=>c.tribunal_code===code),platform=found?.judicial_system||'PJe';setForm({...form,tribunal_code:code,tribunal_name:name,judicial_system:platform,oab_number:found?.oab_number||form.oab_number,oab_uf:found?.oab_uf||(code.startsWith('TJ')?code.slice(2):form.oab_uf),requires_2fa:found?.requires_2fa??form.requires_2fa});setCred({...cred,tribunal_code:code,judicial_system:platform});setTwo({...two,tribunal_code:code,judicial_system:platform})}
 async function run(fn:()=>Promise<any>,fallback:string){setBusy(true);setNotice('');try{const r=await fn();setNoticeType('ok');setNotice(r.message||'Operação concluída com sucesso.');return r}catch(e:any){setNoticeType('error');setNotice(e?.message||fallback);return null}finally{setBusy(false)}}
 async function doConsult(){setResult(null);const r=await run(()=>invoke({action:'consult_process',...consult}),'Falha ao consultar processo.');if(r?.found)setResult(r.process)}
 async function saveConn(){const r=await run(()=>invoke({action:'save',...form}),'Falha ao salvar tribunal.');if(r)await load(true)}
 async function importOab(){const name=tribunalName(form.tribunal_code);const r=await run(async()=>{await invoke({action:'save',...form,tribunal_name:name});return invoke({action:'import_oab',tribunal_code:form.tribunal_code,tribunal_name:name,judicial_system:form.judicial_system,oab_number:form.oab_number,oab_uf:form.oab_uf})},'Falha ao importar por OAB.');if(r)await load(true)}
 async function saveCred(){const r=await run(()=>invoke({action:'save_credentials',...cred}),'Falha ao salvar credenciais.');if(r){setCred({...cred,password:''});await load(true)}}
 async function submit2fa(){const r=await run(()=>invoke({action:'submit_2fa',...two}),'Falha no 2FA.');if(r){setTwo({...two,code:''});await load(true)}}
 async function addProcess(){const r=await run(()=>invoke({action:'add_process',...proc,tribunal_name:tribunalName(proc.tribunal_code)}),'Falha ao adicionar processo.');if(r&&!r.duplicate)setProc({...emptyProcess})}
 const tabs:any[]=[['consult','Consultas',Search],['connections','Tribunais',Landmark],['oab','Importar por OAB',UserCheck],['credentials','Acessos e 2FA',KeyRound],['manual','Adicionar processo',Plus],['status','Monitoramento',ShieldCheck]];
 return <div className="module"><div className="page-head"><div><h1>Tribunais e Processos</h1><p>Consultas processuais, tribunais, OAB, acessos, 2FA e monitoramento.</p></div><button className="integration-action" onClick={()=>load()}><RefreshCw size={15}/>Atualizar</button></div>{notice&&<div className={`integration-notice ${noticeType==='error'?'error':''}`}>{noticeType==='ok'?<CheckCircle2 size={16}/>:<AlertTriangle size={16}/>} {notice}</div>}
 <div className="campaign-tabs process-tabs">{tabs.map(([k,l,I])=><button key={k} className={tab===k?'active':''} onClick={()=>{setTab(k);setNotice('')}}><I size={15}/>{l}</button>)}</div>
 {tab==='consult'&&<div className="integration-panel"><h3><BookOpen size={18}/> Consulta processual</h3><p>Consulte pelo número CNJ na fonte pública DataJud. A consulta não cria nem altera o processo.</p><div className="integration-form"><label>Tribunal<select value={consult.tribunal_code} onChange={e=>setConsult({...consult,tribunal_code:e.target.value})}>{national.map(([c,n])=><option value={c} key={c}>{c} — {n}</option>)}</select></label><label className="wide">Número do processo (CNJ)<input value={consult.cnj_number} onChange={e=>setConsult({...consult,cnj_number:e.target.value})} placeholder="0000000-00.0000.0.00.0000"/></label><button className="integration-action" onClick={doConsult} disabled={busy||!consult.cnj_number}><Search size={15}/>{busy?'Consultando...':'Consultar processo'}</button></div>{result&&<div className="integration-panel" style={{marginTop:16}}><h3><Gavel size={17}/> Resultado</h3><div className="signature-list"><div className="signature-row"><div><strong>{result.numeroProcesso||consult.cnj_number}</strong><small><b>Tribunal:</b> {text(result.tribunal)} · <b>Classe:</b> {text(result.classe)}</small><small><b>Órgão:</b> {text(result.orgaoJulgador)}</small><small><b>Assunto:</b> {Array.isArray(result.assuntos)?result.assuntos.map(text).join(', '):text(result.assuntos)}</small></div></div></div><h3 style={{marginTop:18}}>Últimos andamentos</h3><div className="signature-list">{(result.movimentos||[]).slice().reverse().slice(0,30).map((m:any,i:number)=><div className="signature-row" key={i}><div><strong>{m.nome||m.descricao||`Movimento ${m.codigo||''}`}</strong><small>{m.dataHora||m.data||'Data não informada'}</small></div></div>)}</div></div>}</div>}
 {tab==='connections'&&<><div className="integration-panel"><h3><Search size={17}/> Tribunais do Brasil</h3><div className="input-search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar STF, TJMG, TRT, TRE..."/></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:8,marginTop:14,maxHeight:330,overflow:'auto'}}>{catalog.map(([code,name])=><button className="secondary" key={code} onClick={()=>chooseTribunal(code,name)}><Landmark size={14}/><span><b>{code}</b> · {name}</span></button>)}</div></div><div className="integration-panel"><h3><Landmark size={17}/> Configuração do tribunal</h3><div className="integration-form"><label>Código<input value={form.tribunal_code} onChange={e=>setForm({...form,tribunal_code:e.target.value.toUpperCase()})}/></label><label>Tribunal<input value={form.tribunal_name} onChange={e=>setForm({...form,tribunal_name:e.target.value})}/></label><label>Plataforma<select value={form.judicial_system} onChange={e=>setForm({...form,judicial_system:e.target.value})}>{platforms.map(x=><option key={x}>{x}</option>)}</select></label><label>OAB<input value={form.oab_number} onChange={e=>setForm({...form,oab_number:e.target.value})}/></label><label>UF<input value={form.oab_uf} onChange={e=>setForm({...form,oab_uf:e.target.value.toUpperCase()})}/></label><label><input type="checkbox" checked={form.requires_2fa} onChange={e=>setForm({...form,requires_2fa:e.target.checked})}/> Exige 2FA</label><button className="integration-action" onClick={saveConn} disabled={busy}>Salvar tribunal</button></div></div></>}
 {tab==='oab'&&<div className="integration-panel"><h3><UserCheck size={17}/> Importação por OAB</h3><p>O monitoramento é salvo antes da busca. Quando a fonte pública não permitir descoberta por OAB, o LEXOFFICE mantém a OAB cadastrada para o adaptador do tribunal, sem inventar processos.</p><div className="integration-form"><label>Tribunal<select value={form.tribunal_code} onChange={e=>{const t=national.find(x=>x[0]===e.target.value);if(t)chooseTribunal(t[0],t[1])}}>{national.map(([c,n])=><option value={c} key={c}>{c} — {n}</option>)}</select></label><label>Número OAB<input value={form.oab_number} onChange={e=>setForm({...form,oab_number:e.target.value})}/></label><label>UF<input value={form.oab_uf} onChange={e=>setForm({...form,oab_uf:e.target.value.toUpperCase()})}/></label><button className="integration-action" onClick={importOab} disabled={busy||!form.oab_number}>{busy?'Processando...':'Salvar monitoramento e buscar processos'}</button></div></div>}
 {tab==='credentials'&&<><div className="integration-panel"><h3><LockKeyhole size={17}/> Login e senha do tribunal</h3><p>A senha é enviada ao cofre do backend e não volta para a tela depois de salva.</p><div className="integration-form"><label>Tribunal<select value={cred.tribunal_code} onChange={e=>{const code=e.target.value;const found=connections.find(c=>c.tribunal_code===code);setCred({...cred,tribunal_code:code,judicial_system:found?.judicial_system||cred.judicial_system});setTwo({...two,tribunal_code:code,judicial_system:found?.judicial_system||two.judicial_system})}}>{national.map(([c,n])=><option value={c} key={c}>{c} — {n}</option>)}</select></label><label>Plataforma<select value={cred.judicial_system} onChange={e=>setCred({...cred,judicial_system:e.target.value})}>{platforms.map(x=><option key={x}>{x}</option>)}</select></label><label>Login / CPF / usuário<input value={cred.login} onChange={e=>setCred({...cred,login:e.target.value})}/></label><label>Senha<input type="password" value={cred.password} onChange={e=>setCred({...cred,password:e.target.value})}/></label><button className="integration-action" onClick={saveCred} disabled={busy||!cred.login||!cred.password}>{busy?'Salvando...':'Guardar credenciais'}</button></div></div><div className="integration-panel"><h3>Verificação em duas etapas</h3><p>O código 2FA é usado somente nesta operação e não é armazenado.</p><div className="integration-form"><label>Código 2FA<input value={two.code} onChange={e=>setTwo({...two,code:e.target.value})}/></label><button className="integration-action" onClick={submit2fa} disabled={busy||!two.code}>Usar código nesta sessão</button></div></div></>}
 {tab==='manual'&&<div className="integration-panel"><h3><Plus size={17}/> Adicionar processo manualmente</h3><div className="integration-form"><label>Cliente<select value={proc.client_id} onChange={e=>setProc({...proc,client_id:e.target.value})}><option value="">Sem cliente</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Número CNJ<input value={proc.cnj_number} onChange={e=>setProc({...proc,cnj_number:e.target.value})}/></label><label>Número interno<input value={proc.internal_number} onChange={e=>setProc({...proc,internal_number:e.target.value})}/></label><label>Tribunal<select value={proc.tribunal_code} onChange={e=>setProc({...proc,tribunal_code:e.target.value,tribunal_name:tribunalName(e.target.value)})}>{national.map(([c,n])=><option value={c} key={c}>{c} — {n}</option>)}</select></label><label>Parte contrária<input value={proc.opposing_party} onChange={e=>setProc({...proc,opposing_party:e.target.value})}/></label><label>Comarca<input value={proc.comarca} onChange={e=>setProc({...proc,comarca:e.target.value})}/></label><label>Vara<input value={proc.vara} onChange={e=>setProc({...proc,vara:e.target.value})}/></label><label>Assunto<input value={proc.subject} onChange={e=>setProc({...proc,subject:e.target.value})}/></label><label><input type="checkbox" checked={proc.is_confidential} onChange={e=>setProc({...proc,is_confidential:e.target.checked})}/><EyeOff size={15}/> Processo sigiloso</label><button className="integration-action" onClick={addProcess} disabled={busy||(!proc.cnj_number&&!proc.internal_number)}>Adicionar processo</button></div></div>}
 {tab==='status'&&<div className="integration-panel"><h3><ShieldCheck size={17}/> Conexões e monitoramento</h3>{connections.length===0?<p>Nenhum tribunal configurado.</p>:<div className="signature-list">{connections.map(c=><div className="signature-row" key={c.id}><div><strong>{c.tribunal_code} · {c.tribunal_name}</strong><small>{c.judicial_system||'—'} · OAB {c.oab_number||'—'}/{c.oab_uf||'—'} · 2FA {c.requires_2fa?'sim':'não'}</small><small>Última sincronização: {c.last_sync_at?new Date(c.last_sync_at).toLocaleString('pt-BR'):'ainda não realizada'}{c.error_message?` · ${c.error_message}`:''}</small></div><span className="status-dot">{c.status}</span></div>)}</div>}</div>}
 </div>}
