import {useEffect,useState} from 'react';
import {Landmark,Plus,RefreshCw,ShieldCheck,KeyRound,UserCheck,CheckCircle2,AlertTriangle,Play,Upload,Search,Clock3} from 'lucide-react';
import {supabase} from '../lib/supabase';
import './integrations.css';

type Conn={id:string;tribunal_code:string;tribunal_name:string;judicial_system:string|null;oab_number:string|null;oab_uf:string|null;status:string;requires_2fa:boolean;last_sync_at:string|null;error_message:string|null};
type FeatureStatus='enabled'|'coming_soon'|'hidden'|'admin_only';
type FeatureFlag={feature_key:string;status:FeatureStatus;label:string;description:string|null};
const defaults:Record<string,FeatureFlag>={
 tribunals_authenticated_access:{feature_key:'tribunals_authenticated_access',status:'coming_soon',label:'Acessos e 2FA',description:'Integração autenticada com os sistemas judiciais está em desenvolvimento.'},
 tribunals_oab_discovery:{feature_key:'tribunals_oab_discovery',status:'coming_soon',label:'Carteira por OAB',description:'Descoberta automática da carteira será liberada após a validação do provedor.'},
 tribunals_public_monitoring:{feature_key:'tribunals_public_monitoring',status:'enabled',label:'Monitoramento',description:'Atualização pública dos processos conhecidos.'},
 tribunals_manual_process:{feature_key:'tribunals_manual_process',status:'enabled',label:'Adicionar processo',description:'Cadastro manual por número CNJ.'}
};
async function edgeErrorMessage(error:any){const ctx=error?.context;if(ctx&&typeof ctx.clone==='function'){try{const data=await ctx.clone().json();const msg=data?.error||data?.message||data?.msg;if(msg)return String(msg)}catch{}const status=Number(ctx?.status||0);if(status===401)return 'Sua sessão expirou. Entre novamente no LEXOFFICE.';if(status===403)return 'Seu usuário não tem permissão para executar esta operação.';if(status>=500)return 'O serviço encontrou um erro interno.';}return String(error?.message||'Não foi possível concluir a operação.');}
async function fn(name:string,body:any){if(!supabase)throw new Error('Backend indisponível.');const r=await supabase.functions.invoke(name,{body});if(r.data?.error)throw new Error(r.data.error);if(r.error)throw new Error(await edgeErrorMessage(r.error));return r.data||{}}
export default function Tribunals(){
 const[tab,setTab]=useState('monitor'),[connections,setConnections]=useState<Conn[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(false),[flags,setFlags]=useState<Record<string,FeatureFlag>>(defaults);
 const[oab,setOab]=useState({oab_number:'',oab_uf:'MG',cnjs:'',status:'ATIVO'}),[continueUrl,setContinueUrl]=useState(''),[discoverySummary,setDiscoverySummary]=useState<any>(null);
 const[manual,setManual]=useState({cnj_number:'',tribunal_code:'TJMG',judicial_system:'DataJud',subject:''});
 const flag=(key:string)=>flags[key]||defaults[key];
 const usable=(key:string)=>flag(key).status==='enabled';
 async function load(){try{const [a,f]=await Promise.all([fn('tribunal-connection-manager',{action:'list'}).catch(()=>({connections:[]})),supabase?.from('platform_feature_flags').select('feature_key,status,label,description')]);setConnections(a.connections||[]);if(f?.data){const next={...defaults};for(const row of f.data as FeatureFlag[])next[row.feature_key]=row;setFlags(next)}}catch{}}
 useEffect(()=>{load();const id=setInterval(load,45000);return()=>clearInterval(id)},[]);
 async function run(cb:()=>Promise<any>){setBusy(true);setNotice('');try{const r=await cb();setError(false);setNotice(r.message||'Operação concluída.');await load();return r}catch(e:any){setError(true);setNotice(e?.message||'Não foi possível concluir.');return null}finally{setBusy(false)}}
 async function discoverOab(cont=false){if(!usable('tribunals_oab_discovery'))return;const r=await run(()=>fn('escavador-oab-discovery',{action:'discover',oab_number:oab.oab_number,oab_uf:oab.oab_uf,status:oab.status||undefined,continue_url:cont?continueUrl:undefined,max_pages:5}));if(r?.ok){setDiscoverySummary(r);setContinueUrl(r.continue_url||'')}}
 async function importCnjs(){const r=await run(()=>fn('tribunal-connection-manager',{action:'import_cnjs',oab_number:oab.oab_number,oab_uf:oab.oab_uf,cnjs:oab.cnjs,source:'oab_authorized_list'}));if(r?.ok)setOab(v=>({...v,cnjs:''}))}
 async function syncPublic(){if(usable('tribunals_public_monitoring'))await run(()=>fn('tribunal-sync',{action:'sync_public_processes'}))}
 async function addManual(){if(!usable('tribunals_manual_process'))return;await run(()=>fn('tribunal-connection-manager',{action:'add_process',...manual}));setManual(v=>({...v,cnj_number:'',subject:''}))}
 const items=[['access','tribunals_authenticated_access',KeyRound],['oab','tribunals_oab_discovery',UserCheck],['monitor','tribunals_public_monitoring',ShieldCheck],['manual','tribunals_manual_process',Plus]] as const;
 const visible=items.filter(([,k])=>flag(k).status!=='hidden');
 const ComingSoon=({featureKey}:{featureKey:string})=><div className="integration-panel"><div style={{display:'flex',alignItems:'center',gap:10,marginBottom:10}}><Clock3 size={20}/><h3 style={{margin:0}}>{flag(featureKey).label} <span style={{fontSize:12,fontWeight:700,padding:'4px 8px',border:'1px solid currentColor',borderRadius:999,opacity:.8}}>EM BREVE</span></h3></div><p>{flag(featureKey).description||'Esta funcionalidade está em desenvolvimento e será disponibilizada em uma próxima atualização.'}</p><div className="integration-notice"><Clock3 size={17}/> Estamos preparando e validando esta integração antes de disponibilizá-la. Nenhuma credencial ou dado será solicitado enquanto o recurso não estiver pronto.</div></div>;
 return <div className="module"><div className="page-head"><div><h1>Tribunais e Processos</h1><p>Consulta pública e monitoramento processual com recursos liberados somente após validação.</p></div><button className="integration-action" onClick={load}><RefreshCw size={16}/>Atualizar</button></div>{notice&&<div className={`integration-notice ${error?'error':''}`}>{error?<AlertTriangle size={17}/>:<CheckCircle2 size={17}/>} {notice}</div>}
 <div className="campaign-tabs process-tabs">{visible.map(([id,key,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={16}/>{flag(key).label}{flag(key).status==='coming_soon'&&<span style={{fontSize:10,fontWeight:700,marginLeft:5,opacity:.75}}>EM BREVE</span>}</button>)}</div>
 {tab==='access'&&<ComingSoon featureKey="tribunals_authenticated_access"/>}
 {tab==='oab'&&!usable('tribunals_oab_discovery')&&<ComingSoon featureKey="tribunals_oab_discovery"/>}
 {tab==='oab'&&usable('tribunals_oab_discovery')&&<div className="integration-panel"><h3><UserCheck size={18}/> Descobrir carteira do advogado</h3><p>Informe sua OAB para descobrir os CNJs da sua carteira e preparar os processos para monitoramento.</p><div className="integration-form"><label>OAB<input value={oab.oab_number} onChange={e=>setOab({...oab,oab_number:e.target.value})}/></label><label>UF<input value={oab.oab_uf} maxLength={2} onChange={e=>setOab({...oab,oab_uf:e.target.value.toUpperCase()})}/></label><label>Situação<select value={oab.status} onChange={e=>setOab({...oab,status:e.target.value})}><option value="ATIVO">Processos ativos</option><option value="">Todos</option><option value="INATIVO">Inativos</option></select></label><button className="integration-action" onClick={()=>discoverOab(false)} disabled={busy||!oab.oab_number||oab.oab_uf.length!==2}><Search size={15}/>Descobrir processos pela OAB</button>{continueUrl&&<button className="secondary" onClick={()=>discoverOab(true)} disabled={busy}><RefreshCw size={15}/>Continuar descoberta</button>}</div>{discoverySummary&&<div className="integration-notice"><CheckCircle2 size={17}/> {discoverySummary.imported||0} novo(s), {discoverySummary.duplicates||0} já existente(s).</div>}<div style={{marginTop:24}}><h3><Upload size={18}/> Importar CNJs manualmente</h3><div className="integration-form"><label className="wide">Números CNJ<textarea rows={6} value={oab.cnjs} onChange={e=>setOab({...oab,cnjs:e.target.value})}/></label><button className="secondary" onClick={importCnjs} disabled={busy||!oab.oab_number||!oab.cnjs.trim()}><Upload size={15}/>Importar lista</button></div></div></div>}
 {tab==='monitor'&&usable('tribunals_public_monitoring')&&<div className="integration-panel"><h3><ShieldCheck size={18}/> Monitoramento público</h3><p>Somente os processos pertencentes ao usuário conectado são consultados. O DataJud atualiza os CNJs conhecidos e o DJEN acompanha as publicações vinculadas.</p><button className="integration-action" onClick={syncPublic} disabled={busy}><Play size={14}/>{busy?'Sincronizando...':'Sincronizar meus processos agora'}</button></div>}
 {tab==='manual'&&usable('tribunals_manual_process')&&<div className="integration-panel"><h3><Landmark size={18}/> Adicionar processo</h3><p>Informe o número CNJ. O processo será vinculado somente ao usuário conectado.</p><div className="integration-form"><label className="wide">Número CNJ<input value={manual.cnj_number} onChange={e=>setManual({...manual,cnj_number:e.target.value})} placeholder="0000000-00.0000.0.00.0000"/></label><label className="wide">Assunto<input value={manual.subject} onChange={e=>setManual({...manual,subject:e.target.value})}/></label><button className="integration-action" onClick={addManual} disabled={busy||!manual.cnj_number}><Plus size={15}/>Adicionar processo</button></div></div>}
 </div>
}
