import { useEffect,useState } from 'react';
import { Bot,Headphones,BellRing,Send,CheckCircle2,AlertCircle } from 'lucide-react';
import { supabase } from '../lib/supabase';

async function getFunctionError(result:any,fallback:string){if(result?.data?.error)return String(result.data.error);const err=result?.error;if(err?.context){try{const body=await err.context.clone().json();if(body?.error)return String(body.error);if(body?.message)return String(body.message)}catch{}}return err?.message||fallback}

export default function WhatsAppAdminSettings(){
 const [orgId,setOrgId]=useState(''),[settingsId,setSettingsId]=useState<string|null>(null),[connected,setConnected]=useState(false);
 const [aiEnabled,setAiEnabled]=useState(true),[resumeMinutes,setResumeMinutes]=useState(30),[resumeKeyword,setResumeKeyword]=useState('#ia');
 const [followupEnabled,setFollowupEnabled]=useState(false),[followupDelay,setFollowupDelay]=useState(60),[followupAttempts,setFollowupAttempts]=useState(1),[followupStart,setFollowupStart]=useState('08:00'),[followupEnd,setFollowupEnd]=useState('18:00');
 const [alertsEnabled,setAlertsEnabled]=useState(true),[alertPhone,setAlertPhone]=useState(''),[phone,setPhone]=useState(''),[message,setMessage]=useState('');
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function invokeWaha(body:any){if(!supabase)return {data:null,error:new Error('Supabase indisponível.')};return supabase.functions.invoke('whatsapp-waha-connect',{body})}
 useEffect(()=>{(async()=>{if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:p}=await supabase.from('profiles').select('org_id').eq('id',user.id).maybeSingle();if(!p?.org_id)return;setOrgId(p.org_id);const [{data:s},{data:st}]=await Promise.all([supabase.from('whatsapp_settings').select('id,ai_enabled,human_takeover_auto_resume_minutes,human_takeover_resume_keyword,followup_enabled,followup_delay_minutes,followup_max_attempts,followup_start_time,followup_end_time,alerts_enabled,alert_phone').eq('org_id',p.org_id).maybeSingle(),invokeWaha({action:'status'})]);if(s){setSettingsId(s.id);setAiEnabled(s.ai_enabled!==false);setResumeMinutes(Number(s.human_takeover_auto_resume_minutes??30));setResumeKeyword(String(s.human_takeover_resume_keyword||'#ia'));setFollowupEnabled(!!s.followup_enabled);setFollowupDelay(Number(s.followup_delay_minutes??60));setFollowupAttempts(Number(s.followup_max_attempts??1));setFollowupStart(String(s.followup_start_time||'08:00').slice(0,5));setFollowupEnd(String(s.followup_end_time||'18:00').slice(0,5));setAlertsEnabled(s.alerts_enabled!==false);setAlertPhone(String(s.alert_phone||''))}setConnected(!!st?.connected)})()},[]);
 async function save(){if(!supabase||!orgId)return;setBusy(true);setError('');setNotice('');const payload={org_id:orgId,ai_enabled:aiEnabled,human_takeover_auto_resume_minutes:Math.max(0,Number(resumeMinutes)||0),human_takeover_resume_keyword:resumeKeyword.trim()||'#ia',followup_enabled:followupEnabled,followup_delay_minutes:Math.max(1,Number(followupDelay)||60),followup_max_attempts:Math.max(1,Math.min(5,Number(followupAttempts)||1)),followup_start_time:followupStart,followup_end_time:followupEnd,alerts_enabled:alertsEnabled,alert_phone:alertPhone.trim()||null,updated_at:new Date().toISOString()};const q=settingsId?supabase.from('whatsapp_settings').update(payload).eq('id',settingsId).select('id').single():supabase.from('whatsapp_settings').insert(payload).select('id').single();const {data,error}=await q as any;setBusy(false);if(error){setError(error.message);return}if(data?.id)setSettingsId(data.id);setNotice('Configurações do WhatsApp salvas.')}
 async function sendTest(e:any){e.preventDefault();if(!phone.trim()||!message.trim())return;setBusy(true);setError('');setNotice('');const r=await invokeWaha({action:'send',phone:phone.trim(),message:message.trim()});setBusy(false);if(r.error||!r.data?.ok){setError(await getFunctionError(r,'Falha ao enviar mensagem de teste.'));return}setNotice('Mensagem de teste enviada com sucesso.')}
 return <div className="settings-feature-grid whatsapp-admin-settings">
  <div className="settings-feature-card"><h3><Send size={17}/> Teste do canal</h3><p>Envie uma mensagem de teste sem poluir a tela operacional de conversas.</p><form className="channel-form" onSubmit={sendTest}><label>Telefone<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="5531999999999"/></label><label>Mensagem<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Mensagem de teste do LEXOFFICE"/></label><button className="secondary" disabled={busy||!connected}><Send size={15}/> Enviar teste</button></form>{!connected&&<small>Conecte o WhatsApp em Configurações → Conexões antes de testar.</small>}</div>
  <div className="settings-feature-card"><h3><Bot size={17}/> Controle da IA</h3><p>Defina quando a Clara atende e como retoma uma conversa após intervenção humana.</p><div className="channel-form"><label>IA no WhatsApp<select value={aiEnabled?'on':'off'} onChange={e=>setAiEnabled(e.target.value==='on')}><option value="on">Ligada</option><option value="off">Desligada</option></select></label><label>Retomar após (minutos)<input type="number" min="0" value={resumeMinutes} onChange={e=>setResumeMinutes(Number(e.target.value))}/></label><label>Palavra para retomar<input value={resumeKeyword} onChange={e=>setResumeKeyword(e.target.value)} placeholder="#ia"/></label></div></div>
  <div className="settings-feature-card"><h3><Headphones size={17}/> Atendimento humano</h3><p>Ao assumir uma conversa, a IA fica pausada naquele contato. A retomada segue a regra definida acima.</p><div className="settings-chip-row"><span className="settings-chip ready">Intervenção humana</span><span className="settings-chip">Retomada após {resumeMinutes} min.</span></div></div>
  <div className="settings-feature-card"><h3><BellRing size={17}/> Follow-up</h3><div className="channel-form"><label><input type="checkbox" checked={followupEnabled} onChange={e=>setFollowupEnabled(e.target.checked)}/> Follow-up automático</label><label>Primeiro follow-up após (min.)<input type="number" min="1" value={followupDelay} onChange={e=>setFollowupDelay(Number(e.target.value))}/></label><label>Máximo de tentativas<input type="number" min="1" max="5" value={followupAttempts} onChange={e=>setFollowupAttempts(Number(e.target.value))}/></label><label>Início dos envios<input type="time" value={followupStart} onChange={e=>setFollowupStart(e.target.value)}/></label><label>Fim dos envios<input type="time" value={followupEnd} onChange={e=>setFollowupEnd(e.target.value)}/></label><label><input type="checkbox" checked={alertsEnabled} onChange={e=>setAlertsEnabled(e.target.checked)}/> Alertas da régua</label><label>Número geral de alertas<input value={alertPhone} onChange={e=>setAlertPhone(e.target.value)} placeholder="5531999999999"/></label></div></div>
  <div className="settings-feature-card wide"><button className="integration-action" onClick={save} disabled={busy}><CheckCircle2 size={15}/> {busy?'Salvando...':'Salvar configurações do WhatsApp'}</button>{error&&<div className="status-message error"><AlertCircle size={16}/>{error}</div>}{notice&&<div className="status-message success"><CheckCircle2 size={16}/>{notice}</div>}</div>
 </div>
}
