import { useEffect,useMemo,useState } from 'react';
import { MessageCircle,RefreshCw,Send,CheckCircle2,AlertCircle,Wifi,ShieldCheck,Bot,UserRound } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './integrations.css';

async function getFunctionError(result:any,fallback:string){if(result?.data?.error)return String(result.data.error);const err=result?.error;if(err?.context){try{const body=await err.context.clone().json();if(body?.error)return String(body.error);if(body?.message)return String(body.message)}catch{}}return err?.message||fallback}
const digits=(v:any)=>String(v??'').replace(/\D/g,'');
function formatWhatsAppPhone(value:any){const d=digits(value);if(!d)return 'Número não identificado';if(d.startsWith('55')&&(d.length===12||d.length===13)){const ddd=d.slice(2,4),local=d.slice(4);return `+55 (${ddd}) ${local.length===9?`${local.slice(0,5)}-${local.slice(5)}`:`${local.slice(0,4)}-${local.slice(4)}`}`}if(d.length===10||d.length===11){const ddd=d.slice(0,2),local=d.slice(2);return `(${ddd}) ${local.length===9?`${local.slice(0,5)}-${local.slice(5)}`:`${local.slice(0,4)}-${local.slice(4)}`}`}return d}
type Conversation={id:string;status:string;priority:string;unread_count:number;last_message_at?:string|null;last_message_preview?:string|null;responsible_id?:string|null;tags?:string[]|null;whatsapp_contacts?:{id:string;name?:string|null;profile_name?:string|null;phone?:string|null;whatsapp_id?:string|null}|null};
type WaMessage={id:string;direction:string;body?:string|null;created_at:string;status?:string|null};

export default function WhatsApp(){
 const[error,setError]=useState(''),[notice,setNotice]=useState(''),[connected,setConnected]=useState(false),[webhookReady,setWebhookReady]=useState(false),[orgId,setOrgId]=useState(''),[userId,setUserId]=useState(''),[aiEnabled,setAiEnabled]=useState(true),[resumeMinutes,setResumeMinutes]=useState(30);
 const[conversations,setConversations]=useState<Conversation[]>([]),[selectedId,setSelectedId]=useState(''),[messages,setMessages]=useState<WaMessage[]>([]),[reply,setReply]=useState(''),[conversationBusy,setConversationBusy]=useState(false),[loadingConversations,setLoadingConversations]=useState(true);
 const selected=useMemo(()=>conversations.find(c=>c.id===selectedId)||null,[conversations,selectedId]);
 const target=selected?.whatsapp_contacts?.whatsapp_id||selected?.whatsapp_contacts?.phone||'';
 const handler=selected&&(selected.responsible_id||selected.tags?.includes('support'))?'human':'ai';
 async function invokeWaha(body:any){if(!supabase)return {data:null,error:new Error('Supabase indisponível.')};return supabase.functions.invoke('whatsapp-waha-connect',{body})}
 async function loadSettings(){if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;setUserId(user.id);const {data:p}=await supabase.from('profiles').select('org_id').eq('id',user.id).maybeSingle();if(!p?.org_id)return;setOrgId(p.org_id);const {data}=await supabase.from('whatsapp_settings').select('ai_enabled,human_takeover_auto_resume_minutes').eq('org_id',p.org_id).maybeSingle();if(data){setAiEnabled(data.ai_enabled!==false);setResumeMinutes(Number(data.human_takeover_auto_resume_minutes??30))}}
 async function loadConversations(){if(!supabase)return;setLoadingConversations(true);const {data,error}=await supabase.from('whatsapp_conversations').select('id,status,priority,unread_count,last_message_at,last_message_preview,responsible_id,tags,whatsapp_contacts(id,name,profile_name,phone,whatsapp_id)').order('last_message_at',{ascending:false,nullsFirst:false}).limit(100);setLoadingConversations(false);if(error){setError(error.message);return}const rows=(data||[]) as unknown as Conversation[];setConversations(rows);if(rows.length&&!selectedId)setSelectedId(rows[0].id)}
 async function loadMessages(id:string){if(!supabase||!id)return;const {data,error}=await supabase.from('whatsapp_messages').select('id,direction,body,created_at,status').eq('conversation_id',id).order('created_at',{ascending:true}).limit(300);if(error){setError(error.message);return}setMessages((data||[]) as WaMessage[]);await supabase.from('whatsapp_conversations').update({unread_count:0}).eq('id',id);setConversations(v=>v.map(c=>c.id===id?{...c,unread_count:0}:c))}
 async function checkStatus(){const r=await invokeWaha({action:'status'});if(r.error||!r.data?.ok){setConnected(false);return false}setConnected(!!r.data.connected);return !!r.data.connected}
 useEffect(()=>{void loadSettings();void loadConversations();void checkStatus()},[]);
 useEffect(()=>{if(selectedId)void loadMessages(selectedId)},[selectedId]);
 useEffect(()=>{if(!connected||webhookReady)return;let cancelled=false;(async()=>{const r=await invokeWaha({action:'configure_webhook'});if(!cancelled&&!r.error&&r.data?.ok)setWebhookReady(true)})();return()=>{cancelled=true}},[connected,webhookReady]);
 useEffect(()=>{const id=setInterval(()=>{void loadConversations();if(selectedId)void loadMessages(selectedId)},8000);return()=>clearInterval(id)},[selectedId]);
 async function chooseHandler(mode:'ai'|'human',showNotice=true){if(!supabase||!selected||!orgId||conversationBusy)return;setConversationBusy(true);setError('');const now=new Date().toISOString();const contactKey=target;const tags=(selected.tags||[]).filter(t=>t!=='support');const responsible_id=mode==='human'?userId:null;const conversationPatch:any={responsible_id,tags,updated_at:now,bot_ativo:mode==='ai',human_takeover_at:mode==='ai'?null:now,conversation_owner:mode==='ai'?'CLARA':'HUMAN',owner_changed_at:now};const {error:ce}=await supabase.from('whatsapp_conversations').update(conversationPatch).eq('id',selected.id);if(ce){setConversationBusy(false);setError(ce.message);return}if(contactKey){const keys=Array.from(new Set([contactKey,digits(contactKey)].filter(Boolean)));const q=await supabase.from('ai_conversation_controls').select('id').eq('org_id',orgId).in('contact_key',keys).limit(1).maybeSingle();const controlPatch={ai_enabled:mode==='ai',human_takeover:mode==='human',human_takeover_at:mode==='ai'?null:now,resume_after_minutes:resumeMinutes,resume_at:null,updated_at:now};if(!q.data){const {error:ie}=await supabase.from('ai_conversation_controls').insert({org_id:orgId,contact_key:contactKey,...controlPatch});if(ie){setConversationBusy(false);setError(ie.message);return}}else{const {error:ue}=await supabase.from('ai_conversation_controls').update(controlPatch).eq('id',q.data.id);if(ue){setConversationBusy(false);setError(ue.message);return}}}
 setConversations(v=>v.map(c=>c.id===selected.id?{...c,responsible_id,tags}:c));setConversationBusy(false);if(showNotice)setNotice(mode==='ai'?'⚖️ Clara retomou esta conversa.':'👤 Atendimento humano ativado. Clara ficará em silêncio nesta conversa.')}
 async function sendReply(e?:any){e?.preventDefault?.();if(!supabase||!selected||!target||!reply.trim()||conversationBusy)return;setError('');setNotice('');const text=reply.trim();try{if(handler!=='human')await chooseHandler('human',false);setConversationBusy(true);const r=await invokeWaha({action:'send',chat_id:target,message:text});if(r.error||!r.data?.ok)throw new Error(await getFunctionError(r,'Falha ao enviar resposta.'));const now=new Date().toISOString();setMessages(v=>[...v,{id:`local-${Date.now()}`,direction:'outbound',body:text,created_at:now,status:'sent'}]);setReply('');setConversations(v=>v.map(c=>c.id===selected.id?{...c,last_message_preview:text,last_message_at:now,responsible_id:userId}:c));setNotice('Resposta enviada por você. Clara permanece pausada nesta conversa.');setTimeout(()=>void loadMessages(selected.id),1500)}catch(err:any){setError(err?.message||'Falha ao enviar resposta.')}finally{setConversationBusy(false)}}
 const contactName=(c:Conversation)=>c.whatsapp_contacts?.profile_name||c.whatsapp_contacts?.name||null;const contactPhone=(c:Conversation)=>formatWhatsAppPhone(c.whatsapp_contacts?.phone||c.whatsapp_contacts?.whatsapp_id);
 return <div className="wa-workspace"><div className="page-head wa-head"><div><span className="eyebrow">CLIENTE & COMUNICAÇÃO</span><h1>WhatsApp</h1><p>Conversas com Clara e atendimento humano, sem controles duplicados.</p></div><div className="ux-actions"><button className="secondary" onClick={()=>{void loadConversations();void checkStatus()}} disabled={loadingConversations}><RefreshCw size={15}/>{loadingConversations?'Atualizando...':'Atualizar'}</button><div className={`wa-status-pill ${connected?'on':''}`}><span className="status-dot"/>{connected?'Conectado':'Offline'}</div></div></div>
 <div className="wa-kpis"><div><Wifi/><span>Canal</span><strong>{connected?'Online':'Offline'}</strong></div><div><ShieldCheck/><span>Webhook</span><strong>{webhookReady?'Ativo':'Verificando'}</strong></div><div><Bot/><span>Clara</span><strong>{aiEnabled?'Disponível':'Pausada globalmente'}</strong></div><div><MessageCircle/><span>Conversas</span><strong>{conversations.length}</strong></div></div>
 {error&&<div className="status-message error" role="alert"><AlertCircle size={16}/>{error}</div>}{notice&&<div className="status-message success" role="status" aria-live="polite"><CheckCircle2 size={16}/>{notice}</div>}
 <section className="integration-panel"><h3><MessageCircle size={17}/> Conversas do WhatsApp</h3><div className="wa-conversation-grid" style={{display:'grid',gridTemplateColumns:'minmax(250px,.7fr) minmax(0,1.5fr)',gap:14,minHeight:440}}><div className="signature-list" style={{maxHeight:560,overflow:'auto'}}>{loadingConversations&&conversations.length===0?<div className="integration-empty"><RefreshCw size={26}/><p>Carregando conversas...</p></div>:conversations.length===0?<div className="integration-empty"><MessageCircle size={26}/><p>Nenhuma conversa registrada.</p></div>:conversations.map(c=>{const name=contactName(c),phoneLabel=contactPhone(c);return <button key={c.id} className={`signature-row ${selectedId===c.id?'selected':''}`} onClick={()=>setSelectedId(c.id)} style={{textAlign:'left',width:'100%',cursor:'pointer'}} aria-label={`Abrir conversa com ${name||phoneLabel}`}><div>{name?<><strong>{name}</strong><small>{phoneLabel}</small></>:<strong>{phoneLabel}</strong>}</div>{c.unread_count>0&&<span className="status-dot" aria-label={`${c.unread_count} mensagens não lidas`}>{c.unread_count}</span>}</button>})}</div>
 <div className="wa-mini-card" style={{minWidth:0}}>{!selected?<div className="integration-empty"><MessageCircle size={28}/><p>Selecione uma conversa.</p></div>:<><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><span className="eyebrow">CONVERSA</span>{contactName(selected)?<><h2 style={{margin:'3px 0'}}>{contactName(selected)}</h2><small>{contactPhone(selected)}</small></>:<h2 style={{margin:'3px 0'}}>{contactPhone(selected)}</h2>}</div><div className="ux-actions" role="group" aria-label="Responsável pela conversa"><button className={`integration-action ${handler==='ai'?'selected':''}`} onClick={()=>chooseHandler('ai')} disabled={conversationBusy||!aiEnabled} aria-pressed={handler==='ai'}><Bot size={14}/>⚖️ Clara ativa</button><button className={`secondary ${handler==='human'?'selected':''}`} onClick={()=>chooseHandler('human')} disabled={conversationBusy} aria-pressed={handler==='human'}><UserRound size={14}/>👤 Atendimento humano</button></div></div>
 <div className="wa-message-list" style={{height:310,overflow:'auto',padding:'14px 0',display:'flex',flexDirection:'column',gap:9}}>{messages.length===0?<div className="integration-empty"><p>Nenhuma mensagem nesta conversa.</p></div>:messages.map(m=><div key={m.id} style={{alignSelf:m.direction==='outbound'?'flex-end':'flex-start',maxWidth:'78%',padding:'10px 12px',border:'1px solid rgba(217,164,65,.18)',borderRadius:12,background:m.direction==='outbound'?'rgba(217,164,65,.10)':'#0b0d0f'}}><div style={{whiteSpace:'pre-wrap'}}>{m.body||'—'}</div><small style={{opacity:.65}}>{new Date(m.created_at).toLocaleString('pt-BR')}</small></div>)}</div>
 <div className="wa-manual-reply"><div className="wa-manual-reply-head"><div><UserRound size={16}/><b>Responder pessoalmente</b></div><span>{handler==='human'?'Atendimento humano ativo • Clara pausada':'Ao enviar, o atendimento humano será ativado automaticamente'}</span></div><form onSubmit={sendReply}><textarea rows={3} value={reply} onChange={e=>setReply(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void sendReply(e)}}} placeholder="Digite sua resposta ao cliente... (Enter envia • Shift+Enter quebra linha)" aria-label="Mensagem para o cliente"/><button className="integration-action" disabled={conversationBusy||!reply.trim()||!connected}><Send size={16}/>{conversationBusy?'Enviando...':'Responder agora'}</button></form>{!connected&&<small className="wa-reply-warning">Conecte o WhatsApp em Configurações → Conexões para responder por aqui.</small>}</div></>}</div></div></section></div>
}
