import {useEffect,useMemo,useState} from 'react';
import {CheckCircle2,Megaphone,Search,Send,X} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Client={id:string;name:string;phone?:string|null;whatsapp?:string|null;status?:string|null};
type Target={id:string;name:string;phone:string};
const digits=(v?:string|null)=>String(v||'').replace(/\D/g,'');
const valid=(v?:string|null)=>{const d=digits(v);return d.length>=10&&d.length<=15};

export default function BulkClientMessageBridge(){
 const db:any=supabase;
 const[open,setOpen]=useState(false);const[clients,setClients]=useState<Client[]>([]);const[search,setSearch]=useState('');const[selected,setSelected]=useState<string[]>([]);const[text,setText]=useState('');const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');
 useEffect(()=>{const click=(ev:MouseEvent)=>{if(window.location.pathname!='/atendimento')return;const btn=(ev.target as HTMLElement|null)?.closest?.('button') as HTMLButtonElement|null;if(!btn)return;const label=(btn.innerText||'').replace(/\s+/g,' ').trim().toLowerCase();if(label!=='mensagem em massa')return;ev.preventDefault();ev.stopPropagation();(ev as any).stopImmediatePropagation?.();void show()};document.addEventListener('click',click,true);return()=>document.removeEventListener('click',click,true)},[]);
 async function show(){setNotice('');setOpen(true);if(!db)return;const {data,error}=await db.from('clients').select('id,name,phone,whatsapp,status').order('name').limit(5000);if(error){setNotice(error.message);return}setClients((data||[]) as Client[])}
 const eligible=useMemo(()=>{const byPhone=new Map<string,Target>();for(const c of clients){const phone=c.whatsapp||c.phone;if(!c.name?.trim()||!valid(phone))continue;const key=digits(phone);if(!byPhone.has(key))byPhone.set(key,{id:c.id,name:c.name.trim(),phone:String(phone)});}return [...byPhone.values()]},[clients]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return eligible.filter(c=>!q||`${c.name} ${c.phone}`.toLowerCase().includes(q))},[eligible,search]);
 function toggle(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 function toggleAll(){const ids=visible.map(x=>x.id),all=ids.length>0&&ids.every(id=>selected.includes(id));setSelected(v=>all?v.filter(id=>!ids.includes(id)):Array.from(new Set([...v,...ids])))}
 async function send(){if(!text.trim()||!selected.length||busy)return;const targets=eligible.filter(x=>selected.includes(x.id)).map(x=>({phone:x.phone,name:x.name}));if(!targets.length)return; if(!window.confirm(`Enviar esta mensagem para ${targets.length} cliente(s)?`))return;setBusy(true);setNotice('');let sent=0,failed=0;try{for(let i=0;i<targets.length;i+=100){const batch=targets.slice(i,i+100);const {data,error}=await db.functions.invoke('whatsapp-operator-send',{body:{message:text.trim(),targets:batch}});if(error){failed+=batch.length;continue}sent+=Number(data?.sent||0);failed+=Number(data?.failed||0)}setNotice(`${sent} mensagem(ns) enviada(s)${failed?` · ${failed} falha(s)`:''}.`);if(sent){setSelected([]);setText('')}if(!failed&&sent) setTimeout(()=>setOpen(false),900)}finally{setBusy(false)}}
 if(!open)return null;
 return <div style={{position:'fixed',inset:0,zIndex:2500,background:'rgba(0,0,0,.72)',display:'grid',placeItems:'center',padding:16}} onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setOpen(false)}}><div style={{width:'min(820px,96vw)',maxHeight:'90vh',overflow:'auto',background:'#0d141e',border:'1px solid #334258',borderRadius:16,padding:18}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><h2 style={{margin:0}}><Megaphone size={20}/> Mensagem em massa</h2><p style={{margin:'6px 0 0',opacity:.75}}>Lista carregada diretamente do cadastro de clientes, inclusive quem ainda não iniciou conversa no Atendimento.</p></div><button className="icon-btn" onClick={()=>setOpen(false)} disabled={busy}><X size={20}/></button></div><div className="integration-notice" style={{margin:'14px 0'}}><CheckCircle2 size={15}/> {eligible.length} clientes com WhatsApp/telefone válido disponíveis.</div><div style={{display:'flex',gap:8,marginBottom:10}}><label className="service-search" style={{margin:0,flex:1}}><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente por nome ou WhatsApp"/></label><button className="secondary" onClick={toggleAll}>{visible.length&&visible.every(x=>selected.includes(x.id))?'Desmarcar':'Selecionar'} visíveis</button></div><div style={{maxHeight:320,overflow:'auto',border:'1px solid #29384b',borderRadius:12}}>{visible.map(c=><label key={c.id} style={{display:'flex',alignItems:'center',gap:10,padding:'10px 12px',borderBottom:'1px solid #202c3a'}}><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>toggle(c.id)}/><div style={{flex:1,minWidth:0}}><strong style={{display:'block'}}>{c.name}</strong><small style={{opacity:.7}}>{c.phone}</small></div>{selected.includes(c.id)&&<CheckCircle2 size={16}/>}</label>)}{!visible.length&&<div style={{padding:28,textAlign:'center',opacity:.7}}>Nenhum cliente encontrado.</div>}</div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Digite a mensagem para os clientes selecionados..." style={{width:'100%',minHeight:120,marginTop:14,boxSizing:'border-box'}}/>{notice&&<div className="integration-notice" style={{marginTop:12}}>{notice}</div>}<div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginTop:12}}><span>{selected.length} destinatário(s) selecionado(s)</span><button className="primary" disabled={busy||!text.trim()||!selected.length} onClick={()=>void send()}><Send size={16}/>{busy?'Enviando...':'Revisar e enviar'}</button></div></div></div>
}
