import { useEffect,useState } from 'react';
import { Clipboard,Link2,X,CheckCircle2,MessageCircle } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import { supabase } from '../lib/supabase';

const PROD_ORIGIN='https://lexoffice.univittagroup.com.br';
export default function ClientFormShareAction(){
 const location=useLocation();
 const [signed,setSigned]=useState(false),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[url,setUrl]=useState(''),[expires,setExpires]=useState(''),[error,setError]=useState(''),[copied,setCopied]=useState(false),[target,setTarget]=useState<any>(null);
 const onClients=location.pathname==='/clientes'||location.pathname.startsWith('/clientes/');
 useEffect(()=>{const handler=(e:any)=>{const detail=e?.detail||null;setTarget(detail);void generateAndSend(detail)};window.addEventListener('lexoffice:share-client-form',handler);return()=>window.removeEventListener('lexoffice:share-client-form',handler)},[]);
 useEffect(()=>{let active=true;supabase.auth.getSession().then(({data})=>{if(active)setSigned(Boolean(data.session))});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{if(active)setSigned(Boolean(s))});return()=>{active=false;subscription.unsubscribe()}},[]);
 if(!onClients||!signed)return null;
 async function markSent(link:string,phone:string,name:string){try{const token=decodeURIComponent(link.split('/formulario-cliente/')[1]||'');if(token)await supabase.rpc('client_intake_mark_sent',{p_token:token,p_phone:phone,p_name:name||null,p_url:link})}catch{/* lembrete é opcional: nunca bloqueia o envio */}}
 async function generate(detail:any=null){setBusy(true);setError('');setCopied(false);try{const {data,error}=await supabase.functions.invoke('client-intake-link-create',{body:{client_id:detail?.clientId||null}});if(error)throw error;if(!data?.token)throw new Error(data?.error||'Não foi possível gerar o link.');const origin=window.location.hostname==='localhost'?PROD_ORIGIN:window.location.origin;setUrl(`${origin}/formulario-cliente/${encodeURIComponent(data.token)}`);setExpires(data.expires_at||'');setOpen(true)}catch(e:any){setError(e?.message||'Não foi possível gerar o link.');setOpen(true)}finally{setBusy(false)}}
 async function generateAndSend(detail:any){setBusy(true);setError('');setCopied(false);try{const {data,error}=await supabase.functions.invoke('client-intake-link-create',{body:{client_id:detail?.clientId||null}});if(error)throw error;if(!data?.token)throw new Error(data?.error||'Não foi possível gerar o link.');const origin=window.location.hostname==='localhost'?PROD_ORIGIN:window.location.origin;const generatedUrl=`${origin}/formulario-cliente/${encodeURIComponent(data.token)}`;setUrl(generatedUrl);setExpires(data.expires_at||'');const phone=String(detail?.phone||'').replace(/\D/g,'');if(!phone)throw new Error('Cliente sem WhatsApp cadastrado.');const number=phone.startsWith('55')?phone:`55${phone}`;const message=`Olá${detail?.clientName?', '+detail.clientName:''}! Para corrigir ou atualizar seus dados cadastrais, preencha novamente sua ficha pelo link abaixo:\n\n${generatedUrl}\n\nO link é individual, seguro e válido por 7 dias.`;const {data:sent,error:sendError}=await supabase.functions.invoke('whatsapp-operator-send',{body:{message,targets:[{phone:number,name:detail?.clientName||''}],agent_key:'client_schedule_relationship',next_agent_key:'client_schedule_relationship',keep_ai_active:true,mirror_to_app:false}});if(sendError||!sent?.ok||sent?.failed)throw new Error(sendError?.message||sent?.results?.[0]?.error||sent?.error||'Falha no envio pelo WhatsApp.');await markSent(generatedUrl,number,detail?.clientName||'');setOpen(true);setCopied(true);setTimeout(()=>setCopied(false),2200)}catch(e:any){setError(e?.message||'Não foi possível enviar o link.');setOpen(true)}finally{setBusy(false)}}
 async function copy(){if(!url)return;await navigator.clipboard.writeText(url);setCopied(true);setTimeout(()=>setCopied(false),2200)}
 async function shareWhatsApp(){if(!url)return;const message=`Olá${target?.clientName?', '+target.clientName:''}! Para corrigir ou atualizar seus dados cadastrais, preencha novamente sua ficha pelo link abaixo:\n\n${url}\n\nO link é individual, seguro e válido por 7 dias.`;const phone=String(target?.phone||'').replace(/\D/g,'');if(phone){try{const number=phone.startsWith('55')?phone:`55${phone}`;const {data,error}=await supabase.functions.invoke('whatsapp-operator-send',{body:{message,targets:[{phone:number,name:target?.clientName||''}],agent_key:'client_schedule_relationship',next_agent_key:'client_schedule_relationship',keep_ai_active:true,mirror_to_app:false}});if(!error&&data?.ok&&!data?.failed){await markSent(url,number,target?.clientName||'');setCopied(true);setTimeout(()=>setCopied(false),2200);return}}catch{}}window.open(`https://wa.me/?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')}
 return <>
  <button className="client-share-trigger" type="button" onClick={generate} disabled={busy} aria-label="Gerar link para novo cadastro de cliente"><Link2 size={16}/>{busy?'Gerando link...':'Novo cadastro por link'}</button>
  {open&&<div className="client-share-overlay" onClick={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="client-share-modal" role="dialog" aria-modal="true" aria-labelledby="share-client-title"><button className="client-share-close" onClick={()=>setOpen(false)} aria-label="Fechar"><X size={18}/></button><h2 id="share-client-title"><Link2 size={20}/> Formulário do cliente</h2>{error?<div className="client-share-error">{error}</div>:<><p>Envie este link ao cliente. Ele poderá preencher os próprios dados sem acessar o LEXOFFICE.</p><div className="client-share-url"><input readOnly value={url}/><button type="button" onClick={copy}>{copied?<CheckCircle2 size={16}/>:<Clipboard size={16}/>} {copied?'Copiado':'Copiar link'}</button><button type="button" onClick={shareWhatsApp}><MessageCircle size={16}/> Enviar pelo WhatsApp</button></div><small>Válido por 7 dias e para um único envio.{expires?` Expira em ${new Date(expires).toLocaleString('pt-BR')}.`:''}</small></>}</div></div>}
 </>;
}
