import { useEffect,useMemo,useState } from 'react';
import { Bot,CalendarDays,CheckCircle2,Clock3,Loader2,Send,X } from 'lucide-react';
import { supabase } from '../lib/supabase';

type Client={id?:string|null;name:string;phone:string|null;whatsapp:string|null};
type Agent={agent_key:string;name:string;is_active:boolean};
type Props={client:Client;conversationId?:string|null;initialMessage?:string;onClose:()=>void;onSent?:(message:string)=>void};

const digits=(v:any)=>String(v??'').replace(/\D/g,'');
const localNow=()=>{const d=new Date();const p=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(d).replace(' ','T');return p.slice(0,16)};

export default function ClientMessageScheduler({client,conversationId:providedConversationId=null,initialMessage='',onClose,onSent}:Props){
 const [message,setMessage]=useState(initialMessage),[mode,setMode]=useState<'now'|'schedule'>('schedule'),[when,setWhen]=useState(localNow()),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const [agents,setAgents]=useState<Agent[]>([]),[agentKey,setAgentKey]=useState('client_schedule_relationship');
 const phone=digits(client.whatsapp||client.phone);
 useEffect(()=>{(async()=>{if(!supabase)return;const {data}=await supabase.from('ai_agents').select('agent_key,name,is_active').eq('is_active',true).order('name');setAgents((data||[]) as Agent[])})()},[]);
 const selectedAgent=useMemo(()=>agents.find(a=>a.agent_key===agentKey)?.name||'Agente de Agenda e Relacionamento',[agents,agentKey]);
 async function resolveConversationId(){if(providedConversationId)return providedConversationId;if(!supabase||!client.id)return null;const {data:contact}=await supabase.from('whatsapp_contacts').select('id').eq('client_id',client.id).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(!contact?.id)return null;const {data:conv}=await supabase.from('whatsapp_conversations').select('id').eq('contact_id',contact.id).neq('status','closed').order('updated_at',{ascending:false}).limit(1).maybeSingle();return conv?.id||null}
 async function act(){if(!supabase||busy)return;if(!phone)return setError('Este contato não possui WhatsApp válido.');if(!message.trim())return setError('Digite a mensagem.');setBusy(true);setError('');setNotice('');try{const conv=await resolveConversationId();if(mode==='now'){const {data,error}=await supabase.functions.invoke('whatsapp-operator-send',{body:{message:message.trim(),targets:[{phone,conversation_id:conv,name:client.name}]}});if(error)throw error;if(Number((data as any)?.sent||0)!==1)throw new Error((data as any)?.results?.[0]?.error||(data as any)?.error||'A Meta não confirmou o envio.');setNotice('Mensagem enviada pelo WhatsApp oficial.');onSent?.(`Mensagem enviada para ${client.name}.`);return}
 if(!when)throw new Error('Escolha a data e a hora.');const scheduledAt=new Date(`${when}:00-03:00`);if(Number.isNaN(scheduledAt.getTime()))throw new Error('Data ou hora inválida.');if(scheduledAt.getTime()<=Date.now())throw new Error('Escolha uma data e hora futuras.');const {data:u,error:ue}=await supabase.auth.getUser();if(ue||!u.user)throw new Error('Sua sessão expirou. Entre novamente.');const {data:p,error:pe}=await supabase.from('profiles').select('org_id').eq('id',u.user.id).maybeSingle();if(pe||!p?.org_id)throw new Error('Não foi possível identificar o escritório.');const {error}=await supabase.from('scheduled_client_messages').insert({org_id:p.org_id,client_id:client.id||null,conversation_id:conv,client_name:client.name,phone,message:message.trim(),agent_key:agentKey,scheduled_at:scheduledAt.toISOString(),status:'pending',created_by:u.user.id});if(error)throw error;setNotice(`Mensagem programada para ${new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}).format(scheduledAt)} com ${selectedAgent}.`);onSent?.(`Mensagem de ${client.name} programada com ${selectedAgent}.`)}catch(e:any){setError(e?.message||'Não foi possível concluir a ação.')}finally{setBusy(false)}}
 return <div className="modal-overlay" style={{zIndex:1800}} onClick={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><div className="modal-card" style={{maxWidth:680}}><div className="modal-head"><div><h2><Clock3 size={20}/> Programar mensagem</h2><p>{client.name} · {client.whatsapp||client.phone}</p></div><button className="icon-btn ux-modal-close" aria-label="Fechar" disabled={busy} onClick={onClose}><X size={20}/></button></div><div className="integration-notice" style={{marginBottom:14,alignItems:'flex-start'}}><Bot size={16}/><div><b>Escolha qual agente fará o envio</b><small style={{display:'block',marginTop:3}}>O agente selecionado fica gravado junto com a mensagem, a data e a hora.</small></div></div><div style={{display:'flex',gap:10,marginBottom:14,flexWrap:'wrap'}}><button type="button" className={mode==='schedule'?'primary':'secondary'} onClick={()=>setMode('schedule')}><Clock3 size={15}/> Programar</button><button type="button" className={mode==='now'?'primary':'secondary'} onClick={()=>setMode('now')}><Send size={15}/> Enviar agora</button></div><label style={{display:'block',marginBottom:12}}><span style={{display:'block',fontWeight:700,fontSize:12,marginBottom:7}}>Mensagem</span><textarea autoFocus value={message} maxLength={4000} onChange={e=>setMessage(e.target.value)} placeholder="Digite a mensagem para o cliente..." style={{width:'100%',minHeight:140,resize:'vertical',boxSizing:'border-box'}}/></label>{mode==='schedule'&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,marginBottom:14}}><label><span style={{display:'block',fontWeight:700,fontSize:12,marginBottom:7}}><CalendarDays size={13}/> Data e hora</span><input type="datetime-local" value={when} min={localNow()} onChange={e=>setWhen(e.target.value)} style={{width:'100%'}}/></label><label><span style={{display:'block',fontWeight:700,fontSize:12,marginBottom:7}}><Bot size={13}/> Agente que enviará</span><select value={agentKey} onChange={e=>setAgentKey(e.target.value)} style={{width:'100%'}}>{agents.length?agents.map(a=><option key={a.agent_key} value={a.agent_key}>{a.name}</option>):<><option value="client_schedule_relationship">Agente de Agenda e Relacionamento</option><option value="sales">Agente Comercial e Vendas</option></>}</select></label></div>}{notice&&<div className="integration-notice" role="status" style={{marginBottom:12}}><CheckCircle2 size={15}/>{notice}</div>}{error&&<div className="alert error" role="alert" style={{marginBottom:12}}>{error}</div>}<div className="modal-actions"><button className="secondary" disabled={busy} onClick={onClose}>Fechar</button><button className="primary" disabled={busy||!message.trim()} onClick={act}>{busy?<Loader2 size={15} className="spin"/>:mode==='schedule'?<Clock3 size={15}/>:<Send size={15}/>} {busy?'Salvando...':mode==='schedule'?'Programar envio':'Enviar agora'}</button></div></div></div>
}
