import React,{useEffect,useState} from "react";
import {ActivityIndicator,Alert,Pressable,StyleSheet,Text,TextInput,View} from "react-native";
import {NavigationContainer} from "@react-navigation/native";
import {createBottomTabNavigator} from "@react-navigation/bottom-tabs";
import {createNativeStackNavigator} from "@react-navigation/native-stack";
import {Ionicons} from "@expo/vector-icons";
import {StatusBar} from "expo-status-bar";
import {supabase} from "./src/supabase";
import {C} from "./src/theme";
import {registerPush} from "./src/mobile";
import {Home,Process,Messages,Documents,Steps,Finance,Atendimento,Communication,Profile} from "./src/screens";
const Tab=createBottomTabNavigator(),Stack=createNativeStackNavigator();
function Login(){const[cpf,setCpf]=useState(""),[code,setCode]=useState(""),[busy,setBusy]=useState(false);async function login(){const digits=cpf.replace(/\D/g,"");if(digits.length!==11||!code.trim())return Alert.alert("Confira seus dados","Informe seu CPF e o código de acesso fornecido pelo escritório.");setBusy(true);const{data,error}=await supabase.functions.invoke("swift-service?action=client-app-auth",{body:{cpf:digits,access_code:code.trim()}});if(error||!data?.email||!data?.password){setBusy(false);return Alert.alert("Não foi possível entrar","CPF ou código de acesso inválido.");}const r=await supabase.auth.signInWithPassword({email:data.email,password:data.password});setBusy(false);if(r.error)Alert.alert("Não foi possível entrar","CPF ou código de acesso inválido.")}return <View style={s.login}><View style={s.monogram}><Text style={s.sf}>SF</Text></View><Text style={s.brand}>SUZANNE FIGUEIREDO</Text><Text style={s.sub}>ADVOCACIA E SOLUÇÕES JURÍDICAS</Text><Text style={s.welcome}>Bem-vinda ao nosso escritório!</Text><Text style={s.quoteTop}>Mais que direito, soluções para a sua vida.</Text><TextInput style={s.input} keyboardType="numeric" placeholder="Seu CPF" value={cpf} onChangeText={setCpf} maxLength={14}/><TextInput style={s.input} autoCapitalize="characters" secureTextEntry placeholder="Código de acesso" value={code} onChangeText={setCode}/><Pressable style={s.btn} onPress={login}><Text style={s.bt}>{busy?"Entrando...":"Começar"}</Text></Pressable></View>}
function HomeStack(){return <Stack.Navigator screenOptions={{headerStyle:{backgroundColor:C.paper},headerTintColor:C.gold,headerTitleStyle:{fontFamily:"serif",color:C.ink},headerShadowVisible:false}}><Stack.Screen name="Painel" component={Home} options={{headerShown:false}}/><Stack.Screen name="Processo" component={Process} options={{title:"Meu Processo"}}/><Stack.Screen name="Documentos" component={Documents}/><Stack.Screen name="Passos" component={Steps} options={{title:"O que acontece agora?"}}/><Stack.Screen name="Financeiro" component={Finance}/><Stack.Screen name="Atendimento" component={Atendimento}/><Stack.Screen name="Comunicação" component={Communication} options={{title:"Falar com o Escritório"}}/></Stack.Navigator>}
export default function App(){const[session,setSession]=useState<any>(undefined);useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,x)=>setSession(x));return()=>subscription.unsubscribe()},[]);useEffect(()=>{if(session)registerPush().catch(()=>{})},[session?.user?.id]);if(session===undefined)return <View style={s.loading}><ActivityIndicator color={C.gold}/></View>;if(!session)return <><StatusBar style="dark"/><Login/></>;return <NavigationContainer><StatusBar style="dark"/><Tab.Navigator screenOptions={({route})=>({headerShown:false,tabBarActiveTintColor:C.gold2,tabBarInactiveTintColor:"#BEB6AB",tabBarLabelStyle:{fontSize:11},tabBarStyle:{backgroundColor:C.black,height:72,paddingTop:7,paddingBottom:9,borderTopColor:"#2A2118"},tabBarIcon:({color,size})=><Ionicons name={({Início:"home-outline",Notificações:"notifications-outline",Perfil:"person-outline"} as any)[route.name]} size={size} color={color}/>})}><Tab.Screen name="Início" component={HomeStack}/><Tab.Screen name="Notificações" component={Messages}/><Tab.Screen name="Perfil" component={Profile}/></Tab.Navigator></NavigationContainer>}
const s=StyleSheet.create({loading:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:C.paper},login:{flex:1,backgroundColor:C.black,padding:30,justifyContent:"center"},monogram:{alignSelf:"center",width:108,height:108,borderWidth:1,borderColor:C.gold,borderRadius:54,alignItems:"center",justifyContent:"center",marginBottom:18},sf:{fontFamily:"serif",fontSize:50,textAlign:"center",color:C.gold2,fontWeight:"700"},brand:{fontFamily:"serif",fontSize:23,textAlign:"center",letterSpacing:2,color:C.gold2},sub:{fontSize:9,textAlign:"center",letterSpacing:2,color:C.gold,marginTop:5},welcome:{fontFamily:"serif",fontSize:29,textAlign:"center",marginTop:34,color:C.cream},quoteTop:{fontFamily:"serif",fontStyle:"italic",textAlign:"center",color:C.gold2,marginTop:8,marginBottom:28,fontSize:17},input:{borderWidth:1,borderColor:"#5B452D",borderRadius:12,padding:15,marginBottom:12,backgroundColor:C.cream,color:C.ink},btn:{backgroundColor:C.gold,borderRadius:10,padding:15,marginTop:10},bt:{color:"#fff",textAlign:"center",fontWeight:"700",fontSize:15}});
