import React,{useEffect,useState} from "react";
import {ActivityIndicator,Alert,Pressable,StyleSheet,Text,TextInput,View} from "react-native";
import {NavigationContainer} from "@react-navigation/native";
import {createBottomTabNavigator} from "@react-navigation/bottom-tabs";
import {Ionicons} from "@expo/vector-icons";
import {StatusBar} from "expo-status-bar";
import {supabase} from "./src/supabase";
import {C} from "./src/theme";
import {Home,Process,Messages,Documents,Steps,Finance,Atendimento,Profile} from "./src/screens";
const Tab=createBottomTabNavigator();
function Login(){const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false);async function login(){setBusy(true);const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)Alert.alert("Não foi possível entrar",error.message)}return <View style={s.login}><Text style={s.sf}>SF</Text><Text style={s.brand}>SUZANNE FIGUEIREDO</Text><Text style={s.sub}>ADVOCACIA E SOLUÇÕES JURÍDICAS</Text><Text style={s.welcome}>Bem-vinda ao seu espaço exclusivo.</Text><TextInput style={s.input} autoCapitalize="none" keyboardType="email-address" placeholder="Seu e-mail" value={email} onChangeText={setEmail}/><TextInput style={s.input} secureTextEntry placeholder="Sua senha" value={password} onChangeText={setPassword}/><Pressable style={s.btn} onPress={login}><Text style={s.bt}>{busy?"Entrando...":"Entrar"}</Text></Pressable><Text style={s.quote}>Mais que direito, soluções para a sua vida.</Text></View>}
export default function App(){const [session,setSession]=useState<any>(undefined);useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,x)=>setSession(x));return()=>subscription.unsubscribe()},[]);if(session===undefined)return <View style={s.loading}><ActivityIndicator color={C.gold}/></View>;if(!session)return <><StatusBar style="dark"/><Login/></>;return <NavigationContainer><StatusBar style="dark"/><Tab.Navigator screenOptions={({route})=>({headerShown:false,tabBarActiveTintColor:C.gold,tabBarInactiveTintColor:"#8A8178",tabBarStyle:{backgroundColor:C.black,height:68,paddingBottom:9},tabBarIcon:({color,size})=><Ionicons name={({Início:"home-outline",Processo:"document-text-outline",Recados:"mail-outline",Documentos:"folder-outline",Passos:"git-branch-outline",Financeiro:"wallet-outline",Atendimento:"people-outline",Perfil:"person-outline"} as any)[route.name]} size={size} color={color}/>})}><Tab.Screen name="Início" component={Home}/><Tab.Screen name="Processo" component={Process}/><Tab.Screen name="Recados" component={Messages}/><Tab.Screen name="Documentos" component={Documents}/><Tab.Screen name="Passos" component={Steps}/><Tab.Screen name="Financeiro" component={Finance}/><Tab.Screen name="Atendimento" component={Atendimento}/><Tab.Screen name="Perfil" component={Profile}/></Tab.Navigator></NavigationContainer>}
const s=StyleSheet.create({loading:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:C.paper},login:{flex:1,backgroundColor:C.paper,padding:30,justifyContent:"center"},sf:{fontFamily:"serif",fontSize:66,textAlign:"center",color:C.gold,fontWeight:"700"},brand:{fontFamily:"serif",fontSize:22,textAlign:"center",letterSpacing:2,color:C.ink},sub:{fontSize:9,textAlign:"center",letterSpacing:2,color:C.gold,marginTop:4},welcome:{fontFamily:"serif",fontSize:25,textAlign:"center",marginVertical:34,color:C.ink},input:{borderWidth:1,borderColor:C.line,borderRadius:12,padding:15,marginBottom:12,backgroundColor:"#fff"},btn:{backgroundColor:C.gold,borderRadius:10,padding:14,marginTop:12},bt:{color:"#fff",textAlign:"center",fontWeight:"700"},quote:{fontFamily:"serif",fontStyle:"italic",textAlign:"center",color:C.gold,marginTop:30,fontSize:16}});