import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, x-lexoffice-webhook-key","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const digits=(v:any)=>String(v??'').replace(/\D/g,'');
const idPhone=(v:any)=>digits(String(v??'').split('@')[0]);
const extId=(p:any)=>typeof p?.id==='string'?p.id:typeof p?.id?JSON.stringify(p.id):null;
const ignored=(v:any)=>{const s=String(v??'').toLowerCase();return !s||s==='status@broadcast'||s.endsWith('@g.us')||s.endsWith('@broadcast')||s.endsWith('@newsletter')};
function admin(){const u=Deno.env.get('SUPABASE_URL')!,k=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;if(!u||!k)throw new Error('Supabase admin indisponível');return createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}})}
function cfg(){const base=(Deno.env.get('WAHA_API_URL')||'').replace(/\/$/,''),key=(Deno.env.get('WAHA_API_KEY')||'').trim(),session=(Deno.env.get('WAHA_SESSION')||'lexoffice').trim();if(!base||!key)throw new Error('WAHA não configurado');return{base,key,session}}
async function waha(path:string,init:RequestInit={}){const c=cfg();const r=await fetch(`${c.base}${path}`,{...init,headers:{'X-Api-Key':c.key,'Accept':'application/json',...(init.body?{'Content-Type':'application/json'}:{}),...(init.headers||{})}});const raw=await r.text();let d:any;try{d=raw?JSON.parse(raw):{}}catch{d={raw}}if(!r.ok)throw new Error(d?.message||d?.error||raw||`WAHA ${r.status}`);return d}
async function send(target:string,text:string){const c=cfg();const p=idPhone(target);let chatId=String(target||'');if(!chatId.includes('@')){try{const q=await waha(`/api/contacts/check-exists?phone=${encodeURIComponent(p)}&session=${encodeURIComponent(c.session)}`);chatId=q?.chatId||`${p}@c.us`}catch{chatId=`${p}@c.us`}}return waha('/api/sendText',{method:'POST',body:JSON.stringify({session:c.session,chatId,text})})}
async function resolveOrg(db:any,phone:string,wid:string){const forced=(Deno.env.get('LEXOFFICE_ORG_ID')||'').trim();if(forced)return forced;const ids=new Set<string>();for(const [f,v] of [['whatsapp_id',wid],['phone',phone]])if(v){const {data}=await db.from('whatsapp_contacts').select('org_id').eq(f,v).limit(10);for(const x of data||[])if(x.org_id)ids.add(x.org_id)}if(ids.size===1)return [...ids][0];const {data}=await db.from('integration_connections').select('org_id,settings').eq('provider','whatsapp').eq('status','connected');const xs=[...new Set((data||[]).filter((x:any)=>String(x?.settings?.provider||'').toLowerCase()==='waha').map((x:any)=>x.org_id).filter(Boolean))];if(xs.length===1)return xs[0];throw new Error('Organização do WhatsApp não determinada')}
async function ensure(db:any,org:string,phone:string,wid:string){let {data:contact}=await db.from('whatsapp_contacts').select('*').eq('org_id',org).eq('phone',phone).limit(1).maybeSingle();if(!contact&&wid){const q=await db.from('whatsapp_contacts').select('*').eq('org_id',org).eq('whatsapp_id',wid).limit(1).maybeSingle();contact=q.data}if(!contact){const r=await db.from('whatsapp_contacts').insert({org_id:org,phone:phone||null,whatsapp_id:wid||null}).select('*').single();if(r.error)throw r.error;contact=r.data}let {data:conv}=await db.from('whatsapp_conversations').select('*').eq('org_id',org).eq('contact_id',contact.id).neq('status','closed').order('updated_at',{ascending:false}).limit(1).maybeSingle();if(!conv){const r=await db.from('whatsapp_conversations').insert({org_id:org,contact_id:contact.id,client_id:contact.client_id||null,lead_id:contact.lead_id||null,status:'open',priority:'normal',bot_ativo:true}).select('*').single();if(r.error)throw r.error;conv=r.data}return{contact,conversation:conv}}
async function store(db:any,org:string,c:any,p:any,text:string,fromMe:boolean){const eid=extId(p);if(eid){const {data}=await db.from('whatsapp_messages').select('id').eq('org_id',org).eq('external_message_id',eid).maybeSingle();if(data)return false}const now=new Date().toISOString();const r=await db.from('whatsapp_messages').insert({org_id:org,conversation_id:c.id,external_message_id:eid,direction:fromMe?'outbound':'inbound',message_type:'text',body:text,status:fromMe?'sent':'received',sent_at:fromMe?now:null,metadata:{source:p?.source||null,from:p?.from||null,to:p?.to||null,fromMe}});if(r.error&&String(r.error.code)!=='23505')throw r.error;await db.from('whatsapp_conversations').update({last_message_at:now,last_message_preview:text.slice(0,240),unread_count:fromMe?(c.unread_count||0):(c.unread_count||0)+1,updated_at:now}).eq('id',c.id);return true}
async function ctl(db:any,org:string,key:string){let {data}=await db.from('ai_conversation_controls').select('*').eq('org_id',org).eq('contact_key',key).maybeSingle();if(!data){const r=await db.from('ai_conversation_controls').insert({org_id:org,contact_key:key,ai_enabled:true,human_takeover:false,resume_after_minutes:0,resume_keyword:'#ia',resume_at:null}).select('*').single();data=r.data}return data}
async function stopAll(db:any,org:string,c:any,control:any,reason:string){const now=new Date().toISOString();await db.from('whatsapp_conversations').update({bot_ativo:false,human_takeover_at:now,human_takeover_reason:reason,updated_at:now}).eq('org_id',org).eq('id',c.id);if(control?.id)await db.from('ai_conversation_controls').update({ai_enabled:false,human_takeover:true,human_takeover_at:now,last_human_message_at:now,resume_after_minutes:0,resume_at:null,updated_at:now}).eq('id',control.id)}
async function resume(db:any,org:string,c:any,control:any){const now=new Date().toISOString();await db.from('whatsapp_conversations').update({bot_ativo:true,human_takeover_at:null,human_takeover_by:null,human_takeover_reason:null,updated_at:now}).eq('org_id',org).eq('id',c.id);if(control?.id)await db.from('ai_conversation_controls').update({ai_enabled:true,human_takeover:false,human_takeover_at:null,resume_at:null,resume_after_minutes:0,updated_at:now}).eq('id',control.id)}
async function gate(db:any,org:string,id:string){const {data}=await db.from('whatsapp_conversations').select('bot_ativo').eq('org_id',org).eq('id',id).maybeSingle();return data?.bot_ativo===true}
function classify(t:string){if(/(boleto|pix|pagamento|parcela|cobran[cç]a|financeir)/i.test(t))return'billing';if(/(processo|andamento|movimenta[cç][aã]o|intima[cç][aã]o|senten[cç]a|decis[aã]o|prazo)/i.test(t))return'client_process_updates';if(/(agenda|agendar|marcar|hor[aá]rio|consulta|reuni[aã]o|disponib)/i.test(t))return'client_schedule_relationship';if(/(pre[cç]o|honor[aá]rio|contrat|proposta|or[cç]amento)/i.test(t))return'sales';return'client_service_triage'}
async function policy(db:any,org:string,text:string){let {data}=await db.from('ai_agent_policies').select('*').eq('org_id',org).eq('agent_key',classify(text)).eq('active',true).contains('allowed_channels',['whatsapp']).maybeSingle();if(!data)({data}=await db.from('ai_agent_policies').select('*').eq('org_id',org).eq('agent_key','client_service_triage').eq('active',true).contains('allowed_channels',['whatsapp']).maybeSingle());return data}
async function ai(db:any,org:string,p:any,c:any,text:string){const url=Deno.env.get('SUPABASE_URL')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const {data:h}=await db.from('whatsapp_messages').select('direction,body').eq('org_id',org).eq('conversation_id',c.id).order('created_at',{ascending:false}).limit(12);const history=(h||[]).reverse().map((m:any)=>`${m.direction==='inbound'?'Cliente':'Escritório'}: ${m.body||''}`).join('\n');const guard='REGRA DE EXECUÇÃO: se bot_ativo=false ou houver intervenção humana, não responda absolutamente nada e não execute ferramentas. Consultas são somente ONLINE, por Google Meet ou Zoom com link real; jamais agende presencialmente e jamais invente link. ';const r=await fetch(`${url}/functions/v1/ai-provider-gateway`,{method:'POST',headers:{Authorization:`Bearer ${service}`,apikey:service,'Content-Type':'application/json'},body:JSON.stringify({org_id:org,provider:p?.provider||'auto',model:p?.model||'',instructions:guard+(p?.system_prompt||''),input:`Histórico:\n${history}\n\nMensagem atual: ${text}`})});const d=await r.json().catch(()=>null);return r.ok&&d?.ok?String(d.text||'').trim():''}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({ok:false,error:'Método inválido'},405);try{const c=cfg(),key=(req.headers.get('x-lexoffice-webhook-key')||'').trim();if(key!==c.key)return json({ok:false,error:'Webhook não autorizado'},401);const body=await req.json().catch(()=>null);if(!body||body.event!=='message')return json({ok:true,ignored:'event'});const p=body.payload||{},fromMe=p.fromMe===true,text=String(p.body||'').trim(),raw=String(fromMe?p.to:p.from||'').trim(),source=String(p.source||'').toLowerCase();if(!text||ignored(raw))return json({ok:true,ignored:'unsupported'});const phone=idPhone(raw),db=admin(),org=await resolveOrg(db,phone,raw),{conversation}=await ensure(db,org,phone,raw);const fresh=await store(db,org,conversation,p,text,fromMe);if(!fresh)return json({ok:true,ignored:'duplicate'});const control=await ctl(db,org,phone||raw),keyword=String(control?.resume_keyword||'#ia').toLowerCase();if(fromMe){if(text.toLowerCase()===keyword){await resume(db,org,conversation,control);return json({ok:true,action:'ai_resumed_explicitly'})}if(source!=='api'||conversation.responsible_id){await stopAll(db,org,conversation,control,'human_operator_message');return json({ok:true,action:'human_takeover',bot_ativo:false})}return json({ok:true,ignored:'system_outgoing'})}if(!(await gate(db,org,conversation.id))||control?.human_takeover===true||control?.ai_enabled===false)return json({ok:true,action:'stored_no_ai',bot_ativo:false});const pcy=await policy(db,org,text);if(!pcy)return json({ok:true,action:'no_active_policy'});const reply=await ai(db,org,pcy,conversation,text);if(!reply)return json({ok:true,action:'no_ai_reply'});if(!(await gate(db,org,conversation.id)))return json({ok:true,action:'suppressed_after_human_takeover'});const wait=Math.max(0,Number(pcy?.min_delay_seconds||0))*1000;if(wait)await new Promise(r=>setTimeout(r,wait));if(!(await gate(db,org,conversation.id)))return json({ok:true,action:'suppressed_after_human_takeover'});await send(raw,reply);return json({ok:true,action:'ai_reply',agent_key:pcy.agent_key})}catch(e){console.error(e);return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});